### ISSUE TITLE
Allow access to Algolia client in AlgoliaEngine

### ISSUE THREAD

**Issue by mikemclin** [laravel/scout#102]
**Current Implementation**: `Laravel\Scout\Engines\AlgoliaEngine` stores Algolia client as a protected `$algolia` property.  There is no getter for the property.

**Requested feature**: Allow access to the Algolia client using a `getClient()` method _(or similar)_.  So, you could do something like this:

`$algolia = app(EngineManager::class)->engine('algolia')->getClient();`

**Use case**: I keep seeing requests for Algolia-specific features both here, and elsewhere on the web.  Common requests involve setting up master/slave indices for sorting, configure/sync index settings, etc.  All of these requests are Algolia-specific and not generic enough for Scout.  If we had access to the Algolia client, we could build decorator traits (or whatever) for people that use Algolia and want functionality outside of the scope of Scout (similar to how the Laravel Filesystem allows access to the Amazon client for custom Amazon S3 functionality).

Currently, I am having to create a redundant Algolia client, and use that for anything custom.

**Comment by driesvints** [comment]
The problem with this is that "client" is a concept for Algolia while it may not be applicable to another engine and therefor it's not wanted on the `Engine` class. 

You can use the decorator pattern for this instead to decorate the `AlgoliaEngine` class and overwrite the methods which you want to adjust and even add extra functionality.

ServiceProvider (https://laravel.com/docs/5.7/scout#custom-engines):

```php
/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    resolve(EngineManager::class)->extend('algolia_custom', function () {
        $engine = app[EngineManager::class]->engine('algolia');

        return new CustomAlgoliaEngine($engine, new Algolia(
            config('scout.algolia.id'), config('scout.algolia.secret')
        ))
    });
}
```

Engine:

```php
use AlgoliaSearch\Client as Algolia;
use Laravel\Scout\Engines\AlgoliaEngine;
use Laravel\Scout\Engines\Engine;

class CustomAlgoliaEngine extends Engine
{
    /**
     * The Algolia Engine.
     *
     * @var \Laravel\Scout\Engines\AlgoliaEngine
     */
    private $engine;

    /**
     * The Algolia client.
     *
     * @var \AlgoliaSearch\Client
     */
    private $client;

    public function __construct(AlgoliaEngine $engine, Algolia $client)
    {
        $this->engine = $engine;
        $this->algolia = $algolia;
    }

    public function update($models)
    {
         // do custom stuff
    }

    public function delete($models)
    {
         return $this->engine->delete($models);
    }

    ....
}
```

**Comment by driesvints** [comment]
You can also use a callback for the `search` and `paginate` methods in order to access the Algolia client. Here's an example: https://github.com/ErickTamayo/laravel-scout-elastic/issues/24#issuecomment-345137669

I'll try to update the docs to make this more clear.
