### ISSUE TITLE
advanced search in multiple fields

### ISSUE THREAD

**Issue by cryptoBOOOOM** [laravel/scout#109]
Hello, how can i implement an advanced search?

Like

Search all books that have "javascript" in their title and the author contains "john".
I came up with something like : 
`\App\Model::search('javascript')->where('author','LIKE','%john%')->get()`
but there were no results....

**Comment by driesvints** [comment]
You can implement this functionality with a Macro on the builder. Try https://github.com/algolia/laravel-scout-algolia-macros/blob/master/src/macros.php for inspiration.
