### ISSUE TITLE
Wildcard searches

### ISSUE THREAD

**Issue by kirkegaard** [laravel/scout#110]
Hi, im trying to do a wildcard search with elasticsearch. Is it even possible? Ive looked at the driver for ES but cant really figure out if its even possible. I tried to do something like `Users::search(['wildcard' => ['name' => 'amb*']])` but thats not working. I didnt see anything in the documentation either so it might not be possible. I just wanted it confirmed before i looked into other solutions :)

This is my test query from es-head and it works like intended.

```
{"query":{"bool":{"must":[{"wildcard":{"name":"amb*"}}],"must_not":[],"should":[]}},"from":0,"size":50,"sort":[],"aggs":{},"version":true}:
```

**Comment by brino** [comment]
You don't really get to pass a raw query, just keywords. That being said, the current query scout executes for elasticsearch is a "match" on _all fields. Which does not allow wildcards.

I would probably look at [Elasticquent](https://github.com/elasticquent/Elasticquent) for this. OR ... maybe just execute a custom query behind scout's back!

Bind elasticsearch client into AppServiceProvider.php
```php
        $this->app->bind('Elasticsearch\Client', function ($app)
        {
                return Elasticsearch\ClientBuilder::create()
                     ->setHosts(config('scout.elasticsearch.config.hosts'))
                     ->build();
        });
```

Then you can execute a custom query in your controller/job/command like this ...
```php
     $params['index'] = config('scout.elasticsearch.index');
     $params['type'] = 'my_model';
     $params['body'] = ['wildcard' => ['name' => 'amb*'];
     $results = app('Elasticsearch\Client')->search($params);
     dd($results);
```
Obviously scout can't reproduce the eloquent models with the result this way ... but it might work for some cases.

**Comment by kirkegaard** [comment]
Thanks, but in this case that wont really fix my problem. I have fixed it by using https://github.com/ErickTamayo/laravel-scout-elastic driver instead. The only problem is that it does double asterisk searches like *amb* which is kind of icky.
