### ISSUE TITLE
Need more features to support ElasticSearch eg: min_score filter,mapping or language analyzers 

### ISSUE THREAD

**Issue by DesmondPang** [laravel/scout#112]
I am using ElasticSearch. It is great that Laravel scout support ElasticSearch natively. However, I hope more customised features/options will be added. For example, we can set min_score for the search result, mapping for datatype and the language analysers for other languages. 

Many Asian developers use ElasticSearch with language analyser plugins to support Asian languages full-text search.

Thank you.

**Comment by driesvints** [comment]
Going to close this as Elasticsearch support has been removed since. There are some third party packages on packages with an Elasticsearch engine for scout.
