### ISSUE TITLE
Add option to Queue specific models

### ISSUE THREAD

**Issue by n4p4** [laravel/scout#115]
It would be nice to be able to queue indexing for only specific models. For example, say I have a Person model and I have a Document model.

For the Person model, I don't want to or need to queue indexing because the data should be indexed right way and shouldn't cause any slowdowns.

However, for the Document model, if there is a rather large PDF or RichText document, and I need to dump the contents of that document and then index it, I would definitely want to use queuing.

Currently, Scout only allows for a Switch On / Switch Off for ALL models queuing option.

**Comment by driesvints** [comment]
Think you can achieve this by returning `null` from `syncWithSearchUsingQueue` on your model. Let me know if this works or not.
