### ISSUE TITLE
How to search given fields with the Elaticsearch engine？

### ISSUE THREAD

**Issue by i6448038** [laravel/scout#119]
For example，I wanna to search the field “name” in the type "users" with the default Elasticsearch，what should I do？I found nothing about the Elasticsearch engine in the document of laravel-scout

**Comment by paulvl** [comment]
You are talking about a relationship search right?
in that case you should do something like this, assuming that you have a relation named "user_type" which returns an UserType object that has a name attribute:

Modify `toSearchableArray` method on your User class

`

    public function toSearchableArray()
    {
        $array = $this->toArray();

        $extra_data = [];
        $extra_data['type_name'] = $this->user_type->name;

        return array_merge($array, $extra_data);
    }
`

**Comment by i6448038** [comment]
no no no ，I mean I wann to search a custom field in the ES type，for example， I wann to search only the name field or  anyother field which I wann to search of the user_type in the Elasticsearch，not all the fields in the user_type.

**Comment by moxoder** [comment]
I also interested in this issue.

**Comment by Muffinman** [comment]
It doesn't seem like you can - the `ElasticsearchEngine` class just passes an `_all` key to the ElasticSearch server.

You'll need to create a custom Search Engine to provide this feature yourself - or just use the `Elasticsearch\Clientbuilder` class directly.

The same goes for Boosting or any other advanced features which seem to be outside the scope of the scout project.

**Comment by rjbaker** [comment]
Perhaps the `Engine` abstract class could be updated to return the underlying "driver". This could be analogous to Laravel's filesystem disk implementation abstracting local filesystem and cloud providers. You can still access the underlying driver instance and any proprietary methods. The only complexity is  mapping the response into eloquent models.

**Comment by sede2** [comment]
I think you could extend your model and override toSearchableArray() only returning 'name', but you will have to reimport manually this model if the original gets changed.
