### ISSUE TITLE
Laravel Scout environment variables (driver, prefix) not being applied

### ISSUE THREAD

**Issue by prasadrajandran** [laravel/scout#121]
- Laravel Version: 5.3.22
- Scout Version: 1.1.8
- PHP Version: 5.6.25
- Database Driver & Version: mysql 5.7.14

### Description:
I'm running unit tests on my code and I've noticed that setting the following to `SCOUT_DRIVER=null` doesn't work. I get this error message in my log file `'ErrorException' with message 'Missing argument 1 for Illuminate\Support\Manager::createDriver()`. Setting it to `SCOUT_DRIVER='"null"'` works however.

The `SCOUT_PREFIX` property also doesn't seem to apply (when I'm not testing code and using the `algolia` driver). I've resorted to this method as a workaround:
```
public function searchableAs()
{
    return env('SCOUT_PREFIX', '') . 'mytable';
}
```

Anyone know what's going on? If it's a bug with the package or my code?

**Comment by divspace** [comment]
This is happening with the `1.1.10` release as well. I have to manually set the application ID and secret in my model, where previously I was just using `env()` to grab the values. This results in the following error:

```bash
AlgoliaSearch requires an applicationID
```

**Comment by telkins** [comment]
I've noticed the same problem with the prefix.  Is this ticket getting any traction/attention...?

**Comment by prasadrajandran** [comment]
@telkins, not as much as I'd have hoped for unfortunately.

**Comment by telkins** [comment]
@prasadrajandran Thx for the quick response.  I just edited my post...just in case you didn't see it.  :-)

**Comment by prasadrajandran** [comment]
@telkins, that's actually quite interesting. I think it should be considered a bug too. Let's see if this gets more attention from others.

**Comment by diquinnyonk** [comment]
Setting `SCOUT_DRIVER='"null"'` solved for me. Thanks

**Comment by prasadrajandran** [comment]
Closing this since it hasn't attracted much attention from other users.

**Comment by ambuilding** [comment]
@diquinnyonk 
- Thank you very much, it works, all the errors are disappear. 
- Could you tell me what's the difference between '"null"' and "null"?
- `<env name="SCOUT_DRIVER" value="null"/>` doesn't work, replace "null" with '"null"', then it works.
