### ISSUE TITLE
elasticsearch : parsing_exception: no [query] registered for [filtered]

### ISSUE THREAD

**Issue by wardwar** [laravel/scout#122]
please help. how to solve this error?

another error

```json
{
	"error": {
		"root_cause": [{
			"type": "parsing_exception",
			"reason": "no [query] registered for [filtered]",
			"line": 1,
			"col": 22
		}],
		"type": "parsing_exception",
		"reason": "no [query] registered for [filtered]",
		"line": 1,
		"col": 22
	},
	"status": 400
}
```

**Comment by kfchai** [comment]
I have just setup Elasticsearch 5.0 and Laravel Scout then came across this as well when I trigger get() function of the query builder. Realized that Elasticsearch 5.0 doesn't support **filtered** query, instead it has been replaced by **bool** query. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html

I did a little modification in ElasticSearchEngine.php (line 177) to make it works:
```
$searchQuery = [
            'index' =>  $this->index,
            'type'  =>  $query->model->searchableAs(),
            'body' => [
                'query' => [
                    'bool' => [
                        'filter' => $termFilters,
                         'must' => $matchQueries,
                    ],
                ],
            ],
        ];
```

**Comment by lamungu** [comment]
With ElasticSearch 5.0 released, should the driver be rightfully updated to abide to those changes?

**Comment by moxoder** [comment]
Elasticsearch 5+ is not supported properly, please fix it.

**Comment by rmff** [comment]
@wardwar 

Use temp fix suggested from @kfchai 

Inside: vendor\laravel\scout\src\Engines\ElasticsearchEngine.php
Method: performSearch
Replace $query by:
```
        $query = [
            'index' =>  $this->index,
            'type'  =>  $builder->model->searchableAs(),
            'body' => [
                'query' => [
                    'bool' => [
                        'filter' => $filters,
                        'must' => $matches,
                    ],
                ],
            ],
        ];
```

Gist for changed file [vendor\laravel\scout\src\Engines\ElasticsearchEngine.php](https://gist.github.com/rmff/f262ad5195b8fb9bf9aae9e61e323ced#file-vendor-laravel-scout-src-engines-elasticsearchengine-php)

**Comment by jmarcher** [comment]
ping @hernandev
Any ideas?

**Comment by moxoder** [comment]
Use your driver on the basis of basic Elasticsearch Engine through DI (service provider)

**Comment by sl0wik** [comment]
You can use tamayo/laravel-scout-elastic instead to resolve this issue.

**Comment by Michaeltlee** [comment]
"I'm not going to make any further updates to the ElasticSearch driver. " https://github.com/laravel/scout/pull/127 

I just copied the ElasticsearchEngine and made a new Elasticsearch5Engine file with the changes to the performSearch method mentioned above. And then followed the Laravel docs for creating and registering a custom engine. https://laravel.com/docs/5.3/scout#custom-engines.

**Comment by asolopovas** [comment]
+1 Any news on the fix?

**Comment by DMeganoski** [comment]
I left an example in issue #143 for those who are still struggling with this.

**Comment by driesvints** [comment]
Going to close this as Elasticsearch support has been removed since. There are some third party packages on packages with an Elasticsearch engine for scout.
