### ISSUE TITLE
$model->relation()->update() updating database but not algolia

### ISSUE THREAD

**Issue by scottgrayson** [laravel/scout#137]
``` 
$user = factory(App\User::class)->create();
    $user->profile()->update([
    'display_name' => 'findme',
    'bio' => 'user bio',
    'type' => 'band'
]);
```
Not Shown: Profile is created by the User Observer upon user creation

I have tried this in a test ran by phpunit and in `php artisan tinker`
Database updates as expected. 
Algolia entry is created for profile but not updated

**Comment by scottgrayson** [comment]
``` 
$profile->display_name = 'findme';
$profile->save();
```
works. 

is update() not supported because it bypasses some eloquent event?

**Comment by logan-jobzmall** [comment]
@scottgrayson why did you close this? I was finding something similar using Query Builder.
