### ISSUE TITLE
Null driver causes excess SQL queries to be made

### ISSUE THREAD

**Issue by jhoff** [laravel/scout#144]
Maybe I'm missing something here but it seems that on a model what uses the `Searchable` trait, even if the driver for scout is `null`, it still makes additional queries under the hood during normal model operations. This causes performance issues with unit tests ( especially on models with high complexity / test coverage ).

Example:

Factory create without the searchable trait;

```
$factory->define(App\ProductCategory::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->word,
        'parent_id' => null
    ];
});
```

```
factory(ProductCategory::class)->create()
```

```
// only one sql insert statement, as expected
insert into "product_categories" ("name", "parent_id", "updated_at", "created_at") values (?, ?, ?, ?)
```

When the `Searchable` trait is added ( with the scout driver set to null ), there are two additional queries made to the database:

```
insert into "product_categories" ("name", "parent_id", "updated_at", "created_at") values (?, ?, ?, ?)
select * from "product_categories" where "product_categories"."id" in (?)
select * from "product_categories" where "product_categories"."parent_id" in (?)
```

Is it not the case that setting the `Searchable` trait to null should effectively disable it completely? If not, is there a better way to do that so that my unit tests don't take twice as long to run as they should?

**Comment by zanematthew** [comment]
Haven't test this, but shouldn't setting the scout driver to `null` for your testing environment address the issue?

**Comment by driesvints** [comment]
Setting the driver to null indeed uses the `NullDriver` but under the hood the `Builder` class can still make queries to fetch models. Setting the driver to null only disables any requests to the search engine. If you want to completely disable this you'll need to remove the `Searchable` from the model.
