### ISSUE TITLE
Feature Request: add whereIn() and (more importantly) whereNotIn() method to builder

### ISSUE THREAD

**Issue by DMeganoski** [laravel/scout#145]
I have come across a roadblock with scout.

What I am trying to do is filter the results that the user has already selected from a paged table.

I can perform a comparison after the search has been performed, however since my results are paged, this would disrupt the number of results per page.

I essentially need the filter on the query level.

I am using my own driver for elasticsearch and already know how I would like to filter the records via the api, however there is not enough room for options for me to provide the excluded data.

I know you guys have a lot on your hands, but if you could figure out a way to implement these methods on the builder it would be much appreciated. Thanks.

**Comment by htunlogic** [comment]
Same here, potential solution would be to run the regular query for "whereIn" filters and then just:

```
return $query->whereIn(
        'id', User::search($search)->get()->pluck('id')->flatten()
);
```

Its not the most elegant of them all, but it does the job.

**Comment by joseluisq** [comment]
The builder also should support: count(), raw queries, etc... https://github.com/laravel/scout/blob/3.0/src/Builder.php

**Comment by sanjayojha** [comment]
Yes, it is much needed.

**Comment by julienbourdeau** [comment]
Raw queries are now supported: https://github.com/laravel/scout/pull/195

You can also add count with a Macro: https://github.com/algolia/laravel-scout-algolia-macros/blob/master/src/macros.php#L7-L18

**Comment by driesvints** [comment]
This was denied in https://github.com/laravel/scout/pull/141 so going to close this. As @julienbourdeau suggests, you can add this behavior with a macro.
