### ISSUE TITLE
Conditional indexing

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/scout#148]
Hi,

Is there a way to conditionally index a model record?

The search database will be publicly available, I'd rather not index records marked as "unpublished" by users.

I've tried this, but I see no difference in ElasticSearch results:
```
/**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        if(!$this->published) { // The condition
          $this->unsearchable();
          return;
        }
        $array = $this->toArray();
        //....
        return $array;
     }
```

Kind regards,

Sander

**Comment by Harti** [comment]
May I ask, what's your solution? 😐
