### ISSUE TITLE
Driver [elasticsearch] not supported

### ISSUE THREAD

**Issue by prakash-chokalingam** [laravel/scout#149]
I am getting this error when I trying to connect elasticsearch via scout.

**Comment by mtdavidson** [comment]
Elastic was supported at some point during 1.x but was removed in version 2.0 ( https://github.com/laravel/scout/commit/15f519405ee57f28f9aca510df55fe18366ac97a ) if you want to use it you'll need to add it via a package not sure if it currently works with 2.0 but https://github.com/ErickTamayo/laravel-scout-elastic might be a place to start.

**Comment by prakash-freshdesk** [comment]
HI thanks I tried that above package, done every thing but the data is not adding to the index, can you please guide me to the following question,

http://stackoverflow.com/questions/41467964/laravel-scout-with-elastic-search-not-working

**Comment by lukepolo** [comment]
You need to create your own driver , here is what i have working for me

https://gist.github.com/lukepolo/b63d303b076a7cd58bbaa54b3b9f0370

**Comment by Muffinman** [comment]
We have Elasticsearch working fine with scout on 5.3 and 5.4, but I'm afraid it's not much use without customising the mappings yourself.

Our solution was to use our own Artisan commands for creating the index / mappings / aliases and then letting scout just handle in indexing.

**Comment by paulocastellano** [comment]
Use this package https://github.com/ErickTamayo/laravel-scout-elastic
