### ISSUE TITLE
Add a readme.

### ISSUE THREAD

**Issue by Tjoosten** [laravel/scout#15]
For now nex user's don't know how to implement this in laravel app's. 
I think we need to document this in a readme

**Comment by hernandev** [comment]
Pretty sure it will gonna pop on the laravel docs pretty soon, as other optional laravel packages, the readme just links there

**Comment by taftse** [comment]
Documentation can be found here https://laravel.com/docs/master/scout

**Comment by tomschlick** [comment]
Just added a readme.md file in #25 that links back to the documentation & displays the build statuses
