### ISSUE TITLE
How to index conditionally?

### ISSUE THREAD

**Issue by sandervanhooft** [laravel/scout#153]
Hi,

Is there a way to conditionally index a model record?

The search database will be publicly available, I'd rather not index records marked as "unpublished" by users.

I've tried this, but I see no difference in ElasticSearch results:

```
/**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        if(!$this->published) { // The condition
          $this->unsearchable();
          return;
        }
        $array = $this->toArray();
        //....
        return $array;
     }
```

Kind regards,

Sander

**Comment by michelecurletta** [comment]
something like another criteria after [this condition](https://github.com/laravel/scout/blob/2.0/src/Searchable.php#L51).

```
`$models = $models->filter(function ($model, $key) {

    return $model->mustBeSearchable();

});`
```

**Comment by Harti** [comment]
I created a gist to sort of alleviate the issue. 
Essentially I'm overriding a few methods of the Searchable trait.

https://gist.github.com/Harti/ec1fcd28b162bbb2e7fe06ce2df22275

**Comment by sandervanhooft** [comment]
@Harti, Thanks! Your trait override seems the best maintanable solution for now.

**Comment by sandervanhooft** [comment]
@Harti, What do you mean by this?

> Make sure to update your index afterwards (alternatively, update/save the models that you want to be affected).

**Comment by Harti** [comment]
@sandervanhooft The respective search engine's indexing happens only when you store or update an eloquent model in your database, or when you run `php artisan scout:import "App\MyModel"`. 
If you only update the code without letting your search engine re-index the records, you will still find records that are supposed to be hidden.

My trait override simply prevents the models from being added to the search engine index.

**Comment by Harti** [comment]
@sandervanhooft please take note that I updated my Gist to fix an issue with it on [line 39](https://gist.github.com/Harti/ec1fcd28b162bbb2e7fe06ce2df22275#file-searchable-L39).

**Comment by jorenvanhee** [comment]
You could also return an empty array in the `toSearchableArray` method.

```
    public function toSearchableArray()
    {
        if ($something === true) {
            return [];
        }

        return $this->toArray();
    }
```

**Comment by michelecurletta** [comment]
@taylorotwell this seems to be a common issue, what about adding this feature out of the box?

**Comment by julienbourdeau** [comment]
I think returning an empty array is the way to go. I'm not sure what you can't do with that.

**Comment by royduin** [comment]
Just returning an empty array didn't work for me. But running `$this->unsearchable();` before returning the empty array works great.

**Comment by julienbourdeau** [comment]
I believe it's because this model was already in the index. Can you make sure your index is empty and try again without the unsearchable() call?

**Comment by royduin** [comment]
@julienbourdeau, that's true but in my case when a entity should be indexed is conditionally. It's possible to have one in the index and after changing something it should not be indexed anymore. In that case `$this->unsearchable();` is required I think.

**Comment by DougSisk** [comment]
We have draft products in our e-commerce system and this was causing all kinds of problems when they were updated in the administrative area.

My solution was to add `Product::disableSearchSyncing();` to a service provider and just manually throughout the app run `searchable()` and `unsearchable()`. Very annoying and I agree there should be some simpler way to toggle wether or not the model should be allowed to be indexed.

**Comment by aconital** [comment]
@royduin I tried your solution. Although it's not adding the object as an index but it's is being counted as an operation.

**Comment by celcius-jochen** [comment]
You could also store the `$this->published` value in the Algolia index for each record.
When you query Algolia, add a filter `published=1` to the `searchParams`.
