### ISSUE TITLE
Raw Scout search results with get()

### ISSUE THREAD

**Issue by kapsoft** [laravel/scout#156]
I've been trying to get raw scout search results (not paginated) via:
         $results = \App\Vertex::search($term)->get(); 

But seems its limited by Algolia client lib "hitsPerPage" of 20 (in index.php).

Is there anyway around this via Scout? (I'm try to do manual pagination myself since filtering is limited).

Thanks in advance.

DJK

**Comment by mattdfloyd** [comment]
You can override the `search` method of the `Searchable` trait on the model to change the number of results.

```php
    public static function search($query, $callback = null)
    {
        $builder = new Builder(new static, $query, $callback);
        $builder->limit = 30;

        return $builder;
    }
```

see https://github.com/laravel/scout/blob/3.0/src/Searchable.php#L86
