### ISSUE TITLE
Call to undefined method Laravel\Scout\Builder::skip()

### ISSUE THREAD

**Issue by kickthemooon** [laravel/scout#165]
I am trying to implement  search with load more button instead of pagination.

Unfortunately it seems that scout has only the take() method but no skip() method?

I am searching for ideas, any suggestions?

**Comment by desh901** [comment]
Yeah this is quite annoying. Btw this is a little workaround that worked for me:

```
$page = (int)$skip / $take;
$paginator = $elements->paginate($take, '', $page);
$collection = $paginator->getCollection();
```

**Comment by kickthemooon** [comment]
@desh901 nicee, thanks.
