### ISSUE TITLE
Listening for eloquent events stops scout from syncing for those events 

### ISSUE THREAD

**Issue by sullyfischer** [laravel/scout#169]
I’ve been listening for eloquent events by defining the `$events` array which was introduced in Laravel 5.4

But now I’m facing a problem. For example, when I listen for the `created` event of a model, it no longer syncs it to the Laravel Scout after hitting `save()` method. 

The same goes for the other eloquent events.

**Comment by driesvints** [comment]
Think this was fixed with https://github.com/laravel/scout/pull/252. Feel free to ping me if this is still a problem.
