### ISSUE TITLE
Algolia Driver not returning an array

### ISSUE THREAD

**Issue by kinnedev** [laravel/scout#178]
Hi!

When using Scout with Algolia driver. When sending a post via Axios to the below code a collection is returned: 

 ```
return User::search($request->search)->get();
```

Now if I just dd to a page an array is returned. 

This seems to only be happening with search(). 

Any help would be greatly appreciated!

Thank you.

**Comment by mariapaulinar** [comment]
Same here :(

**Comment by DMeganoski** [comment]
I haven't used axios, but I have heard of similar issues. You should be able to do something like this:

```php
    return User::search($request->search)->get()->toJson();
```

**Comment by kinnedev** [comment]
I actually found my issue. 

On my local env I was annually deleting records from my database and that was throwing of scout. 

I hope this helps you guys .
