### ISSUE TITLE
Calling scout:import results in Call to undefined method Illuminate\Database\Query\Builder::searchable()

### ISSUE THREAD

**Issue by DMeganoski** [laravel/scout#179]
I'm confused what exactly is going on here. I wrote a custom driver for elasticsearch a few months ago, and although the driver seems to be functioning correctly, scout is giving me an issue when I try to import my existing records into elasticsearch, which essentially never makes it to the driver itself. 

here is the stack trace. hopefully someone can give me some insight as to what is going on.
```
[2017-05-03 15:19:43] development.ERROR: BadMethodCallException: Method searchable does not exist. in /home/darryl/web/laravel-slab/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /home/darryl/web/laravel-slab/vendor/laravel/scout/src/Searchable.php(112): Illuminate\Support\Collection->__call('searchable', Array)
#1 /home/darryl/web/laravel-slab/vendor/laravel/scout/src/Searchable.php(99): Smargasy\Contacts\Models\Contact->searchable()
#2 /home/darryl/web/laravel-slab/vendor/laravel/scout/src/Console/ImportCommand.php(43): Smargasy\Contacts\Models\Contact::makeAllSearchable()
#3 [internal function]: Laravel\Scout\Console\ImportCommand->handle(Object(Illuminate\Events\Dispatcher))
#4 /home/darryl/web/laravel-slab/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#5 /home/darryl/web/laravel-slab/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#6 /home/darryl/web/laravel-slab/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/darryl/web/laravel-slab/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/darryl/web/laravel-slab/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/darryl/web/laravel-slab/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Scout\Console\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/darryl/web/laravel-slab/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/darryl/web/laravel-slab/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/darryl/web/laravel-slab/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
```

**Comment by morloderex** [comment]
Have you added the searchable trait to your modal?

**Comment by DMeganoski** [comment]
yep, the model definitely has the trait on it. Otherwise, it would have resulted in a 'makeAllSearchable' does not exist. And the searchable function definitely exists directly under makeAllSearchable. However, since it calls `$self = new static; $static->newQuery()' it returns an instance of Eloquent\Builder, which returns an instance of Query\Builder, and the __call function does not seem to know what to do with 'searchable'

It should also be noted that I'm using Laravel 5.3 and Scout 2.*

**Comment by DMeganoski** [comment]
Hmm... So I started going through some of the other files in the repository and found the `SearchableScope`, which is a global scope that is added to the model in the `Searchable::bootSearchable()` method. This adds the `searchable` and `unsearchable` methods to builder.

The issue seems to be that this method is never called. I can't find a reference to it anywhere in the code. Is this something that the framework is supposed to be calling dynamically based on the trait name?

For now, this is a workaround:
```php
public static function boot() {
		
		static::bootSearchable();
		
	}
```

**Comment by DMeganoski** [comment]
I just realized this was occurring with some models, and not others. It turns out that I had forgot to include the `parent::boot()` which only purpose is to call `static::bootTraits()` in my model's override (which is why it did not cause issues until now).

Sorry, my mistake. I'll close the issue.

**Comment by prototypicalDave** [comment]
@DMeganoski thanks for that. Saved me a lot of time.

**Comment by jubaedprince** [comment]
@DMeganoski I am facing the same issue. Can you help me solve this issue please? ``
   BadMethodCallException  : Call to undefined method Illuminate\Database\Eloquent\Builder::searchable()

  at /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50
    46|      * @throws \BadMethodCallException
    47|      */
    48|     protected static function throwBadMethodCallException($method)
    49|     {
  > 50|         throw new BadMethodCallException(sprintf(
    51|             'Call to undefined method %s::%s()', static::class, $method
    52|         ));
    53|     }
    54| }

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::throwBadMethodCallException("searchable")
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:36

  2   Illuminate\Database\Eloquent\Builder::forwardCallTo(Object(Illuminate\Database\Query\Builder), "searchable", [])
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1356

  3   Illuminate\Database\Eloquent\Builder::__call("searchable", [])
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/scout/src/Searchable.php:129

  4   App\MoneyRequisition::makeAllSearchable()
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/scout/src/Console/ImportCommand.php:43

  5   Laravel\Scout\Console\ImportCommand::handle(Object(Illuminate\Events\Dispatcher))
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  6   call_user_func_array()
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  7   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  8   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  9   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Container/Container.php:576

  10  Illuminate\Container\Container::call()
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  11  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/jubaedprince/Codes/alfred-v2/vendor/symfony/console/Command/Command.php:255

  12  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  13  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/vendor/symfony/console/Application.php:934

  14  Symfony\Component\Console\Application::doRunCommand(Object(Laravel\Scout\Console\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/vendor/symfony/console/Application.php:273

  15  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/vendor/symfony/console/Application.php:149

  16  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  17  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:133

  18  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /home/jubaedprince/Codes/alfred-v2/artisan:37``

**Comment by jubaedprince** [comment]
Thanks! This solved my issue, needed to put `parent::boot()` in the `__consruct()` method
