### ISSUE TITLE
Improve search results by feeding back user activity

### ISSUE THREAD

**Issue by wheredidgogogo** [laravel/scout#18]
Hi Guys,

This is not so much an issue, as a feature request.  I've been using Algoia with Laravel for a while now and one of my big complaints is the inability to send user activity back to the Algolia algorithm for each search term.

I record clicks, purchases etc and use this to rank the results however this applies across the board and not to individual search terms.

If there is anyone from Algolia working on this tool or reading this thread please consider allowing user activity for each search term to be fed back into the algorithm :)

Thanks

Anthony

**Comment by JanPetr** [comment]
Hello @wheredidgogogo,
thanks for the question. It's one of advanced use-cases and therefore it, with highest probability, won't be part of Scout.

I can see you already reached Algolia's support. I will discuss your use-case with my colleagues and get back to you as soon as I have aswer for you.

Thanks, Jan from Algolia

**Comment by wheredidgogogo** [comment]
Excellent,

Thanks Jan

I've been talking to Martin Salle in your office who is on holidays at the moment.

I built a quick test site to mess around with some of the geo-search functions in Algolia - http://192.241.221.130/ - you will need to change your location to somewhere in Australia to give it a test.

The results would be so much better if I could feed back user actions like clicks and time on link for each keyword.

Cheers

Anthony

**Comment by wheredidgogogo** [comment]
Excellent - thanks @JanPetr

I've been messing around with the Algolia geo functions and built this little test site: http://46.101.121.125/

You'll need to change your location to somewhere in Australia to test. 

It would be excellent if I could feed back user actions such as clicks, time on link etc back into the algorithm for each keyword.

Just on another note, when using the geo-functions (aroundLatLng) it doesn't return a full data set.  It seems to limit the number of results returned.

Cheers

Anthony

**Comment by julienbourdeau** [comment]
Hi @wheredidgogogo,

In case people read this later: I would advise to use javascript (InstantSearch) to query Algolia and display the result, then you can send user activity to your server. As soon as you update the data in your model, it will be sync with Algolia.
