### ISSUE TITLE
Algolia results limit of 1000 items.

### ISSUE THREAD

**Issue by jeverington** [laravel/scout#180]
I have a record set of 5000+ records and when returning a set of results via scout thats over 1000 records the paginator shows the correct number of pages for the total set, but on selection of any page that would contain item 1001 or more it fails to show.
I think this is related to the constraint of 1000 records that Algolia will return. You can set the setting "paginationlimitedto", but not via scout.
Would there be a way to pass this so I can up the return limit or be able to limit the paginator to only show up to 1000 results worth of pages.

**Comment by FarzanDalaeeBamilo** [comment]
+1

**Comment by julienbourdeau** [comment]
Hi,

You can use the callback to pass extra parameters.

```php
$res = App\Airport::search('', function ($algolia, $query, $options) {

    $extraOptions = [
        'paginationlimitedto' => 5000,
    ];

    $options = array_merge($options, $extraOptions);

    return $algolia->search($query, $options);
});
```

**Comment by jeverington** [comment]
Hi Julien,

Thanks for the comment. I think this would solve my problem, but it still goes agains the idea of having a abstracted search provider. I currently swap between algoilia when hosted and elasticsearch locally.

**Comment by timbogdanov** [comment]
Unknown parameter: paginationLimitedTo

**Comment by timbogdanov** [comment]
> Hi,
> 
> You can use the callback to pass extra parameters.
> 
> ```
> $res = App\Airport::search('', function ($algolia, $query, $options) {
> 
>     $extraOptions = [
>         'paginationlimitedto' => 5000,
>     ];
> 
>     $options = array_merge($options, $extraOptions);
> 
>     return $algolia->search($query, $options);
> });
> ```

this does not work

`Unknown parameter: paginationLimitedTo`

**Comment by tobz-nz** [comment]
The correct way to set the `paginationLimitedTo` value is:

```php
$res = App\Airport::search('', function ($algolia, $query, $options) {
    $algolia->setSettings([
            'paginationLimitedTo' => 20000, // 20,000 is the maximum allowed
    ]);

    return $algolia->search($query, $options);
});
```

...at least it works for me :)

**Comment by julienbourdeau** [comment]
@tobz-nz This will make an additional set_settings http call before the search call. The set_setting call only need to be made once.
