### ISSUE TITLE
How to import a larg table? Query scanning too much rows

### ISSUE THREAD

**Issue by 182050940** [laravel/scout#182]
scout:import use a query like:

```
select * from `articles` where `articles`.`deleted_at` is null order by `id` asc limit 500 offset 1000000
```
select query with offset limit is too much slow

**Comment by driesvints** [comment]
This should now be chunked, can you check again in the latest version and report if this is still a problem? Thanks!

**Comment by yuloh** [comment]
It is chunking but it looks like it's [using `chunk`](https://github.com/laravel/scout/blob/8177460f69cb1eb1d4ce857fdcd39a52c3c7c575/src/SearchableScope.php#L34) which [uses limit/offset](https://github.com/laravel/framework/blob/d6fc4cfa470b2807c50f8371739627aea32a34fc/src/Illuminate/Database/Concerns/BuildsQueries.php#L28).

To prevent using limit/offset it would need to use [chunkById](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Query/Builder.php#L2225) instead.

**Comment by driesvints** [comment]
@yuloh can you send in a PR with a test?
