### ISSUE TITLE
Paginated data format Issue

### ISSUE THREAD

**Issue by fakiolinho** [laravel/scout#184]
Paginated `data` in last page are returned as an Object (not an Array) as shown below:

<img width="575" alt="screenshot at may 17 00-09-15" src="https://cloud.githubusercontent.com/assets/2962687/26128521/5a08dd02-3a95-11e7-9bb2-742f4dc56fa6.png">

This happens only in last page while for all the others i get an Array as usual:

<img width="597" alt="screenshot at may 17 00-12-28" src="https://cloud.githubusercontent.com/assets/2962687/26128578/88b7c820-3a95-11e7-8c96-765fe66a5e0b.png">

This is my Model:

```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model {
  use Searchable;

  protected $guarded = ['id', 'created_at', 'updated_at'];
}
```

and this is my controller's method:

```php
public function index(Request $request) {
  $count = $request->input('count', 10);
  $searchTerm = $request->input('searchTerm', null);

  $posts = \App\Post::search($searchTerm)->paginate($count);

  return [
    'data' => [
      'posts' => $posts
    ]
  ];
}
```

Thanks!!!

**Comment by phppirate** [comment]
Having the same issue. Did you find a way to work around this?

**Comment by fakiolinho** [comment]
Unfortunately not @phppirate I 've removed Scout since then 🤕

**Comment by phppirate** [comment]
@fakiolinho what do you use as an alternative?

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by hareku** [comment]
@driesvints Hi
I have same problem.
When I use the scout pagination, I got a non array data property. That is an object that keyed by nums (0,1,2...).

How do I solve this?

algolia/algoliasearch-client-php: 2.2.3
laravel/scout: v7.1.1

**Comment by driesvints** [comment]
I feel like we're missing a `values` call on this collection here. I think that might be causing it: https://github.com/laravel/scout/blob/7.0/src/Builder.php#L269-L271

**Comment by iamgergo** [comment]
Hi, @driesvints,

I took a look at this issue while using Scout, but for me, it was working well.

Then I found this PR https://github.com/laravel/scout/pull/372, which solved this bug. 
Versions bigger than 7.1.2 should work well.

**Comment by nunomaduro** [comment]
Thanks for clarifying this issue @iamgergo.
