### ISSUE TITLE
How to use offset and limit

### ISSUE THREAD

**Issue by ujwaldhakal** [laravel/scout#185]
As in api the pagination is not possible so have to use limit and offset which is not possible in algolia, any other ways to do it so?

**Comment by julienbourdeau** [comment]
The paginator accepts the page number as a third parameter. If I undertood properly you should get something like

```php
$page = $offset / $limit;
Model::search($query)->paginate($limit, '', $page);
```

**Comment by ujwaldhakal** [comment]
yeah its working fine !
