### ISSUE TITLE
use scout on a model there is a mysql view

### ISSUE THREAD

**Issue by physio** [laravel/scout#199]
good morning, sorry for my english.
I have created a mysql view in db (there is a join between two tables). In laravel i have created a model where the $table property is my db view. I want to use scout for filter the datas from a list paginate. 
I undestand that scout update the index when i add/update/delete a table's row. But in this case the the situation is different because the data in my model collection changes when i add/update/delete row into 2 db tables.
can you help me?

regards

**Comment by DMeganoski** [comment]
You can use [model events](https://laravel.com/docs/5.4/eloquent#events) and use `touch()` on the relation to update related models and indexes.

For example, let's say this is in the User model:
```php
public function toSearchableArray() {
	$attributes = $this->attributes;
	$attributes['projects'] = implode(',', $this->projects()->pluck('name'));
}
```

Then in the 'Project' model:

```php
	protected static function boot() {
		
		static::updated(function ($model) {
			$model->user->touch();
		});
		
		parent::boot();
	}
```

This will make the make it so you can search project names on the user model, and it will update the index every time a project is updated.

**Comment by physio** [comment]
Hello @DMeganoski, thank you for your support.
I guess I did not understand your reasoning, sorry.
You suggest:
1: I override toSearchableArray () in the model that refers to db view
2: Extending the boot () method in the model that refers to the db table

My perplexities are:
How do I add the surname to the index as well?
How do i add another model (the join join table)?

regards

**Comment by hhsadiq** [comment]
@physio did you find a solution to make it work with SQL views?

**Comment by DMeganoski** [comment]
Sorry, I had not seen that you were asking for clarification.

The `touch()` method simply updates the `'updated_at'` column, but this would be enough to trigger the update of the index, I am pretty sure. As long as that is one of the fields you have indexed.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
