### ISSUE TITLE
Call to undefined method searchableUsing()

### ISSUE THREAD

**Issue by NoorAdiana** [laravel/scout#201]
I sometime get error this when running comman ```scout:import```

```Call to undefined method Illuminate\Database\Query\Builder::searchableUsing()```

I no idea whAt it is, in my local is fine but in server sometime i got this error.

I running ```scout:import``` of 10 times then 4 or 2 is failed whit error.

Can help me?

This is model part

```
/**
 * Enable for as you type feature
 *
 * @var boolean
 */
public $asYouType = true;

/**
 * Get the indexable data array for the model.
 *
 * @return array
 */
public function toSearchableArray()
{
    $array = $this->toArray();

    $array = array_merge($array, [
        'donatur' => $this->donatur->toArray(),
        'relawan' => $this->relawan ? $this->relawan->toArray() : null
    ]);

    return array_dot($array);
}
```

Server : Ubuntu 16.04 with PHP 7.1, Scout ^3.0 with TNTSearch

**Comment by tomvo** [comment]
Did you try restarting your queue worker?

**Comment by jcorrego** [comment]
I have the same issue, and it doesnt solve with restarting the queue

**Comment by raulsh** [comment]
I have the same issue too. There is a solution? I searched in source code and there is nothing abount searchableUsing() method, only calls to this method.
