### ISSUE TITLE
Test with models indexed by Laravel Scout fails

### ISSUE THREAD

**Issue by standaniels** [laravel/scout#202]
I'm writing a test for finding models with Scout. I'm on Laravel 5.4 and use the provider `"tamayo/laravel-scout-elastic": "^3.0"`.

It seems that in my tests indexing the created items isn't completed when I start searching for a model. Is this true? How can I fix this? My queue is already set to sync and `SCOUT_QUEUE` is set to `false`.

Here is an example of a test that keeps failing (Failed asserting that search results contain the given post). Any help is greatly appreciated.

```php
<?php

namespace Tests\Unit;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Tests\TestCase;

class SearchTest extends TestCase
{
    /** @test * */
    public function it_searches_the_whole_category_tree_for_posts()
    {
        // Given
        /** @var Category $parentCategory */
        $parentCategory = \factory(Category::class)->create([
            'title' => 'myParentCategory',
        ]);
        /** @var Category $childCategory */
        $childCategory = \factory(Category::class)->create();
        $childCategory->makeChildOf($parentCategory);
        /** @var Post $post */
        $post = \factory(Post::class)->create([
            'user_id' => \factory(User::class)->create()->id,
        ]);
        $post->requestCategories()->attach($childCategory);

        // When
        $searchResults = Post::search('myParentCategory')->get();

        // Then
        $this->assertTrue($searchResults->contains($post), 'Failed asserting that search results contain the given post.');
    }
}
```

**Comment by standaniels** [comment]
Or would asserting the model's `toSearchableArray` method be sufficient?

**Comment by zanematthew** [comment]
This could probably be closed, also is posted here; https://github.com/ErickTamayo/laravel-scout-elastic/issues/67

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
