### ISSUE TITLE
Run php artisan migrate: refresh --seed exception in lumen.

### ISSUE THREAD

**Issue by seekcx** [laravel/scout#206]
https://github.com/laravel/scout/blob/3.0/src/ScoutServiceProvider.php#L29

Lumen does not have `path.config`.

**Comment by sudomabider** [comment]
I think it's because Lumen doesn't have a a standard location for putting config files like Laravel does. Basically it's up to Lumen users to specify what the config path is.

For example in your `AppServiceProvider` put in 
```
$this->app['path.config'] = base_path('config'); // or whatever your path is
```

**Comment by seekcx** [comment]
@sudomabider Well, that's really a good idea!
