### ISSUE TITLE
Limiting calls to Algolia API to save money

### ISSUE THREAD

**Issue by dgursh** [laravel/scout#208]
Hi,

I've integrated Laravel Scout and Algolia driver with my app. I'm currently on the free plan for alogolia that allows for 100,000 API calls.

Currently, when a user performs a search on my site it makes 5 api calls, one to each of my 5 indexes like so...

```
$objects = Model1::search($request->input('q'))->paginate(20);
$objects2 = Model2::search($request->input('q'))->paginate(20);
$objects3 = Model3::search($request->input('q'))->paginate(20);
$objects4 = Model4::search($request->input('q'))->paginate(20);
$objects5 = Model5::search($request->input('q'))->paginate(20);
```

Then I render out all of these objects in the view. The problem I'm noticing is that the API calls are accumulating very quickly since every search request performs 5 separate API calls. This effectively reduces my 100K API calls to only 20K since every search is 5x the normal amount :(

Is there anyway to reduce these calls to just a single API call with Scout where I can effectively accomplish the same thing and search 5 different indexes?

Thanks in advanced. :)

**Comment by julienbourdeau** [comment]
Hi,
You cannot target multiple indices at once with Scout. Also, note that Algolia counts operation of its side, not HTTP calls. If you could group them into one call, it would still count 5 operations.

I would recommend you to implement cache, I think it's the best way to _save operations_.
