### ISSUE TITLE
Why use "??" operator (only use for php version > 7) if php minimum required in composer json is >= 5.6.4

### ISSUE THREAD

**Issue by brocard** [laravel/scout#210]
Exaclty in the line  33 at the file SearchableScope.php

``$builder->chunk($chunk ?? config('scout.chunk.searchable', 500), function ($models) use ($builder) {``

**Comment by Artistan** [comment]
#211 - fixed in  v3.0.7
Good call, I am using 7.1 on our current project, but that could cause some major issues.

**Comment by brocard** [comment]
Thanks @Artistan

**Comment by markwalet** [comment]
Issue is fixed, I think you can close this issue now.
