### ISSUE TITLE
Trigger Model -> Save() Inside a queued job?

### ISSUE THREAD

**Issue by atweedie** [laravel/scout#218]
We are currently using a command that triggers a job  to queue the database insert query upon on save() on SQS. 
Doing so seems to have stopped Scout from triggering its indexing of the model.

Scout triggers when we move the code from a job to a command (Therefore not dispatching  the job) it indexes the model fine either with scout queue set to true or false.

**Comment by ryancwalsh** [comment]
I don't know if this is what you're trying to do, but https://stackoverflow.com/a/42981667/470749 helped me see that I needed to remove `SerializesModels`.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
