### ISSUE TITLE
Scout index  table in disorder in Elasticsearch

### ISSUE THREAD

**Issue by dker92** [laravel/scout#229]
Hello,
I use scout to index my table in my Elastic Cloud , but I noticed scout doesn't index the rows of my  table in the same order in Elasticsearch than my sql table, and so when i use match_all I got  my document in disorder, is there a way for scout to index my row in order ?

**Comment by driesvints** [comment]
Seems like a Elasticsearch specific issue. So going to close this. Feel free to reply if you're still having issues with this.
