### ISSUE TITLE
Support relations withCount() method

### ISSUE THREAD

**Issue by yingdongzhang** [laravel/scout#230]
`withCount()` doesn't work with the `::search()` method, as the `search()` method doesn't return a QueryBuilder but a \Laravel\Scout\Builder instance, and it can't be chained to a QueryBuilder either. Is this expected to be supported soon?

For instance if I have Question & Answer, one Question can have more than one Answers.

Currently both of these two queries will throw a method not defined exception, depends on the order you call them:

```
$questions = Question::search('hello')->withCount('answers')->get();
$questions = Question::withCount('answers')->search('hello')->get();
```

**Comment by julienbourdeau** [comment]
If you set the `withCount` property in your model, it will be taken into account.

Otherwise, if it has to be optional because you don't want to load the count all the time, you can leverage the macros.

```php
    Laravel\Scout\Builder::macro('withCount', function () {
        $this->model->withCount(['people']);

        return $this;
    });
```

You also have to implement the `withCount` method in the model:
```php
    public function withCount(array $withCount)
    {
        $this->withCount = $withCount;

        return $this;
    }
```

The you will be able to use it this way:
```php
Question::search('hello')->withCount(['answers'])->get();
```

**Comment by driesvints** [comment]
https://github.com/laravel/scout/pull/290 Got merged so perhaps that solves your problem? 

Or you can try @julienbourdeau's suggestion.

**Comment by Div-Man** [comment]
`Post::search('hello')->query(fn($query) => $query->withCount('answers'))->get());`
