### ISSUE TITLE
shouldBeSearchable() not respecting the scout:import command

### ISSUE THREAD

**Issue by hhsadiq** [laravel/scout#244]
Right now the shouldBeSearchable() has no effect while running the `php artisan scout:import MODEL` command. Is that by purpose or bug?

Branch: master

**Comment by aconital** [comment]
I believe this is a bug. I'm having the same problem

**Comment by aconital** [comment]
Thanks @kfirba.

**Comment by nunomaduro** [comment]
@hhsadiq This issue has been fixed. Do you mind of closing it?

**Comment by hhsadiq** [comment]
@nunomaduro closed. Thanks

**Comment by Casmo** [comment]
For those coming from Google and still running into this problem: use `scout:flush <model>` before importing the batch.
