### ISSUE TITLE
Search results object type error

### ISSUE THREAD

**Issue by rabpeter** [laravel/scout#246]
This my current scout codes.
$providers = Provider::search($query)->where('type', 2)->get();

Some times results is array like this
[{'id': '89999', 'first_name': 'adf', ....},
{....},.....
]

But sometimes wrong results like this
{'7': {'id': '9989', 'first_name': 'Blabla'}...., '8': {....}}

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
