### ISSUE TITLE
Request: Adding support for browse() method

### ISSUE THREAD

**Issue by hhsadiq** [laravel/scout#248]
Just a request

Add support for browse() method.

> The search method cannot return more than 1,000 results. If you need to retrieve all the content of your index (for backup, SEO purposes or for running a script on it), you should use the browse method instead. This method lets you retrieve objects beyond the 1,000 limit.

https://www.algolia.com/doc/api-reference/api-methods/browse/

**Comment by driesvints** [comment]
Seems to be Algolia specific so this might be a good feature for https://github.com/algolia/scout-extended
