### ISSUE TITLE
shouldBeSearchable vs indexOnly from deprecated package

### ISSUE THREAD

**Issue by ekstro** [laravel/scout#249]
I thought that "shouldBeSearchable()" works similar to "indexOnly (algolia/algoliasearch-laravel)", but returning false doesn’t delete a record if it was indexed earlier. Is such way of behaving intended?

Quick fix (not the prettiest):

```
public function toSearchableArray()
{
    if ($condition === true) {
    	$this->unsearchable();

        return [];
    }

    return $this->toArray();
}
```

**Comment by kfirba** [comment]
@ekstro the `shouldBeSearchable` method simply ensures that no records should get sent to Algolia or any other engine you are using under certain conditions. It does not attempt to sync the model or remove it. It serves as a "gate".

**Comment by arjanwestdorp** [comment]
#264 Adds this sync behaviour where it will make the unsearchable call in case the `shouldBeSearchable()` returns `false`.
