### ISSUE TITLE
using Laravel insert() and inserting many rows at the same time doesnt seem to trigger a insert into Algolia

### ISSUE THREAD

**Issue by kiwo12345** [laravel/scout#259]
I am doing a bulk insert in Laravel like 

```
\App\Example::insert([
    [
        'name' => 'abc',
        'value' => '123',
    ],
    [
        'name' => 'def',
        'value' => '456',
    ],
    // etc...
]);
```

This will do a bulk insert, one query but still inserting many rows at once.

The problem is that when I use `insert()` the rows doesnt get inserted to Algolia. So how can I do a bulk insert to Algolia as well?

I dont want to loop through my rows and do a insert one by once since this will cost extra requests

**Comment by Chrysanthos** [comment]
The only alternative you currently have is using the command [here](https://laravel.com/docs/master/scout#batch-import).

**Comment by kiwo12345** [comment]
@Chrysanthos I solved it by saving the ids inside a transaction like this:

$currentId = MyModel::max('id');
MyModel::insert($data);
$lastId = MyModel::max('id');

MyModel::where('id', '>', $currentId)->where('id', '<=', $lastId)->searchable(); // Here I do a bulk insert
