### ISSUE TITLE
sql error when saving a model

### ISSUE THREAD

**Issue by subdesign** [laravel/scout#261]
Hey,
first of all, the query part is working, I get results using Scout.  
pre story: I use two accessors, to build content from markdown to html
```php
    public function getPreviewConvertedAttribute()
    {
        return (new Parsedown)->text($this->preview);
    }

    public function getBodyConvertedAttribute()
    {
        return (new Parsedown)->text($this->body);
    }
```
I use Laravel as backend for a Vue.js project, and I have to pass transformed data to Vue, so **I can't hide** these two accessor fields.

The error is, updating the Article model with eloquent (`->save()`):  
```
SQLSTATE[42000]: Syntax error or access violation: 1064 index 'articles' does not support INSERT (enabled=1) [REPLACE INTO articles (author_id, title, slug, preview, body, status, enabled, hash, updated_at, created_at, id, preview_converted, body_converted) VALUES (1, 'Some article', 'some-article', 'this is the preview', 'this is the content', '1', 1, '8c1d5a9b8852e3f5bfdde4ed0e98ef72', '2018-01-27 17:27:35', '2018-01-27 17:27:35', 25, '<p>this is the preview</p>', '<p>this is the content</p>')]
```
As I see Scout try to insert the two accessor fields, which aren't exist in DB in real.  

The sphinx config for sql is:
```
sql_query = SELECT id, title, preview as preview_converted, body as body_converted, created_at FROM articles
```
I get any result with Scout/Sphinx only with this query...  
 
How to prevent it to do that, if it makes behind the scenes? Or the message should point to a different error?
Laravel 5.5  
sphinx 2.2.1 (mac)

**Comment by driesvints** [comment]
You can use the `toSearchableArray` to manipulate which keys are sent to your search engine for updating. Try filtering those converted attributes out in there.
