### ISSUE TITLE
Disable auto index

### ISSUE THREAD

**Issue by kiwo12345** [laravel/scout#262]
Is there any way to disable the auto index?

I dont want to call 

```php
App\Order::withoutSyncingToSearch(function () {
    // Perform model actions...
});
```

each time. It would be much easier to just disable it once.

**Comment by edersoares** [comment]
You can to use the `shouldBeSearchable()` method in your model class to disable the auto index like
```php
public function shouldBeSearchable()
{
    return app()->environment('production'); // Or other conditional
}
```
See more [here](https://laravel.com/docs/5.6/scout#indexing) in Conditionally Searchable Model Instances

Or you can set SCOUT_DRIVER to `null` to disable auto index.

**Comment by lighta971** [comment]
In your AppServiceProvider.php

```php
Order::disableSearchSyncing();
```

**Comment by julienbourdeau** [comment]
@edersoares Note that if `shouldBeSearchable` return false, it will dispatch a delete call to Algolia (every time the model is touched).

**Comment by driesvints** [comment]
Try `Order::disableSearchSyncing();` like @lighta971 suggested.

**Comment by altynbek07** [comment]
My solution:
#### Disable Algolia:
in `.env` file:
```env
SCOUT_DRIVER=null
```
in `scout.php` file:
```php
'driver' => env('SCOUT_DRIVER', null),
```
---
#### Enable Algolia:
in `.env` file:
```env
SCOUT_DRIVER=algolia
```
