### ISSUE TITLE
multiple process import command

### ISSUE THREAD

**Issue by mhndev** [laravel/scout#265]
I have large amount of data , I need to be able to import this data not by single process, instead I need
multiple worker to do this job for me.

also I think number of batch index is related to hardware so it should be dynamic.

**Comment by Rkallenkoot** [comment]
Did you try using the `SCOUT_QUEUE=true` setting in environment?

**Comment by driesvints** [comment]
Did you try queuing like @Rkallenkoot suggested?

There's also https://github.com/laravel/scout/issues/275 which can use for inspiration on how to batch things.
