### ISSUE TITLE
toSearchableArray() not used

### ISSUE THREAD

**Issue by ApplicationError** [laravel/scout#266]
This probably isn't a bug, but I thought I'd add it as an issue, just in case it is a bug. 

I've added a toSearchableArray() to my User model, but the additional data is not being passed to Alogolia. Each time I perform the scout:import, all model data is sent to Aloglia. I commented out toSearchableArray() in my User model and also toSearchableArray() in Searchable.php, but import:scout works without errors and sends all model data over. 

Looking at the docs for Laravel Scout (https://laravel.com/docs/5.6/scout#configuration) I was left with the impression that toSearchableArray() in my User model would overwrite the toSearchableArray() in the Searchable.php - so if I comment out both instances, I was expecting an error (but didn't get one).

I'll continue my "searching" and try to make this work.

**Comment by ApplicationError** [comment]
I am confused. When I disable queuing in the config/scout.php...   'queue' => env('SCOUT_QUEUE', false),    everything works, as in, the searchableAs() and toSearchableArray() work as expected. I am not sure what's going on. I'll leave the queue disabled for now.

**Comment by edersoares** [comment]
Do you restarted your queue worker?

**Comment by ApplicationError** [comment]
Hi @edersoares, I have not. I didn't know that's a requirement. Can I periodically restart the queue worker? Hm....

**Comment by edersoares** [comment]
If you modified your code you need restart the queue worker to its reload the source code.

**Comment by nunomaduro** [comment]
Hey @ApplicationError  👋

Thanks for reporting this issue. Just made a small test, and it works in my application. You still have this problem? If yes, can you share the versions of Laravel/Scout/Algolia that you are using? 🧐

**Comment by driesvints** [comment]
Yeah, this seems like a problem with restarting your queues rather than scout. Restart your queues and php-fpm whenever you deploy your code.
