### ISSUE TITLE
Overwriting Delete logic

### ISSUE THREAD

**Issue by aconital** [laravel/scout#267]
My Algolia ObjectId is modified and not equal to primary key of my model. As a result when I call delete on my object Scout doesn't remove it from algolia.  Is there a way to overwrite the delete logic, something similar to toSearchableArray.

**Comment by julienbourdeau** [comment]
Can you share what your ObjectId look like and why you modified it?

**Comment by aconital** [comment]
@julienbourdeau My Laravel model's primary key is id which is an integer but because I needed my frontend to be able to filter on a unique field, I had to change the Algolia ObjectID to that unique field.
Imagine this example:
```
User{
id,
name
email
}

```
```
Algolia User 
{
objectID: email
name
}
```
I didn't want to mark that field as a facet because it has a unique value so I had to change the objectID because Algolia allows you to filter on ObjectID.
