### ISSUE TITLE
Error when performing a batch import

### ISSUE THREAD

**Issue by harrygr** [laravel/scout#27]
When trying to perform a batch import (e.g. `php artisan scout:import "App\Post"`) the following error is thrown

> Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Laravel\Scout\SearchableScope::Laravel\Scout\{closure}() must be an instance of Laravel\Scout\Builder, instance of Illuminate\Database\Eloquent\Builder given in /home/vagrant/samarkand-web/vendor/laravel/scout/src/SearchableScope.php:32

**Comment by JanPetr** [comment]
Update to the latest version, the issue was fixed in https://github.com/laravel/scout/pull/22

**Comment by harrygr** [comment]
I have  172d156 installed (2hrs old at time of writing) and it still gives that error

**Comment by wcjonathan** [comment]
Have you include the use statement for the Searchable trait?

**Comment by harrygr** [comment]
Yes, here is the relevant code:

```php
//...
use Laravel\Scout\Searchable;

class Product extends Model
{
    use Searchable;

//...
```

**Comment by tomschlick** [comment]
Give this a shot now... looks like @talv86 fixed it with his PR

**Comment by harrygr** [comment]
Yes looks like #33 did the trick
