### ISSUE TITLE
Is there anyway to remove an item from the search index without removing it from the local db

### ISSUE THREAD

**Issue by kiwo12345** [laravel/scout#270]
I know that I can remove an item from the search index by:

```
$order = App\Order::find(1);
$order->delete();
```

or
// You may also remove via relationships...
`App\Order::where('price', '>', 100)->unsearchable();`

But I only want to remove it from the search index/Algolia and still keep it in my local DB, is this possible?

**Comment by julienbourdeau** [comment]
This is what `unsearchable` does (in your second snippet.

```php
App\Order::find(1)->unsearchable();
```
