### ISSUE TITLE
When does shouldBeSearchable get triggered?

### ISSUE THREAD

**Issue by kiwo12345** [laravel/scout#271]
Lets say I have a shouldBeSearchable() set like this:

```
public function shouldBeSearchable()
{
    return $this->is_active === 1;
}
```

By default in my app a newly created post gets **is_active** set to **1** so it will be added to my search index.

But if I now update that same post and set **is_active** to **0** does it automatically then get removed from my search index?

**Comment by akkhan20** [comment]
And what was the answer before closing?
