### ISSUE TITLE
compatibility  with ES 6.2.2

### ISSUE THREAD

**Issue by shalinimonad** [laravel/scout#273]
Hi there, i am using "jeskew/amazon-es-php" package for connecting scout with AWS ES instance.
But in ES 6.2.2 , i want to create multiple index and want to import models into different index , how i can do that using scout ,because currently it import data into one index only.

**Comment by julienbourdeau** [comment]
If you override the `searchableAs` method of your model, you'll be able to return the index name of your need.
https://laravel.com/docs/5.6/scout#configuring-model-indexes
Let is know if that worked.

**Comment by shalinimonad** [comment]
Sry my comment was not appropriate,i am using driver "elasticsearch" . By "index" mean elasticsearch index  , not model index .Model indexes configuration allow to modify type(typically each table name) ,not ELASTICSEARCH_INDEX (database name). 

I want to import models into different elasticsearch index.

I got solution ,so closing this
