### ISSUE TITLE
getScoutKey() broken get() and paginate() functions

### ISSUE THREAD

**Issue by bb128b** [laravel/scout#274]
This issue references the merge request from #268.

This is broken somehow. I set the value of getScoutKey to a unique index on my Eloquent Model and the results come back as 0 even though is results.

```
    /**
     * Get the value used to index the model.
     *
     * @return mixed
     */
    public function getScoutKey()
    {
        return $this->name; // This is the unique index (objectID in Algolia).
    }
```

I have 6 results but the data is an empty array.

```
{
    "current_page": 1,
    "data": [],
    "first_page_url": "http://url.test/api/search?query=qui&page=1",
    "from": null,
    "last_page": 1,
    "last_page_url": "http://url.test/api/search?query=qui&page=1",
    "next_page_url": null,
    "path": "http://url.test/api/search",
    "per_page": 15,
    "prev_page_url": null,
    "to": null,
    "total": 6
}
```

I believe it is around this code that needs refactoring.

src/Engines/AlgoliaEngine.php - Line 175

```
        $models = $builder->whereIn(
            $model->getQualifiedKeyName(),
            collect($results['hits'])->pluck('objectID')->values()->all()
        )->get()->keyBy($model->getKeyName());
```

I would do it myself but I do not know Scout well enough to make a fix. If nobody attempts it I will try on Sunday an issue a pull request.

**Comment by julienbourdeau** [comment]
How do you search in the index?

**Comment by driesvints** [comment]
Should be fixed in above PR ^
