### ISSUE TITLE
Algolia: Record size is limited to 10kb

### ISSUE THREAD

**Issue by sebastiansulinski** [laravel/scout#275]
When importing large document I'm getting 

> AlgoliaSearch\AlgoliaException: Record at the position 0 objectID=107 is too big size=12300 bytes. Contact us if you need an extended quota

Algolia suggests chunking long document https://www.algolia.com/doc/guides/indexing/structuring-your-data/?language=php#indexing-long-documents

Not sure if other services also have similar cap - if so, perhaps worth implementing split of the larger records?

**Comment by ligne13** [comment]
Is there a way to do this with Scout ?

**Comment by sebastiansulinski** [comment]
Not at the moment, but I've forked the repository and am working on the PR for it.

**Comment by ligne13** [comment]
Awesome !

**Comment by julienbourdeau** [comment]
Great, I'll be happy to review. Ideally, keep in mind that the limit depends on your plan (10KB for Community but 20KB for Essential and custom for Enterprise).

If it's not merged in the core, we could have a scout extension with this, managing settings and other things for example.

**Comment by sebastiansulinski** [comment]
What I was planning to do is to tackle the multiple arrays sent to scout and allow user to decide how they want to split their content i.e by sending:

```php
public function toSearchableArray()
{
    return [
        [
            'id' => 1,
            'name' => 'Name 1 content',
            'body' => 'Chunk 1 content',
        ],
        [
            'id' => 1,
            'name' => 'Name 2 content',
            'body' => 'Chunk 2 content',
        ],
        [
            'id' => 1,
            'name' => 'Name 3 content',
            'body' => 'Chunk 3 content',
        ]
    ];
}
```

This way user can control how they want to split the content rather than doing it directly from within the `AlgoliaEngine`. This would also remove any need for additional configuration etc. I will add an example of how content can be split from within the `toSearchableArray`.

Unless you guys think automating it from within the `AlgoliaEngine` is a better approach?

**Comment by ligne13** [comment]
This sounds good to me ! What options for chunking text do you think of ? (splitting by sentences ? by paragraphs ?).

**Comment by sebastiansulinski** [comment]
I would probably say `words`, but would have to make sure that the character limit does not exceed whatever 10kb can take in. Once I have a PR ready, I'll update this ticket.

**Comment by julienbourdeau** [comment]
@sebastiansulinski This would be ideal but I'm not sure how you can detect if `toSearchableArray()` returned an array of records (array or array) or only one record (array of stuff, potentially array of array).

**Comment by sebastiansulinski** [comment]
@julienbourdeau - here's my initial attempt https://github.com/sebastiansulinski/scout/blob/4.0/src/Engines/AlgoliaEngine.php - you'll see `addToObjectsCollection` method that first checks whether the first / current item returned from the `toSearchableArray` is of the type `array` - there's still lots of things that I need to change etc. as I'm reading through algolia's docs - one that is probably the biggest issue at the moment is when on update lots of content gets removed, ultimately generating less chunks - what happens with the old ones etc., but I'm slowly wrapping an idea on hot to tackle it. Any comments / suggestions - let me know.

**Comment by driesvints** [comment]
Can see how this could be useful. Feel free to send in a PR.

**Comment by marcosdipaolo** [comment]
still no idea how to split a large blog post in Laravel, so it can be indexed. 
A 101 guide somewhere?

**Comment by nunomaduro** [comment]
@marcosdipaolo I am going to support that on [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended). Please `watch` the repository an wait until a release.

**Comment by pieterclaerhout** [comment]
Did anyone by any chance do something similar for Meilisearch? Apparently, for performance reasons, they also expect to split up large records into smaller pieces… (they suggested 10KB - 20KB per record).
