### ISSUE TITLE
Simple delete() has no effect

### ISSUE THREAD

**Issue by MrMooky** [laravel/scout#276]
I've been trying to understand this for some time now, but cannot seem to find a fix. Adding and updating a model to Algolia works just fine. But I cannot remove/delete the user from the Algolia index.

Example: `ObjectID = 100`, which is the users id. When calling `User::find(100)->delete();` the user gets deleted from my app, but remains in the Algolia index. As far as I can see from the docs, this is how it should work, right?

Even calling `User::find($userid)->unsearchable();` before deleting the user has no effect on the index.

**Comment by MrMooky** [comment]
I tried a few more things now but nothing seemed to work. My User model has this primary key set:

`protected $primaryKey = 'id';`

In my Controller I delete a user like this:

`User::find($userid)->delete();`

The user gets deleted from the DB, but remains in the Algolia index. It can't be that I am the only one having this issue. ._.

**Comment by nunomaduro** [comment]
Hey @MrMooky 👋

Thanks for reporting this issue. Just made a small test, and it works in my application. You still have this problem? If yes, can you share the versions of Laravel/Scout/Algolia that you are using? 🧐

**Comment by MrMooky** [comment]
Hi @nunomaduro.

Yes, I still have this problem, unfortunately.

Laravel 5.4.36
Scout ^4.0
Algolia ^1.25

**Comment by nunomaduro** [comment]
@MrMooky A good start would be upgrade scout to `^5.0`

**Comment by MrMooky** [comment]
<img width="442" alt="screenshot 2018-09-15 at 12 44 04" src="https://user-images.githubusercontent.com/3603346/45585467-0d99b980-b8e5-11e8-883f-208ef516195d.png">

Done. Unfortunately, when calling `User::find(Auth::user()->id)->delete();` the user still appears in the Algolia index. :/

**Comment by MrMooky** [comment]
But if that's the case, I should have problems updating the index when a user updates the profile. This works fine. Only deleting is ignored.

**Comment by nunomaduro** [comment]
Have you tried upgrade your Laravel version? Laravel 5.4 is no longer maintained.

**Comment by MrMooky** [comment]
Just updated to 5.6.x and had high hopes it would fix the issue, but sadly it still won't delete the user from the index. ._.

**Comment by nunomaduro** [comment]
Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/)
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)
- Algolia Discourse (https://discourse.algolia.com)

Thanks in advance.

**Comment by MrMooky** [comment]
I don't consider this a general application issue since the rest is working as _advertised_ out of the box. But I'll try my luck over at StackOverflow. Thanks, though.

**Comment by goyote** [comment]
@MrMooky did you resolve this issue? I'm experiencing same.

**Comment by goyote** [comment]
@MrMooky You can use this meanwhile:

```
use AlgoliaSearch\Client;

$client        new Client(config('scout.algolia.id'), config('scout.algolia.secret'));
$versionIndex = $client->initIndex(config('scout.prefix').'versions');

$versionIndex->deleteObject($version->id);
```

**Comment by MrMooky** [comment]
@goyote Thank you sooo much! 🎉

**Comment by MatanYed** [comment]
I got this issue also. Anything new?

**Comment by nunomaduro** [comment]
@MatanYed What version of Laravel/Scout are you using?

**Comment by MatanYed** [comment]
@nunomaduro Laravel 5.7.7, my Scout version was 4.0.4 and I updated it to 6.0.0 just to check, in both versions it's not working

**Comment by MatanYed** [comment]
my scout config is `soft_delete => false`

**Comment by nunomaduro** [comment]
@MatanYed Show me the code you use to delete records from your database and Algolia.

**Comment by MatanYed** [comment]
@nunomaduro I'm sorry, after the update to scout 6.0.0, I had to clear cache and import all the models, now it works fine. Thanks for super-fast response!

**Comment by MrMooky** [comment]
I just noticed that for some very strange reason, the direct API call just stopped working. Not sure why or even when. :/ So I'm back where I started and spend the entire morning trying to figure this out, again.

Laravel: 5.7
laravel/scout: 7.1.2 (just updated, did not fix it)
algolia/algoliasearch-client-php: 2.2.4 (just updated, did not fix it)

I can see in the Algolia logs, that the user is being updated instead of removed with the action `"action": "updateObject"`

Here's the weird part: I just put the following into a different action and it worked right away with this action in the logs: `"action": "deleteObject"`

```
$user = Auth::user();
$user->unsearchable();
```

I tried changing positions in the code and put it almost at the very bottom of my delete function for accounts, but the model keeps being updated.

**Comment by nunomaduro** [comment]
Monday I will check this with my team, 🤙🏻

**Comment by TomKlotzPro** [comment]
@MrMooky,
`logout()` fires update event to Algolia Index. Since the user is still searchable, it's normal that it should be indexed.

If you want to remove from your index a user who logs out you must perform the `unsearchable()`, and the function `shouldBeSearchable()` should return false for that specific user so the user don’t get added again.

**Comment by nunomaduro** [comment]
Thanks, @TomKlotzPro for the investigation. @MrMooky don't hesitate to re-open the issue if Tom's solution doesn't work for you.
