### ISSUE TITLE
shouldBeSearchable() seems to not be working

### ISSUE THREAD

**Issue by Lanatel** [laravel/scout#280]
Hello! 
I am using ElasticSearch in my project and I want to index conditionally, so I have the following method in my model class

```
public function shouldBeSearchable()
{
      return $this->paid;
}
```

When it return `true` everything works as expected, but if result is `false` I get this error 

```json
{
	"_index": "question",
	"_type": "questions",
	"_id": "72",
	"_version": 1,
	"result": "not_found",
	"_shards": {
		"total": 2,
		"successful": 1,
		"failed": 0
	},
	"_seq_no": 5,
	"_primary_term": 1
}
```

And that's obvious because I found method, which handles the saved event for the model. Here it is

```
public function saved($model)
{
        if (static::syncingDisabledFor($model)) {
            return;
        }

        if (! $model->shouldBeSearchable()) {
            $model->unsearchable();
            return;
        }

        $model->searchable();
    }
```

So, here it call   `unsearchable()` method for model which doesnt exist in the search index and maybe because of that I have this not found error?

**Comment by driesvints** [comment]
`unsearchable` will call the delete method of your engine. You'll first need to check if the model exists in the delete method before attempting to delete it.
