### ISSUE TITLE
Add support for query Scopes

### ISSUE THREAD

**Issue by ARKKYN** [laravel/scout#284]
$this->customers->search($input['query'])->AmountReceivables()->withCount(['vehicles','totalInvoices','invoices'])->paginate($limit);

throws error On using  scopes

**Comment by driesvints** [comment]
Should be fixed by now on 5.0, let me know if you still having troubles with this.

**Comment by ARKKYN** [comment]
@driesvints  thank you

**Comment by mrmonat** [comment]
This doesn't seem to work anymore as ```Model::search($query)``` returns an Instance of `\Laravel\Scout\Builder` instead of `\Illuminate\Database\Eloquent\Builder` ?

**Comment by sebastiaanluca** [comment]
@driesvints Can't get it to work as in the example above, but is the following the preferred way of adding query parameters that will be applied to the search results?

```php
return Category::search($query)
    ->query(function (Builder $builder) {
        $builder->enabled();
    })
    ->take(5)
    ->get();
```

**Comment by driesvints** [comment]
@sebastiaanluca hmm, can't find an example in the docs. I think so yeah but unsure. Where does the `enabled` function come from? Are you using the latest 7.x release?

**Comment by sebastiaanluca** [comment]
`enabled()` is just the model scope. Can be an eager load, scope, where, etc, but still have to write tests to assert this works. Using `laravel/scout` v7.1.2 in combination with `teamtnt/laravel-scout-tntsearch-driver` v7.1.0.

Applying a scope, limit, etc after the `search()` call throws an exception it can't find the method on the builder. Adding it before complains about `search()` not being a method on the class.

**Comment by driesvints** [comment]
@sebastiaanluca we don't `teamtnt/laravel-scout-tntsearch-driver`. Maybe this is an issue with this driver? Does it works with the Algolia driver?

**Comment by sebastiaanluca** [comment]
Since it acts on Scout interfaces and classes I suspect it's unrelated to the used driver, but don't have a setup to test with the Algolia driver so can't compare unfortunately.

Tbh, I think it's just some incomplete or faulty documentation. Checking the Scout builder class, there's no magic method forwarding to the underlying query builder class, only a `query` method that `Set the callback that should have an opportunity to modify the database query.` You shouldn't be able to directly call scopes and relations after calling `search`.

**Comment by MartinMorlog** [comment]
> @driesvints Can't get it to work as in the example above, but is the following the preferred way of adding query parameters that will be applied to the search results?
> 
> ```
> return Category::search($query)
>     ->query(function (Builder $builder) {
>         $builder->enabled();
>     })
>     ->take(5)
>     ->get();
> ```

This worked for Algolia, for search using MySql got it to work like:

```php
return Category::search($query, static function (Builder $builder) {
    return $builder->enabled();
});
