### ISSUE TITLE
Models using `Searchable` are pushed even with no changes

### ISSUE THREAD

**Issue by msiemens** [laravel/scout#285]
Seems to be caused by #252. The `saved` event is triggered even when no changes have been made to the model. There, `$model->searchable()` is called unconditionally, regardless of whether the model is actually dirty or not. This causes any model to be imported to the search index whenever it is saved – with and without changes.

Compared to that, the `updated` event – which was used in the previous verison – is actually only triggered, when the model is dirty, see https://github.com/laravel/framework/blob/17c4c0faaecb5293febada7930a459a9efd6979b/src/Illuminate/Database/Eloquent/Model.php#L626-L637.

Observed in a Laravel project of mine, I can create a reproduction repository, if wanted.

**Comment by msiemens** [comment]
I can also provide a pull request if wanted

**Comment by Catzilla** [comment]
I created a package that solves this issue.
Check it out: [scout-noindex](https://github.com/Catzilla/scout-noindex)

**Comment by driesvints** [comment]
Because of the reasons @julienbourdeau detailed in the closed PR, I believe we won't be changing this anytime soon. You can use a 3rd party implementation like the one from @Catzilla if you really want this behavior.

**Comment by tomlankhorst** [comment]
Or check `isDirty()` yourself, before `save()`. 

```php 
$book->isDirty() && $book->save();
```

if you know for sure that you want to alter the model when _dirty_ and performance is of importance, then you might not want to run `save` at all, when the model isn't _dirty_.
