### ISSUE TITLE
Config custom queue results in always queue

### ISSUE THREAD

**Issue by thoresuenert** [laravel/scout#289]
It is possible to configure a specific queue and connection within `config/scout.php`:
```php
//config/scout.php
return [
  'queue' => [
     'queue' => 'custom',
     'connection' => 'custom',
  ]
];
```
Which is used by https://github.com/laravel/scout/blob/f1b5d65a7d4a70bafaba7ec996176e95341c44ec/src/Searchable.php#L253-L256 and https://github.com/laravel/scout/blob/f1b5d65a7d4a70bafaba7ec996176e95341c44ec/src/Searchable.php#L263-L266.

The Problem with that is: we can no longer disable queuing via config, because of following check for queuing: https://github.com/laravel/scout/blob/f1b5d65a7d4a70bafaba7ec996176e95341c44ec/src/Searchable.php#L63-L65 
when `config('scout.queue')` is an array it is always `true`.

It feels like a hidden feature and i dont know how to solve it.

Idea:
```php
//config/scout.php
return [
  'queue' => [
    'enable' => true/false,
     'queue' => 'custom',
     'connection' => 'custom',
  ]
];
```

My Use-Case is tntsearch driver in combination with horizon:
Without a second supervisor and a custom queue the sqlite database used by tntsearch throws blocked erros because mulitple processes are writing to sqlite file.

**Comment by driesvints** [comment]
I don't really understand why you would setup a custom queue but at the same time disable it. It's either the one or the other the way I see it. Feel free to provide more info if you still feel this should be changed.

**Comment by thoresuenert** [comment]
@driesvints 
my use case is really easy:

| env | queues |
| --- | ---- |
| local/development | no |
| preview app (each PR) |  no |
| production  | yes |
| staging | yes |

### Reason why i need a custom queue
I use the tntsearch driver which is based on sqlite.
Without a custom queue i face file/databse lock issues which leads to async data.
The workaround is to use a custom queue for all search related stuff to limit the workers to 1.

**Comment by driesvints** [comment]
Okay, I see what you mean. I'll re-open this and try to send something in for this.

**Comment by driesvints** [comment]
When looking at it further I realized you can achieve this behavior by using environment variables for the queue name and connection.

```
    'queue' => [
        'queue' => env('SCOUT_QUEUE_NAME'),
        'connection' => env('SCOUT_QUEUE_CONNECTION'),
    ],
```

If you set `SCOUT_QUEUE_NAME` & `SCOUT_QUEUE_CONNECTION` as empty then you can achieve the behavior you want. Can you try this out?

**Comment by williamdes** [comment]
@driesvints Works perfectly !
