### ISSUE TITLE
Update single value for record

### ISSUE THREAD

**Issue by MrMooky** [laravel/scout#291]
I am having an issue with updating a record, as described [here](https://stackoverflow.com/questions/51230363/tosearchablearray-in-laravel-scout-overwrites-owner).

Since it appears nobody can help me there, I'd like to know if it is possible to update a single value in a record instead of the whole record.

**Comment by Jimmea** [comment]
U can write a function in model contains class searchable. And then u call to method searchable

**Comment by driesvints** [comment]
Algolia supports partial updates but Scout doesn't support it at the moment. You can however use the Algolia library to do this.

```php
$index = $this->algolia->initIndex($models->first()->searchableAs());

$index->partialUpdateObject(...do stuff);
```

Check out the docs here: https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/
