### ISSUE TITLE
Undefined property: Laravel\Scout\Builder::$queryCallback in ...vendor/laravel/scout/src/Searchable.php on line 178

### ISSUE THREAD

**Issue by joshuajazleung** [laravel/scout#292]
This is the only query I use in my controller:

`return Thread::search($searchTerm)->paginate(25);`

I tried 
`return Thread::search($searchTerm)->get();`
`return Thread::search($searchTerm)->first();`

still get the same error. Is this a bug?

**Comment by cerkauskas** [comment]
https://github.com/laravel/scout/pull/293 I made pull request

**Comment by gdsrmygdsrjr** [comment]
#298

**Comment by driesvints** [comment]
Should be fixed now. Thanks guys 👍
