### ISSUE TITLE
The '?query=' parameter is hardcoded in Scout/Builder->paginate() 

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/scout#299]
```
    public function paginate($perPage = null, $pageName = 'page', $page = null)
    {
        $engine = $this->engine();

        $page = $page ?: Paginator::resolveCurrentPage($pageName);

        $perPage = $perPage ?: $this->model->getPerPage();

        $results = Collection::make($engine->map(
            $rawResults = $engine->paginate($this, $perPage, $page), $this->model
        ));

        $paginator = (new LengthAwarePaginator($results, $engine->getTotalCount($rawResults), $perPage, $page, [
            'path' => Paginator::resolveCurrentPath(),
            'pageName' => $pageName,
        ]));

        return $paginator->appends('query', $this->query);
    }
```

https://github.com/laravel/scout/blob/5.0/src/Builder.php#L279

Currently, as you can see on the last line, the paginator allways use the hardcoded parameter "query" as parameter. This is not documented and does not permits localization nor customization. 
it should be fixed.

one posible solution is to have a config option.

**Comment by julienbourdeau** [comment]
It could also be renamed `q`. It wouldn't be customizable but localization wouldn't matter as much.

**Comment by driesvints** [comment]
Closing this because it's a duplicate of #58. Let's continue discussion there.
