### ISSUE TITLE
scout:import and search not working

### ISSUE THREAD

**Issue by newtekDev** [laravel/scout#300]
Laravel 5.5
Using Algolia

When I use the command `scout:import "App\{Class}"` nothing gets imported even though I get the proper response message. 

```
Imported [App\{Class}] models up to ID: 1843
Imported [App\{Class}] models up to ID: 2682
Imported [App\{Class}] models up to ID: 2717
```
But when I go to the Algolia dashboard I saw no models imported.

I know I'm connected to Algolia because the index was added and I see my queries happening in the dashboard. But when I look at the query I see:

```
{
  "requests": [
    {
      "indexName": "projects",
      "params": "query=&..."
    }
  ]
}
```

So it looks like the query is empty.

I dd'd the `Class::search()` method and the response showed the correct model, correct query, but the index property was null.

One point to make is I used the native Scout first, without Algolia, I don't know if that would cause issues. I was having similar issues there as well.

Not sure how to debug further.

I was able to use the Algolia composer plugin to get results and import models, but then its all manual.

```
$client = new \AlgoliaSearch\Client(config('scout.algolia.id'), config('scout.algolia.secret'));

$index = $client->initIndex('{index}');

return response()->json($index->search($request->search));
```

**Comment by newtekDev** [comment]
followed different things here to finally get it to work: https://github.com/laravel/scout/issues/175

- set queue to false
- deleted index in algolia dashboard
- flushed import
- did import
- got results

**Comment by julienbourdeau** [comment]
Usually, this happens when the NullEngine is used instead of Algolia.

I'd recommend `php artisan config:clear` in case you have cached your configuration (which you shouldn't do in dev env).

**Comment by DmitryShmanko** [comment]
> Usually, this happens when the NullEngine is used instead of Algolia.
> 
> I'd recommend `php artisan config:clear` in case you have cached your configuration (which you shouldn't do in dev env).

you've saved me my brain :D
