### ISSUE TITLE
How to define the queue for Scout?

### ISSUE THREAD

**Issue by elfeffe** [laravel/scout#302]
https://github.com/laravel/scout/blob/9f06b9c4d77879d53cf1680740b7f8bf19f78279/src/Searchable.php#L261
This line thinks scout.queue is an array, but it's boolean.
So scout.queue.connection doesn't exist

**Comment by Onind** [comment]
you have to edit your config queue value to an array. This way it will still use the queue and you can customize the values.

`	'queue' => [
		'queue'      => 'search',
		'connection' => 'sqs'
	]`

**Comment by nunomaduro** [comment]
@elfeffe Have you tried @Onind's solution?

**Comment by elfeffe** [comment]
@nunomaduro Yes!
I didn't see it
