### ISSUE TITLE
Multiple Where clause with same column name does not work

### ISSUE THREAD

**Issue by varuog** [laravel/scout#315]
Multiple Where clause with same column name dont produce 'AND' concatenated query string and only take last where clause. I am using https://github.com/YABhq/laravel-scout-mysql-driver with scout. 

`Model::search()->where('foo', 'bar)->where('foo' => 'baf');`
**Produce in DB log** 
> WHERE foo='baf' AND MATACH..

Inspecting builder code in **scout/src/Builder.php**, it looks like it overwrites field value.

```
 /**
     * Add a constraint to the search query.
     *
     * @param  string  $field
     * @param  mixed  $value
     * @return $this
     */
    public function where($field, $value)
    {
        $this->wheres[$field] = $value;
        return $this;
    }
```

what would be the workaround? also it would be nice to see whereIn clauses for search

**Comment by driesvints** [comment]
I think it's best that the package you're mentioning would overwrite this functionality or provide a custom method for this behavior. The builder is macroable so you can extend it this way: https://laravel.com/docs/5.7/scout#builder-macros
