### ISSUE TITLE
queueMakeSearchable() for collections does not check shouldBeSearchable()

### ISSUE THREAD

**Issue by chamby** [laravel/scout#320]
Models that should not be indexed are being indexed when calling `$collection->searchable()`. This is different behavior than ~~`$model->searchable()`~~ or `$query->searchable()`.

**Comment by driesvints** [comment]
Are you sure? The `$model->searchable()` call just uses the collection object behind the scenes.

**Comment by chamby** [comment]
Models and queries use the `SearchableScope` macro, not the collection `Searchable` trait.

**Comment by chamby** [comment]
I'll try to find some time in the next couple of days.

**Comment by chamby** [comment]
Apparently I misunderstood the use cases for searchable() and unsearchable(). What I was really looking for was what the model observer does. The model observer, upon save, does both depending on the result of `shouldBeSearchable()`.

```php
    public function saved($model)
    {
        if (static::syncingDisabledFor($model)) {
            return;
        }
        if (! $model->shouldBeSearchable()) {
            $model->unsearchable();
            return;
        }
        $model->searchable();
    }
```

I have a use case where I have a collection or query of models where I want to recheck their `shouldBeSearchable()` value and have the appropriate action taken. I can create my own snippet of code for this of course.

**Comment by chamby** [comment]
```
// shouldBeSearchable() not used
$model->searchable();
$collection->searchable();

// shouldBeSearchable() is used
$model->relationship()->searchable();
$query->searchable();
```

**Comment by chamby** [comment]
I believe this is really a documentation clarification issue. I am making assumptions about the intent of the various flavors of `searchable()`.

Calls against the model itself or a collection of models is intended to force the model to be searchable.
Calls against a relationship or query are intended as a batch processing step and therefore the filtering makes sense.

Assuming that this is the correct intention of the code, I have opened an issue with the docs.
https://github.com/laravel/docs/issues/4813

**Comment by driesvints** [comment]
I still believe we're missing something here and that this is a potential bug. So I'd wait with updating the docs until we get to the bottom of this.

@nunomaduro would you have time to check in on this?

**Comment by driesvints** [comment]
Hey @chamby & @nunomaduro. I did some research against this and came to the same conclusion. You'll notice that there's two places where the `shouldBeSearchable` method is used: in the `SearchableScope` class which is applied to all model queries (as you hinted above) and in the `ModelObserver` class for the `saved` event. Here it'll also remove the model from the index if it's not suppose to be searchable. It's indeed the case that calls to `searchable` on a model or collection "force" a model to be searchable, regardless of the result of `shouldBeSearchable`. 

You're right that this should be clarified in the docs. I'll try to send in an update.
