### ISSUE TITLE
Search in multiple indices in single API call 

### ISSUE THREAD

**Issue by dexbytesmanish** [laravel/scout#327]
How can I search in multiple indices in single API call using multiple queries pushed in single client request as mentioned here ? : https://stackoverflow.com/questions/49846344/algolia-searching-multiple-indices-in-laravel

and also deal with pagination ?
How can I access Algolia client via Scout and create queries with pagination and push to search call ?

I am using Laravel 5..4

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
