### ISSUE TITLE
Class 'AlgoliaSearch\Version' not found

### ISSUE THREAD

**Issue by PieterjanDeClippel** [laravel/scout#328]
I installed Scout using the manual: https://laravel.com/docs/5.4/scout

Installed versions:
- Scout: ^6.1
- Laravel: 5.5.*
- algoliasearch-client-php: ^2.0

In the file **/vendor/laravel/scout/src/EngineManager.php** there's a reference to **AlgoliaSearch\Version**
This class simply doesn't exist in **/vendor/algolia/algoliasearch-client-php/src/** neither does it exist in the GitHub repository @ https://github.com/algolia/algoliasearch-client-php

Edit:
Everything's installed through composer on Linux (Debian Stretch).
When I run php artisan scout:import "App\Entities\{Collection}/{Model}" artisan throws the error:

```
In EngineManager.php line 31:
Class 'AlgoliaSearch\Version' not found
```

Is this an issue or can I resolve this myself?

**Comment by nunomaduro** [comment]
Thanks for reporting this issue @PieterjanDeClippel. You are checking the documentation of a version of Laravel that's **no longer supported**.

Laravel Scout is not **yet** compatible with `algoliasearch-client-php: ^2.0`. Please update your `composer.json` file to require the version `algoliasearch-client-php: ^1.27` of Algolia API Client.

**Comment by PieterjanDeClippel** [comment]
So either update to a later version of Laravel, or use algolia-search-1.27. I'll try.
Thanks

**Comment by adelsedighi** [comment]
with laravel 5.7 installed I used the following:
composer require algolia/algoliasearch-client-php:^1.27

**Comment by nunomaduro** [comment]
@adelsedighi And all works as expected?

**Comment by ehben83** [comment]
Hi,
when trying to use : \AlgoliaSearch\Client::generateSecuredApiKey, the class is not found.
Is there an alternative to this function with the new algolia search client ?

**Comment by nunomaduro** [comment]
@ehben83 Please try: `Algolia\AlgoliaSearch\Client::generateSecuredApiKey`.

**Comment by ehben83** [comment]
@nunomaduro thanks - I found it finally, the correct is : `Algolia\AlgoliaSearch\SearchClient::generateSecuredApiKey`
