### ISSUE TITLE
queueRemoveFromSearch() should optionally use a queue

### ISSUE THREAD

**Issue by chamby** [laravel/scout#331]
Engine delete operations, much like update operations, invoke the network and add latency. I would expect `Searchable::queueRemoveFromSearch()` to optionally use a queue just like `Searchable::queueMakeSearchable()` does. It even has queue in the name.

A new Job called `MakeUnsearchable` would also need to be created.

**Comment by nunomaduro** [comment]
I kind of agree with you on this one. Possible code for a Pull Request:

```php
    /**
     * Dispatch the job to make the given models unsearchable.
     *
     * @param  \Illuminate\Database\Eloquent\Collection  $models
     * @return void
     */
    public function queueRemoveFromSearch($models)
    {
        if ($models->isEmpty()) {
            return;
        }

        if (! config('scout.queue')) {
            return $models->first()->searchableUsing()->delete($models);
        }

        dispatch((new RemoveFromSearch($models))
                ->onQueue($models->first()->syncWithSearchUsingQueue())
                ->onConnection($models->first()->syncWithSearchUsing()));
    }
```

@driesvints What do you think about this?

**Comment by driesvints** [comment]
@nunomaduro looks good.

**Comment by nunomaduro** [comment]
Thanks @driesvints. I gonna work on a Pull Request on the next couple days.

**Comment by michaelnguyen547** [comment]
I just found out today that unsearchable() does not use queue. This PR will fix my issue. Thanks

**Comment by mvdnbrk** [comment]
I am trying to implement this with the code suggested by @nunomaduro.

We will dispatch a job `RemoveFromSearch` passing `$models` which is an instance of  `\Illuminate\Database\Eloquent\Collection`, but by the time the job will be executed the models are already deleted from the database.

Any suggestions how to get around this?

**Comment by jshayes** [comment]
I think that it why queueing deletes was initially removed in this commit https://github.com/laravel/scout/commit/f46b2b8a343162cf227afeb2dcd3709cb4bc626b

**Comment by chamby** [comment]
Yes. This limitation makes sense. It might be possible to obtain the relevant keys for deletion using `$model->getScoutKey()` and queue the RemoveFromSearch Job with that data instead of attempting to de-serialize the model itself in the Job. The Scout keys are all that is actually needed issue a deletion request.

**Comment by nathanblogs** [comment]
Any update on this, It was really confusing looking at the code to find out it doesn't actually queue.

**Comment by jasonlfunk** [comment]
This bit me today. I'm using the TNTSearch driver and have a very large search index. Even though I have a dedicated scout queue, this method is being run in sync has causing 4-5s delays in my code. This really ought to be given a higher priority.

**Comment by driesvints** [comment]
Anyone's free to send in a pr for this enhancement.

**Comment by matt-allan** [comment]
I have this working [on a branch](https://github.com/matt-allan/scout/tree/queue-deletes) but it's a bit of a hack.

It only works if the scout driver only accesses `$model->getScoutKey`; any other attributes will be null. This works fine with the Algolia driver. The Elasticsearch driver I'm personally using accesses other model attributes to determine the document type so it wouldn't work.

Given these limitations I'm not sure if I should open a PR. Maybe it should be optional?

**Comment by driesvints** [comment]
@matt-allan I think it's fair to pursue a solution for only the Algolia driver since that's the only one we're supporting natively in the library atm. But if there would be a generic solution to this we can definitely improve it further later on so other third party libraries can benefit as well.

**Comment by chamby** [comment]
@matt-allan I just wanted to ping you about your branch. I think you should submit a PR for the Algolia support. It seems like you have enough buy-in.

**Comment by matt-allan** [comment]
Thanks @chamby and @driesvints, I'll see if I can make some time to get the PR ready next week.

**Comment by driesvints** [comment]
@matt-allan I've tackled the remaining issues. Feel free to send that PR for this one if you like! :)

**Comment by fernandocoronatomf** [comment]
Hey guys, any idea about when this will be released?
I think this definitely should run in a queue when the scout driver is set to true.

**Comment by driesvints** [comment]
@fernandocoronatomf please don't post "when will this be released" comments. Those aren't helpful. Instead, feel free to help out by sending in a PR.

**Comment by driesvints** [comment]
@uyson please send in a PR if you want this to move forward.

**Comment by uyson** [comment]
yes, I tring to do . but I need to learn phpunit, and mockry to write a test

**Comment by uyson** [comment]
我看了代码， 原来的基础场不好改， 搜两年了我很郁闷官方也没有修改的想法？

**Comment by driesvints** [comment]
This will finally land in today's Scout release thanks to @stevebauman 👏
