### ISSUE TITLE
toSearchAbleArray not working

### ISSUE THREAD

**Issue by yongkylie** [laravel/scout#335]
I am trying to add custom data or removing unnecessary data such as `created_at` by running `search()` method. After several attempts, I still can't make it work.

Here is my model:
```
use Laravel\Scout\Searchable;
class MyModel extends Model {
    use Searchable;    
    ...

    public function toSearchableArray() {
        $array = $this->toArray();
        unset($array['created_at']);
        unset($array['updated_at']);

        return $array;
    }
}
```

The result still returning the same untouched data indexed in Algolia. I tried to add `$array['custom'] = 'custom_value'` to `$array` and it also doesn't work.

I tried to change the toSearchableArray() method to return an empty array immediately, but it still returns the data indexed in Algolia. Is it a bug? Or am I doing something wrong?

My `laravel/scout version` is `^6.1` and `algolia/algoliasearch-client-php` version is `^1.27`.

Any help would be appreciated, thanks!

**Comment by nunomaduro** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
