### ISSUE TITLE
Algolia search with callback and paginate

### ISSUE THREAD

**Issue by m1kfb** [laravel/scout#336]
`$lat = floatval($latLong->latitude);
        $lng = floatval($latLong->longitude);
        $results = Company::search('', function ($algolia, $query, $options) use ($lat, $lng, $radius) {
            $location =  [
                'aroundLatLng' => $lat.','.$lng,
                'aroundRadius' => $radius,
            ];
            $options = array_merge($options, $location);
            return $algolia->search($query, $options);
        })->paginate(12);`

I'm having an issue here with the paginate method. On the subsequent pages, I don't get any results as there is nothing in the query var. I have tried adding the postcode that I get geospatial from but it affects the results. Is there a way of passing the query to the paginate but not algolia?

**Comment by nunomaduro** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by m1kfb** [comment]
It was asked as a question but it is functionality missing that should be there in reality.

**Comment by nunomaduro** [comment]
I will test this later, and re-open the issue if there is a bug or a missing functionality. 👍

**Comment by nunomaduro** [comment]
Just made a quick test locally, and everything works as expected.

Let's find out your problem together, some questions:

What is the name of the query parameter you use for searching?

**Comment by m1kfb** [comment]
So I think the problem may lie in how I’m doing. So the user passes their postcode I convert it to lat long and do the callback with a blank query to return all records around them, when I click on page 2 say because the query is blank it doesn’t get the second page of results.
