### ISSUE TITLE
Bug release 6.1.2

### ISSUE THREAD

**Issue by aetbaev** [laravel/scout#337]
Builder::paginate Line 269

 * @return \Illuminate\Database\Eloquent\Collection
AlgoliaEngine::map

**Comment by nunomaduro** [comment]
Hey @aetbaev, I would like to help you. Can you detail your issue?

**Comment by driesvints** [comment]
I'll need more info and/or code to debug this further. Please post relevant code like models, jobs, commands, notifications, events, listeners, controller methods, routes, etc. You may use https://paste.laravel.io to post larger snippets or just reply with shorter code snippets. Thanks!

**Comment by aetbaev** [comment]
Argument 1 passed to Illuminate\Database\Eloquent\Model::newCollection() must be of the type array, object given, called in /var/www/vendor/laravel/scout/src/Builder.php on line 270

**Comment by mattdfloyd** [comment]
The method signature on `Collection::make` with `$model->newCollection` are different and #334 is causing a regression. `$model->newCollection` requires an array of models while `Collection::make` allowed a mixed parameter.

**Comment by driesvints** [comment]
Just released v6.1.3 with a regression fix
