### ISSUE TITLE
usesSoftDelete trait being applied despite being set as false in config

### ISSUE THREAD

**Issue by 06chaynes** [laravel/scout#338]
I am getting an error on a model regarding the trait method 'usesSoftDelete' failing to apply. I have 'soft_delete' set as false in the scout.php config file, so I wasn't expecting for the trait to be applied at all. Is this behaviour to be expected?

scout v6.1.3

**Comment by nunomaduro** [comment]
Hey @06chaynes. 

Can you detail your problem with a **real** use case? What is the behavior that is not working as expected?

**Comment by 06chaynes** [comment]
When I apply scout's Searchable trait to my model that does not implement soft deletes, it attempts to apply the usesSoftDeletes trait anyways. This is causing a conflict with another trait the model is inheriting. I thought that setting 'soft_delete' to false in the scout config would stop it from applying the usesSoftDelete trait on the model.

**Comment by nunomaduro** [comment]
No problem. I am here to help you. Two questions:

1. What do you mean by `...applying the usesSoftDelete trait on the model.`? You are getting soft deleted models on your index?
2. What do you mean by `This is causing a conflict with another trait the model is inheriting`?

**Comment by 06chaynes** [comment]
After applying the Searchable trait to my model (App\Models\Organization), I get the following error when running artisan commands like 'scout:import' or 'config:cache':  `Trait method usesSoftDelete has not been applied, because there are collisions with other trait methods on App\Models\Organization`. The trait that it is colliding with is a nested-set package I use for this model.

**Comment by 06chaynes** [comment]
Ah, I was looking at it wrong I see. I decided to fork the other package in question and rename the conflicting method, all good now. Thanks again!
