### ISSUE TITLE
[6.1.3] Method Illuminate\Support\Collection::load does not exist.

### ISSUE THREAD

**Issue by Dylan-Chapman** [laravel/scout#339]
When I updated to 6.1.3 from 6.1.1, I can no longer do the following:

```php
MyModel::search('myQuery')->get()->load('myRelation');
```

And I receive the error

```
Method Illuminate\Support\Collection::load does not exist.
```

Is there a new suggested method for loading relationships with searching?

**Comment by driesvints** [comment]
You're getting back a plain collection instead of an `Illuminate\Database\Eloquent\Collection`. It could be due to the changes made in https://github.com/laravel/scout/pull/334 but I'm not so sure why you're getting back a plain collection. 

Are you overwriting the `newCollection` method in your model? Are you using the `query` method on the Scout Builder?

**Comment by Dylan-Chapman** [comment]
Nope, not overwriting `newCollection`, and not sure what the `query` method on the Scout Builder is/does. My model uses `Laravel\Scout\Searchable` and has a `toSearchableArray` method, and a controller that returns the results of `MyModel::search('myQuery')->get()->load('myRelation');`. That's all that's really happening related to searching.

If it matters, I'm using the `teamtnt/laravel-scout-tntsearch-driver` search driver.

**Comment by Dylan-Chapman** [comment]
Oh, I'd like to add that I can get around the problem by doing the following instead: 
```php
MyModel::search('myQuery')->paginate(0)->load('myRelation');
```

**Comment by driesvints** [comment]
I *think* it might be related to this piece of code: https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L197-L206

But it's best that you open up an issue on their repo.

**Comment by sanjayojha** [comment]
I have the same problem. I am using it with Laravel 5.7 and latest drivers. 
For now, I am using the temp fix suggested by @Dylan-Chapman 
```php 
$posts = Post::search($query)->where('approved', 1)->paginate(0);
$posts->load(['author', 'category']);
```
Any update on it?

**Comment by mforcer** [comment]
@driesvints is this a TNT issue? The problem that I can see is that when using `search()` on a model it returns a Laravel\Scout\Builder instance which does not have access to load/with and neither does Collections obviously meaning neither of the relation loading methods can be used when returning results.

I've been forced to use the `paginate(0)` method to get around it.

**Comment by driesvints** [comment]
@mforcer I believe so. Look at the line I linked to. It always returns a plain collection and not an Eloquent one.

**Comment by superpromiser72** [comment]
Fucking

**Comment by alchibekov** [comment]
MyModel::search('myQuery')->get()->load('myRelation');

> I _think_ it might be related to this piece of code: https://github.com/teamtnt/laravel-scout-tntsearch-driver/blob/master/src/Engines/TNTSearchEngine.php#L197-L206
> 
> But it's best that you open up an issue on their repo.

**Comment by alchibekov** [comment]
> Oh, I'd like to add that I can get around the problem by doing the following instead:
> 
> ```
> MyModel::search('myQuery')->paginate(0)->load('myRelation');
> ```

`MyModel::search('myQuery')->paginate(0)->load('myRelation');`
