### ISSUE TITLE
AlgoliaEngine::map does not respect the order of the Engine results

### ISSUE THREAD

**Issue by nunomaduro** [laravel/scout#341]
**Context**: Engines, like Algolia, allow to define the ranking - order of the results.

An example could be: I want products to be sorted by the quantity, so when I type "iphone" i want to get the ones that I have more in stock.

**Problem**: The method `AlgoliaEngine::map` does not return the models in the same order of the returned results by Algolia. Mainly because a `whereIn` is applied behind-the-scenes.

**Solution**: Sort the models by the same order of the given results just before returning the result of `AlgoliaEngine::map`.

**Comment by driesvints** [comment]
@nunomaduro I tried looking into this but I don't see how `whereIn` influences the order?

**Comment by nunomaduro** [comment]
The `AlgoliaEngine::map` will call the method `getScoutModelsByIds` from the trait `Searchable.php`.

The method `getScoutModelsByIds` will perform a `Model::whereIn`. The problem here: When you perform a regular `$users = User::whereIn('id', [2,3,1])->get();`, and assuming that you are using Mylsql, Eloquent will just tranform that in `SELECT * FROM users WHERE id IN (2,3,1);`. And mysql, be default, will return the rows in ID ascending order (1,2,3).

In this process you loose the order returned by the search engine.

```php
# currently
$models = User::search('iphone')->get(); // search engine returns (2,3,1)
echo $models[0]->id // 1
echo $models[1]->id // 2
echo $models[2]->id // 3

# my proposal 
$models = User::search('iphone')->get(); // search engine returns (2,3,1)
echo $models[0]->id // 2
echo $models[1]->id // 3
echo $models[2]->id // 1
```

**Comment by devinfd** [comment]
I can second this bug and I hope that you consider it critical. My search results are now in a seemingly random order. So basically the search results are useless. I can't see where this bug was introduced so I can't recommend a change. Sorry

**Comment by devinfd** [comment]
fyi: I had to implement an immediate fix so I overrode getScoutModelsByIds in my model with 

```php
return $query->whereIn(
            $this->getScoutKeyName(), $ids
        )->orderByRaw('FIELD('.$this->getScoutKeyName().', '.implode(', ', $ids).')')->get();
```

It's sloppy but it works

**Comment by nunomaduro** [comment]
@devinfd On Scout Extended this problem do not exists. Can you try see this source code https://github.com/algolia/scout-extended/blob/7935885de233a1d651e46f621b2c7ccce64da3fc/src/Searchable/ModelsResolver.php#L87 and perform a pull request to Laravel Scout?

**Comment by devinfd** [comment]
I can try that at some point. I'm away at conference and cant dedicate the time for at least a week.

**Comment by ChrisThompsonTLDR** [comment]
This should fix the issue.

```
    public function map(Builder $builder, $results, $model)
    {
        if (count($results['hits']) === 0) {
            return $model->newCollection();
        }

        $objectIds = collect($results['hits'])->pluck('objectID')->values()->all();

        return $model->getScoutModelsByIds(
                $builder, $objectIds
            )->filter(function ($model) use ($objectIds) {
                return in_array($model->getScoutKey(), $objectIds);
            })->sortBy(function($model) use ($ids) {
                return array_search($model->getScoutKey(), $ids);
            });
    }
```

**Comment by driesvints** [comment]
PR Made: https://github.com/laravel/scout/pull/369

**Comment by devinfd** [comment]
thank you @driesvints !
