### ISSUE TITLE
Get Builder Instance

### ISSUE THREAD

**Issue by lukecurtis93** [laravel/scout#343]
Is it possible to get a base Laravel builder class from the search query, I'm trying to achieve the following: [link](https://laracasts.com/discuss/channels/laravel/get-builder-instance-from-laravel-scout)

Essentially, used in conjunction with [spatie query builder](https://github.com/spatie/laravel-query-builder) it'd be super neat if we could do something like the following:
```
QueryBuilder::for(User::search(request('query'))
    ->allowedIncludes('posts')
    ->get();
```

However Scout currently returns a Scout builder so the Query Builder will not accept this class as its parameter.

Any advice would be greatly appreciated.

**Comment by driesvints** [comment]
Heya, no this isn't possible atm. The Scout Builder is a very different builder type then the query builder. You'd have to create some sort of custom transpiler.
