### ISSUE TITLE
restore a soft delete model runs MakeSearch twice

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/scout#344]
When I `restore` a soft-deleted record, two `MakeSearchable` jobs are queued up at exactly same time.

Screenshot @ https://pasteboard.co/HWvt34X.png

Any ideas why there are 2 `MakeSearchable` jobs?

**Comment by driesvints** [comment]
What version of Laravel, Horizon & Scout are you using?

**Comment by nunomaduro** [comment]
@michaelnguyen547 Are you using the model event `restored` or `restoring` for something in your application?

**Comment by michaelnguyen547** [comment]
this is my code


```
public function enable(Badge $badge)
{
    $badge->restore();
    return redirect()->route('admin.badge.index')
           ->with('flash_success', 'A Badge has been enabled');
}
```

**Comment by driesvints** [comment]
@michaelnguyen547 are you still experiencing this? Can you maybe create a sample app which recreates this problem so we can test?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by chris-lee-lb** [comment]
@driesvints I've also faced the same problem.

After some researches, I've found out that `Laravel\Scout\ModelObserver` will receive `saved` & `restored` events at same time when you restore soft-deleted model.

So you will dispatch `MakeSearchable` job twice.
