### ISSUE TITLE
Wrong pagination total count with global scope

### ISSUE THREAD

**Issue by vedmant** [laravel/scout#345]
I have an issue with pagination, it shows wrong total pages count.
Looks like the issue is caused by global scope, applied to a model.
Global scope is applied to get, but not count. For example `Post::search($request->get('q'))->get();` returns 4 records, but `Post::search($request->get('q'))->count()` returns 9.

I use scout with elasticsearch using driver babenkoivan/scout-elasticsearch-driver, not sure if it's scout issue or driver only issue.

"laravel/framework": "5.7.*",
"laravel/scout": "^6.1",
"babenkoivan/scout-elasticsearch-driver": "^3.9",

**Comment by nunomaduro** [comment]
This seems normal. If you want to apply the global scope in `get` and in `count` results you may need change the code into: 

```php
Post::search($request->get('q'))->get(); // returns 4 records.
Post::search($request->get('q'))->get()->count(); // returns 4 records.
```

Using `Post::search($request->get('q'))->count()`doesn't take the global scope into consideration since the count is returned directly from the search engine.

**Comment by vedmant** [comment]
@nunomaduro Thanks, but this breaks pagination. When I do `Post::search($request->get('q'))->paginate();` it also returns total count 9 while actual posts count is just 4. It shows wrong number of pages in case I add more posts.

**Comment by driesvints** [comment]
Can you please post some more code? There isn't a `count` method on the builder so not sure how this could work in the first place. Did you implement a macro? Can you post the model & global scope?

**Comment by vedmant** [comment]
Here is global scope, it's added through boot method of a trait.

        // Set domain scope by default
        static::addGlobalScope('domain', function (Builder $builder) {
            $domain = app('domain')->getDomain();
            $builder->where($builder->getModel()->getTable() . '.domain_id', '=', $domain->id);
        });

In my search controller method I use `Post::search($request->get('query'))->paginate()` it pulls posts only from the current domain, and it shows wrong total count. For now I added workaround `Post::search($request->get('query'))->where('domain_id', app('domain')->getDomainId())->paginate()` it works properly in this case when `where('domain_id',...` is passed directly. About `->count()`, I just used it for example. It my case it work normally `Post::search($request->get('query'))->count()`. The method comes from elastic search builder ScoutElastic\Builders\FilterBuilder.

**Comment by driesvints** [comment]
I'm sorry but we don't offer support for any third party packages like scout-elasticsearch-driver. We don't have a count method ourselves so I don't see how this is a issue with Scout itself. It's best that you raise an issue on their repo.
