### ISSUE TITLE
Provide synchronizable feature

### ISSUE THREAD

**Issue by lucasmichot** [laravel/scout#346]
Hello there, I've been using intensively this package for this last months and I feel a `synchronizable` (in lack a better name) is missing.

Sometimes you may define `shouldBeSearchable` with a specific condition.
Then make product `upsert` models (`searchable`), and if they've already been indexed, remove them (`unsearchable`).

But if we decide to update `shouldBeSearchable` so that it restricts a bit more the number of models to index, you will still have models inedexed that you don't want searchable anymore.

I feel `synchronizable` is missing here: this function is purpose is the following:
- insert searchable models in the index which are not present
- update searchable models in the index
- remove unsearchable models from the index (or try to remove them, as they might not have been ever indexed)

---

I might be missing something, but I don't think that this feature is present so far....

Feel free to give your thoughts, or propose alternative solutions.

I'm happy to make a PR it makes sense

**Comment by driesvints** [comment]
I don't have time to look at this atm but maybe @nunomaduro can provide some insights?

**Comment by lucasmichot** [comment]
Elasticsearch does

**Comment by driesvints** [comment]
I've been looking into this but I personally think that just running `scout:flush` and `scout:import` after each other already mimics this behavior. So I don't think it makes sense to add a dedicated method that checks each record's state separately.

If you want you can always attempt a PR. Thanks

**Comment by lucasmichot** [comment]
Hm flushing the index, and then importing would not work - as some import can last for a very long time.
This would lead to incomplete search results for the people using the search service; such a user experience would not be acceptable.

I will propose a PR soon.
