### ISSUE TITLE
[7.0] Algolia API client v2

### ISSUE THREAD

**Issue by mvdnbrk** [laravel/scout#348]
Algolia rewrote their API client entirely and released v2 of their client two months ago.

Any plans on upgrading scout to use the latest version of the Algolia API client?

The upgrade doesn't seem to be very complicated, let me know if a PR for this is appreciated.

**Comment by lucasmichot** [comment]
It's a very good reason to postpone 👍 
Congrats @nunomaduro !!

**Comment by mvdnbrk** [comment]
If I have the time I will take a look into it and submit a PR.

We can release this by the end of february 😄

Congrats and have a great time @nunomaduro :tada:
