### ISSUE TITLE
Can't skip empty updates using soft deletes

### ISSUE THREAD

**Issue by timeisenhuth** [laravel/scout#350]
Further to this issue https://github.com/laravel/scout/pull/318 - If `scout.config.soft_delete` is true, it ends up merging the `__soft_deleted` property here:

https://github.com/laravel/scout/blob/6.0/src/Engines/AlgoliaEngine.php#L49

and so the empty check on the array here https://github.com/laravel/scout/blob/6.0/src/Engines/AlgoliaEngine.php#L53 - is always false

So any time I'm returning an empty array from `toSearchableArray` with soft deletes turned on it's sending through empty objects to Algolia with just the __soft_deleted property

Is this intentional?

**Comment by driesvints** [comment]
No, I don't believe so. I'll take a look at this soon.

**Comment by driesvints** [comment]
I think the following lines are a bit weird. Wouldn't you just want to skip if the `toSearchableArray` is empty? I'm not sure why `scoutMetadata` is checked. 

@nunomaduro do you believe we should just filter on `toSearchableArray` and not `scoutMetadata`?

**Comment by nunomaduro** [comment]
Thanks for creating this issue @timeisenhuth.

1. Without soft-deletes: 

Problem: If a records exists at the Algolia side, an empty array from the `toSearchableArray` don't delete the record from Algolia.

R: A solution may be: Delete the record from Algolia, not sure.

2. With soft-deletes: 

Problem: If a records exists at the Algolia side, an empty array from the `toSearchableArray` + `__soft_deleted ` will causing the update on the record with the following content: 
```php
['objectID' => 'objectID', '__soft_deleted` => 1]
```

R: A solution may be: Delete the record from Algolia again, no sense of having am empty record at Algolia.

**Comment by driesvints** [comment]
@nunomaduro but this doesn't solves the original question: does it even makes sense to sync a record if its `toSearchableArray` is empty? I believe the code should be:

```php
    public function update($models)
    {
        if ($models->isEmpty()) {
            return;
        }

        $index = $this->algolia->initIndex($models->first()->searchableAs());

        if ($this->usesSoftDelete($models->first()) && config('scout.soft_delete', false)) {
            $models->each->pushSoftDeleteMetadata();
        }

        $objects = $models->map(function ($model) {
            if (empty($model->toSearchableArray())) {
                return;
            }

            $array = array_merge(
                $model->toSearchableArray(), $model->scoutMetadata()
            );

            return array_merge(['objectID' => $model->getScoutKey()], $array);
        })->filter()->values()->all();

        if (! empty($objects)) {
            $index->saveObjects($objects);
        }
    }
```

**Comment by driesvints** [comment]
And in this block maybe change it to:

```php
             if (empty($model->toSearchableArray())) {
                // delete model instead.
            }
```

**Comment by nunomaduro** [comment]
I see. Let's focus on the original question.

Your code seems correct, just make sure you call the `$model->toSearchableArray()` just once, and reuse the result for later merge the `scoutMetadata`.

Can you perform a pull request? I will check it.

**Comment by nunomaduro** [comment]
Let's ignore the `// delete model instead.` issue for the moment.

**Comment by driesvints** [comment]
@nunomaduro will do 👍
