### ISSUE TITLE
toSearchableArray doesn't get relations when save from Nova

### ISSUE THREAD

**Issue by msassa** [laravel/scout#351]
I have a model, with some relations.
One is a belongsTo, and I'm adding some information from this relation to the toSearchableArray to indexed in Algolia.
The main model is something like this:

```
class Car extends Model
{
    use Searchable;

    public function toSearchableArray()
    {
        $searchableCar = array_only(
            $this->toArray(),
            ['id', 'title', 'url', 'active', 'vin', 'stock', 'bodyStyle', 'certifiedPreowned', 'color', 'diff', 'engine', 'kilometer', 'miles', 'make', 'model', 'price', 'year']
        );

        $searchableCar['import'] = $this->import->name;

        return $searchableCar;
    }

    public function import()
    {
        return $this->belongsTo(Import::class);
    }
}

```

And when I create a new model from Nova, I get an error saying 
`ErrorException: Trying to get property 'name' of non-object` like the relation doesn't exist yet.

I make a dump of the model in the saved event, and the import is null  🤷‍♂️

I fix this overwriting the method:

```
public function queueMakeSearchable($models)
    {
        if ($models->isEmpty()) {
            return;
        }

        $models->load('import');

        if (!config('scout.queue')) {
            return $models->first()->searchableUsing()->update($models);
        }

        dispatch((new MakeSearchable($models))
            ->onQueue($models->first()->syncWithSearchUsingQueue())
            ->onConnection($models->first()->syncWithSearchUsing()));
    }

```

and manually loading the relation and it works ... but doesn't feel ok

Someone has deal with this problem?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by msassa** [comment]
Hi, thanks for the reply.
I think this may be a bug, since the toSearchableArray method is not taking the relationships, and I have to manually include them by modifying a trait method.

**Comment by driesvints** [comment]
Can you first please try one of the above support channels? If you can actually identify this as a bug, feel free to report back.
