### ISSUE TITLE
Using Model::create in a seeder does not call searchable

### ISSUE THREAD

**Issue by loic-lopez** [laravel/scout#361]
Hello,

I created several models in my seeder but they are not queued with the MakeSearchable job, I was able to do manual tests:

- migrate: fresh --seed no data
- migrate: fresh --seed and manually call: 
```php
User::all()->map (function $user) {
    $user->searchable();
});
```
-> jobs have been pushed

Thanks for reply.

**Comment by driesvints** [comment]
Can you first please try one of the following support channels? If you can actually identify this as a bug, feel free to report back.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
