### ISSUE TITLE
How to update custom field on algolia search?

### ISSUE THREAD

**Issue by maidul98** [laravel/scout#363]
public function toSearchableArray(){
    $array = $this->toArray();

    //find the user
    $user = User::findOrFail($this->user)->first();
    $bookmark = bookmark::where(['user_id' => $this->user_id, 'want_id' => 18])->first();
    $array['user'] = $user;
    $array['bookmark'] = $bookmark;
    return $array;
    }

Now, when a user adds a new post to his/her bookmark, I want to update the bookmark field of this post to be that bookmark. Problem is how to do update this custom bookmark that is not apart of my real table?

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
