### ISSUE TITLE
Does we really need builder inside getScoutModelsByIds?

### ISSUE THREAD

**Issue by matchish** [laravel/scout#366]
[https://github.com/laravel/scout/blob/484ff556fe2def2eab9f8eb2e60becba36c439d9/src/Searchable.php#L171](https://github.com/laravel/scout/blob/484ff556fe2def2eab9f8eb2e60becba36c439d9/src/Searchable.php#L171)
I think the signature should be 
`public function getScoutModelsByIds(array $ids, callable $callback)`

**Comment by driesvints** [comment]
Hmm, I do agree that the method could use a little bit refactoring but I still think it's an internal method which should be used as a part of the public API. It's also undocumented (and not meant to be). It's currently being used in the `map` method on the `AlgoliaEngine` class. 

What's your specific use case?

**Comment by matchish** [comment]
Yes, it's not documented, but it's part of trait Searchable and I think all in this trait part of public API because it's in the scope of a searchable model. And it's not marked as internal in phpdoc. And in docs, we have a note that `AlgoliaEngine` is a good point for building custom engine. 
So my case is a custom engine, I've used the method when map results to models, like in AlgoliaEngine.
I extract  mapping code to transformer class, and it looks not clear with the builder as a dependency

**Comment by driesvints** [comment]
I'll mark this as an enhancement. Feel free to send in a PR if you want. I do believe a better signature might be: 

```php
public function getScoutModelsByIds(array $ids, callable $queryCallback = null)
```

**Comment by matchish** [comment]
Thank Dries for confidence. I've created [pull request ](https://github.com/laravel/scout/pull/367)

**Comment by driesvints** [comment]
Unfortunately the pr got rejected so I think it's best that we leave things be for now...

**Comment by maximusblade** [comment]
Still a valid question
