### ISSUE TITLE
Restrict models applied for importing

### ISSUE THREAD

**Issue by vyuldashev** [laravel/scout#368]
`scout:import` imports all models. I need to import models not older than 6 month. How can I achieve this?

**Comment by vyuldashev** [comment]
I know that it can be achieved by `App\Order::where('price', '>', 100)->searchable();`, but I wonder if there is a way to achieve it with `scout:import` command.

**Comment by kp-syginteractive** [comment]
This question is probably more appropriate for help forums. Maybe you can override the toSearchableArray() method on the model?

https://laravel.com/docs/5.8/scout#configuring-searchable-data

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
