### ISSUE TITLE
Creating the Paginator using the container

### ISSUE THREAD

**Issue by rico** [laravel/scout#371]
It would be great, if the `LengthAwarePaginator` in `Laravel\Scout\Builder` would be created using the `Container` - like in `Illuminate\Database\Eloquent\Builder` - so that we can customize it or automatically append `query`parameters.

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. It's best to post these at the [laravel/ideas](https://github.com/laravel/ideas) repository to get support for your idea. After that you may send a PR to the framework. Please only use this issue tracker to report bugs and issues with the framework.

Thanks!

**Comment by driesvints** [comment]
Yep, can see that being useful.

**Comment by IlmLV** [comment]
I am also looking forward to see this implemented.
Also should consider load other classes throw container, to be able easily extend for example Builder class. If I could be able to load extended Builder class it could be much easier to override LengthAwarePaginator.

**Comment by driesvints** [comment]
Since only two people have requested this in the last year I'm going to close this one. But we're open to prs if anyone wants to see this in Scout.
