### ISSUE TITLE
MakeSearchable failed the request although It's configured to be queued

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/scout#377]
- Scout Version: 7.1.2
- Laravel Version: 5.7.28
- PHP Version: 7.2.19
- Database Driver & Version: MySQL v5.7

### Description:
I have a `User` model with `Searchable` trait, I configured scout to work with my Algolia account and I also configured it to index data only asynchronously (queue).
For some reason, in the last week I had 2 incidences that a request was failed on production because of an HTTP request timeout, this is the error:
`GuzzleHttp\Exception\ConnectException
: cURL error 28: Resolving timed out after 2512 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
I am using Sentry to catch exceptions and I can see in which LOC the exception is thrown:
```php
$payload = $request->validated();
$user = User::create($payload); // Here the exception thrown - the request got broken
$user->attachRole(User::ROLE_AGENT);
$user->sendInvitationMail();
// The user created, the client receives some error message
// and when he trys to re-register he receives another error:
// "this email address already exists" 🤦‍♂️
```
I am also using Laravel Telescope and I can see the trace, and the exception is come from the `MakeSearchable` class.

**What do you think could lead to this issue?**
There is an option to increase the request timeout?

### Steps To Reproduce:
I didn't manage to reproduce it.

### Notes
- My app is on production for almost a year using Laravel Scout and Algolia and this is the first time it happens
- I didn't change anything related to Scout's configurations
- I am using Laravel Horizon with Redis for queues

**Comment by MatanYadaev** [comment]
BTW, I already had 200 times this cURL error 28 (request timeout), it's started 3 months ago and it's been only on the queue server, the 2 incidences I explained is regarding the API server, not the queue one.

**Comment by driesvints** [comment]
It's a little bit hard to debug this since you don't have too much info and can't reproduce it yourself. Are there any more logs you can dig up? Can you implement a bug tracker like Bugsnag to check if that could uncover some more info?

**Comment by MatanYadaev** [comment]
Unfortunately I don't have any further information about this issue 😔
Anything you could advice me to check? What could goes wrong in a situation like this?

**Comment by wisoot** [comment]
I see the similar errors from time to time roughly about 35 times in the pass 2 months. It doesn't seem to occur constantly but intermittently.
The error happen inside algolia package. Maybe the error should be suppressed if it is legit network error?

**Comment by MatanYadaev** [comment]
@wisoot Yea but my issue is about it happens at the request and not async on the queue.
Why do the project communicate with Algolia at the request?

**Comment by nunomaduro** [comment]
@MatanYadaev No worries, let's try to debug this together. To make sure I understand: You have 2 servers, the web server and another server responsible for the async tasks (queue) right? Both have the `Resolving timed out after...` issue?

**Comment by MatanYadaev** [comment]
@nunomaduro Thanks for the help, I appreciate it. Yes, I have 2 servers, both have this issue.
In the API server it happened for 3 times, and at the Queue server it happened more than 200 times.

I really think that for some reason `MakeSearchable` isn't running on the queue server.
An example from Laravel Telescope:
![][https://i.ibb.co/RhkhLFB/image.png]
The hostname is `api-production` instead of `queue-production`, in scheduled job I can see that the hostname is for sure `queue-production`.

**Comment by driesvints** [comment]
@MatanYadaev are you still experiencing this?

**Comment by MatanYadaev** [comment]
@driesvints No
