### ISSUE TITLE
Set connect timeout configuration for Algolia php client

### ISSUE THREAD

**Issue by moosapour-arash** [laravel/scout#379]
- Scout Version: 7.1.1
- Laravel Version: 5.7.7
- PHP Version: 7..2

### Description:
i want to customize the timeout values in algolia php client , as described [here](https://www.algolia.com/doc/api-reference/api-methods/configuring-timeouts/)
is it possible / how to set these kind of configuration through scout ?

### Workaround
i have managed to set my desired configurations by calling extend function on EngineManger class in AppServiceProvider:
```php
        $this->app->resolving(EngineManager::class,function ($engine,$app){
                        $engine->extend('algolia',function (){
                        UserAgent::addCustomUserAgent('Laravel Scout', '7.0.0');
                        $config = SearchConfig::create(config('scout.algolia.id'), config('scout.algolia.secret'));
                        $config->setConnectTimeout(config('scout.algolia.connectTimeout'));
                        $config->setReadTimeout(config('scout.algolia.readTimeout'));
                        $config->setWriteTimeout(config('scout.algolia.writeTimeout'));
                        return new AlgoliaEngine(
                            Algolia::createWithConfig($config),
                            config('scout.soft_delete')
                        );
                    });
        });
```
but its kinda hackish,is there any other better way ?

**Comment by driesvints** [comment]
Think this would be a feature request. If you can send in a PR which implements the `SearchConfig` in a clean way that would be nice. My first thoughts are of indeed adding the settings to the Algolia config.

**Comment by moosapour-arash** [comment]
@tillkruss just a few days after i opened this, algolia banned all iranians IPs  due to sanctions ,both in frontend and client side APIs , so there is no point for me to contribute , feel free to send PR

**Comment by driesvints** [comment]
Since only one person has requested this and doesn't needs it anymore I'm gonna close this. Welcoming prs however.
