### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by HilmanAnshori** [laravel/scout#38]
Hello,
I'm trying to implement scout but paginate method not working properly, am i doing it wrong or it's a bug?

here's my implementations:
driver : tried tntsearch and now using algolia (same issue)

my model: only use Searchable trait (searchableAs() and toSearchableArray() not implemented)

indexing : using "php artisan scout:import "App\Models\Blog\Blog" and output:

```
Imported [App\Models\Blog\Blog] models up to ID: 100  
All [App\Models\Blog\Blog] records have been imported.
```

if in my controller:

``` php
$posts = Blog::search($request->get('q'))
        ->paginate(10)->appends(["only" => "q"]);
        dump($posts);
```

output blog/search?q=ipsum:
![screenshot_7](https://cloud.githubusercontent.com/assets/3981733/18027126/5087b430-6c85-11e6-98cc-9671b497c03c.jpg)

output blog/search?q=ipsum&page=2:
![screenshot_8](https://cloud.githubusercontent.com/assets/3981733/18027132/702c1330-6c85-11e6-99b9-f5bf6184676d.jpg)

if i change controller to:

``` php
$posts = Blog::search($request->get('q'))
        ->get();
        dump($posts);
```

output blog/search?q=ipsum:
![screenshot_9](https://cloud.githubusercontent.com/assets/3981733/18027142/aa2105f0-6c85-11e6-8444-5b9ceaf32966.jpg)

thanks

**Comment by julienbourdeau** [comment]
I'm not sure what you expect. Isn't because you forgot to use `all()`?

```php
$posts = Blog::search($request->get('q'))->paginate(10)->all();
dump($posts);
```

**Comment by driesvints** [comment]
Can you please add more info than "not working properly". Please be specific as what's not working. The above example seems to work fine for me.
