### ISSUE TITLE
Update user agent with each release

### ISSUE THREAD

**Issue by tillkruss** [laravel/scout#383]
@driesvints: Could you update the user agent with each release?

Could this even be automated somehow?

https://github.com/laravel/scout/blob/1e22f8e8442795233a344d3994b0d1e297bf3f92/src/EngineManager.php#L30-L40

**Comment by driesvints** [comment]
@tillkruss urgh, sorry about that. Will do 👍 

Not sure about how to automate this.

**Comment by tillkruss** [comment]
Reading the composer `installed.json` seems terrible. Maybe a GitHub action?

https://github.com/release-it/release-it

**Comment by driesvints** [comment]
Would have to be very specific for socialite I guess?

**Comment by driesvints** [comment]
Updated the user agent for the latest release.
