### ISSUE TITLE
Add user identification by default?

### ISSUE THREAD

**Issue by tillkruss** [laravel/scout#385]
From the Algolia docs:

>For analytics query aggregation to work properly, the analytics engine relies on a user id.
>
>Many front-end solutions tag every search with the end-user’s HTTP request IP. However, it is important to not rely on this behavior. You should explicitly create a unique user identifier that you maintain in your own application. For example, you could use a unique id you store in a database.
>
>When using a back-end API client, you want to:
>
> - set the X-Forwarded-For header to forward the user IP to Algolia
> - set the userToken search parameter to tell Algolia which user is querying

Should we add this by default? Happy to open a PR.

 - https://www.algolia.com/doc/api-reference/api-methods/set-extra-header/
 - https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/out-of-the-box-analytics/how-to/specify-which-user-is-doing-the-search/

**Comment by nunomaduro** [comment]
Overall I think it's a good idea, you may also want to keep in mind this issue https://github.com/laravel/scout/issues/379 - as they are related and both want to modify the `SearchConfig` instance.

How would you see this concerning the developer experience?

**Comment by tillkruss** [comment]
I assume @moosapour-arash won't be sending a PR, so this could be part of it. Great tip!

My first thoughts about solving this were automatically adding `X-Algolia-UserToken` and `X-Forwarded-For` as default headers. Probably a config toggle to turn it off for the Europeans.

**Comment by tillkruss** [comment]
I guess this could be done fairly easily on a per-app basis:

```php
<?php

namespace App\Providers;

use Laravel\Scout\EngineManager;
use Laravel\Scout\Engines\AlgoliaEngine;

use Algolia\AlgoliaSearch\Support\UserAgent;
use Algolia\AlgoliaSearch\Config\SearchConfig;

use Illuminate\Support\ServiceProvider;

class SearchServiceProvider extends ServiceProvider
{
    public function boot()
    {
        UserAgent::addCustomUserAgent(
            config('app.name'),
            env('HEROKU_RELEASE_VERSION', 'testing')
        );
        
        resolve(EngineManager::class)->extend('algolia', function () {
            $config = SearchConfig::create(
                config('scout.algolia.id'),
                config('scout.algolia.secret')
            );

            $config->setDefaultHeaders([
                'X-Forwarded-For' => '...',
                'X-Algolia-UserToken' => '...',
            ]);

            return new AlgoliaEngine(
                SearchClient::createWithConfig($config),
                config('scout.soft_delete')
            );
        });
    }
}
```

**Comment by tillkruss** [comment]
The question now is should Scout do this by default, or not?

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/scout/pull/411

Thanks for the initial code @tillkruss.
