### ISSUE TITLE
Non-static method exception using scout:import

### ISSUE THREAD

**Issue by jim0thy** [laravel/scout#388]
- Scout Version: 7.2.1
- Laravel Version: 6.0.4
- PHP Version: 7.2.21
- Database Driver & Version: MariaDB 10.4.6

### Description:
Calling `scout:import "App\Model"` causes the error:

>  *Non-static method App\Model::usesSoftDelete() should not be called statically*

The stack trace points to line 122 in **Searchable.php**:
```php
$softDelete = static::usesSoftDelete() && config('scout.soft_delete', false);
```

This happens on all `Searchable` models across several projects, regardless of whether the model uses the `SoftDeletes` trait.

### Steps To Reproduce:
Run `php artisan scout:import "App\Model"`

**Comment by jim0thy** [comment]
Ignore this, I'm an idiot.

**Comment by shortcodes** [comment]
> Ignore this, I'm an idiot.

@jim0thy I am curious. Why i am an idiot too? Maybe some feedback for me's in future, and present?

**Comment by shortcodes** [comment]
Ok. I know why i am idiot. In my Engine i had non static method `usesSoftDelete`. Nothing to do with this package. It is greaT ;)
