### ISSUE TITLE
Paginator Total Issue

### ISSUE THREAD

**Issue by agariaw** [laravel/scout#389]
- Scout Version: 6.1.3
- Laravel Version: 5.8.35
- PHP Version: 7.3.4

### Description:
I'm using ElasticSearch with scout. after ElasticSearch returns rows like 50 from the search. I set a callback using query() function in \Laravel\Scout\Builder. In which I filter the returned results based on some other relationship. which sets the total items in collection to 1.  But the paginator 
does not update the pagination details like total, last page etc. It still continues to show pagination details based on 50 result.
### Steps To Reproduce:
Use search using scout. then filter the data using query() function. it will update the collection items but not pagination details.
E.g.
```
 $model = Model_NAME::search($searchTExt)
            ->query(function ($query) {
                       return $query->whereHas('users', function($query){
                            return $query->where('user_id', '=', ID );
                     });
              })
```

**Comment by nunomaduro** [comment]
@agariaw Are you using `babenkoivan/scout-elasticsearch-driver`?

**Comment by driesvints** [comment]
I'm sorry but we don't support elasticsearch. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by agariaw** [comment]
@nunomaduro No I'm not.
@driesvints shouldn't this be a issue of scout as I'm using Laravel Scout Builder's function query() to filter data.  This class also sets the LengthAwarePaginator which is causing the issue?

**Comment by driesvints** [comment]
@agariaw don't you need paginate instead of search?

**Comment by agariaw** [comment]
Actually I need both. I am searching for the projects with the restriction of only shared with user. then paginate the result and send it to the browser. But paginator is not working correctly in this case I think.

**Comment by driesvints** [comment]
@agariaw I'm gonna keep this closed unless something's broken with the Algolia driver, sorry. But definitely feel free to send in a PR if you think there could be an improvement somewhere.

**Comment by usrNotFound** [comment]
I am having this problem with algolia search as well.

  Model::search('query)
                ->query(fn (Builder $builder) => $builder->whereHas('model, fn($query) => $query->where('id' , $id)
                ->paginate(25))

would mess up pagination total. It seems like pagination is completely ignoring the query part
