### ISSUE TITLE
Call to undefined method search

### ISSUE THREAD

**Issue by Justicea83** [laravel/scout#390]
"Call to undefined method Illuminate\Database\Eloquent\Builder::search()", exception: "BadMethodCallException", file: "C:\wamp64\www\gold-app\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php",

I have used the trait on the model
class Region extends Model
{
    use Searchable;

    public function country(){
        return $this->belongsTo(Country::class);
    }
}

public function index(Request $request)
    {
        $searchable = $request->has('search') && strlen($request['search']) > 0;
        return $this->showOne(Region::with('country')
            ->when($searchable, function ($query, $searchable) use($request) {
                return $query->search($request['search']);
            })
            ->latest()
            ->paginate($request->size));
    }

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by jhoanborges** [comment]
Add use Laravel\Scout\Searchable; in your model like this

```
<?php
 
namespace App\Models;
 
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
 
class Post extends Model
{
    use Searchable;
}
```
