### ISSUE TITLE
there is bug in the conf file of scout

### ISSUE THREAD

**Issue by argb** [laravel/scout#391]
- Scout Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
 public function syncWithSearchUsingQueue()
    {
        return config('scout.queue.queue');
    }

It's wird, in conf file, scout.queue is not an array.
If it's an array in the .env file, the setting  SCOUT_QUEUE would be meaningless.

How can I set SCOUT_QUEUE to be an array in .env file?

it's really bad !!!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
