### ISSUE TITLE
Query object instead of term

### ISSUE THREAD

**Issue by matchish** [laravel/scout#397]
What if instead of a term we can pass a `QueryObject`?
Then we can change how we build query on the fly. I mean often we need to tune a query for a 
 specific query but not for all application. The same with results mapping.

How it can be
https://github.com/matchish/laravel-scout-elasticsearch/issues/88#issuecomment-585074403

**Comment by driesvints** [comment]
Can you please explain in more detail, preferable with some code examples?

**Comment by matchish** [comment]
I'll do it later. I have a simpler solution now
