### ISSUE TITLE
Dont work whereNotNull

### ISSUE THREAD

**Issue by VictorPullzz** [laravel/scout#398]
- Scout Version: 6.1.*
- Laravel Version: 5.5.*
- PHP Version: >=7.1.0
- Database Driver & Version: MySql 5.7

### Description:
This method does not work. But even when I do it through the usual Builder method where ('...', '! =', Null) / where ('...', '<>', null), an empty collection is returned to me, although it cannot to be!

### Steps To Reproduce:
1 - Create any model let's say Post | id | user_id | created_at ...
2 - Add 5 records. One record have empty user_id
3 - Post::search('some text')->where('user_id', '<>', 'null')->get()
4 - Empty result...

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by VictorPullzz** [comment]
Thank you for answer, unfortunately I can’t update the version on the project, this will lead to many problems..

**Comment by driesvints** [comment]
@magarrent this seems like a feature request. Please try a PR if you want to add this to Scout.
