### ISSUE TITLE
Restoring data not updating on algolia

### ISSUE THREAD

**Issue by MadaniTech** [laravel/scout#401]
- Scout Version: 7.2
- Laravel Version: 6.0
- PHP Version: 7.3
- Database Driver & Version: mariadb 10

### Description:
All is working well on creating updating and deleting record. But on restore it does not update on algoia search.

### Steps To Reproduce:
My code is
```
$data = Model::onlyTrashed()->where('data', $data);
$data->firstOrFail();
$data->restore();
```

Its working on db end but not updating on algolia. What is the function on scout to restore on algolia indexing. Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MadaniTech** [comment]
@driesvints thanks.
