### ISSUE TITLE
add custom macro

### ISSUE THREAD

**Issue by beaumind** [laravel/scout#403]
- Scout Version: 8.0.1
- Laravel Version: 7.8
- PHP Version: 7.4.5

### Description:
I've added new custom macro like this:
      `Builder::macro('searchNested', function (array $nested) {
                $this->nested = $nested;
                return $this;
            `}`
        );`

but in the custom scout engine when I'm trying to access this property `$builder->nested` I'm getting this error:
`Undefined property: Laravel\Scout\Builder::$nested `

**Comment by driesvints** [comment]
You're trying to access a property that doesn't exists. The macros are meant to add behavior but you can't add properties through them.

**Comment by beaumind** [comment]
@driesvints how can I add these kind of functionalities to builder? any suggestion?
