### ISSUE TITLE
Unable to install Scout on Laravel 5.8

### ISSUE THREAD

**Issue by sunnythewebdeveloper** [laravel/scout#410]
I am unable to install Scout on Laravel 5.8 due to requirements not being resolved to an installable set of packages.
Any suggestions ?

`sudo composer require laravel/scout
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^8.0 for laravel/scout                                                
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                     
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.38
    - Conclusion: don't install laravel/framework v5.8.38
    - laravel/scout v8.0.0 requires illuminate/pagination ^6.0|^7.0 -> satisfiable by illuminate/pagination[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel/scout v8.0.1 requires illuminate/pagination ^6.0|^7.0 -> satisfiable by illuminate/pagination[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/pagination v6.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.10.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.11.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.12.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.13.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.13.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.14.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.15.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.15.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.16.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.17.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.17.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.10|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.11|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.12|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.13|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.14|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.15|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.16|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.17|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.18|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.19|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.20|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.21|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.22|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.23|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.24|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.25|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.3|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.4|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.5|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.6|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.7|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.8|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.18.9|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.4.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.5.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.5.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.6.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.6.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v6.8.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.5|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.6|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.7|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.0.8|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.1.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.1.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.1.3|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.10.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.10.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.10.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.10.3|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.11.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.12.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.13.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.14.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.14.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.15.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.16.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.16.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.17.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.17.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.17.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.18.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.19.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.19.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.2.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.2.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.4.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.5.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.5.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.6.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.6.2|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.7.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.8.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.8.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.9.0|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.9.1|don't install laravel/framework v5.8.38
    - don't install illuminate/pagination v7.9.2|don't install laravel/framework v5.8.38
    - Installation request for laravel/framework (locked at v5.8.38, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.38].
    - Installation request for laravel/scout ^8.0 -> satisfiable by laravel/scout[v8.0.0, v8.0.1].

Installation failed, reverting ./composer.json to its original content.`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by sunnythewebdeveloper** [comment]
Hi,

Thanks for reply
