### ISSUE TITLE
[8.2.0] EngineManager - Undefined variable: user 

### ISSUE THREAD

**Issue by MikeElghali** [laravel/scout#412]
- Scout Version: 8.2.0
- Laravel Version: 7.23.0
- PHP Version: 7.4.8
- Database Driver & Version: MySQL 8.0.21

### Description:

When i try the new feature "Identifying Users" i have a php syntax error "Undefined variable: user".

<img width="1282" alt="Capture d’écran 2020-08-06 à 12 46 35" src="https://user-images.githubusercontent.com/2301050/89523304-edc65400-d7e2-11ea-93fa-058d87ae3ee0.png">

### Steps To Reproduce:

1. Set in .env file `SCOUT_IDENTIFY=true`
2. Search something
3. The error appear

**Comment by driesvints** [comment]
Urgh, fixing.

**Comment by driesvints** [comment]
Fixed. Thanks!
