### ISSUE TITLE
The searchable scope does not work with the hasManyThrough relation

### ISSUE THREAD

**Issue by ebrigham1** [laravel/scout#414]
- Scout Version: 8.2.1
- Laravel Version: 7.25.0
- PHP Version: 7.4.9
- Database Driver & Version: 8.0.21

### Description:
The laravel scout [searchable/unsearchable scopes](https://github.com/laravel/scout/blob/060bd8f57cb6ee377af7d352e23967d1ebd162b1/src/SearchableScope.php#L33-L48) does not work with the `hasManyThrough` relation. This is because `hasManyThrough` requires special handling for `chunkById` which the searchable scope uses as part of its builder macro. However since the searchable scope is added as a builder macro the relation actually just forwards the `searchable` function call onto the eloquent builder which does not use the relation's `chunkById` function. This causes an error similar to the following:

```
Illuminate/Database/QueryException with message 'SQLSTATE[23000]: Integrity constraint violation:
1052 Column 'id' in order clause is ambiguous
(SQL: select * from `posts` inner join `users` on `users`.`id` = `posts`.`user_id` where `users`.`country_id` = 3
order by `id` asc limit 500)'
```

You can see this is happening because it is not using the special [chunkById](https://github.com/laravel/framework/blob/7161c83d4f4a28300eb5d1e739c25e3fd7ec5deb/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L465-L481) function for that relation which uses the qualified key name.

### Steps To Reproduce:

1. Create a `hasManyThrough` relation such as countries -> users -> posts.
3. Make posts searchable using the trait and adding an index for it.
4. From the country object try to re-index/de-index associated posts with the searchable/unsearchable scope `$country->posts()->searchable()`/`$country->posts()->unsearchable()`

### Possible Solution:

I believe this could be fixed by simply adding a relation macro (pretty much exactly the same as the builder macro already in use) to the scout service providers boot method, but I'm unsure if this is the best approach.

```php
public function boot()
{
    Relation::macro('searchable', function ($chunk = null) {
        $this->chunkById($chunk ?: config('scout.chunk.searchable', 500), function ($models) {
            $models->filter->shouldBeSearchable()->searchable();

            event(new ModelsImported($models));
        });
    });

    Relation::macro('unsearchable', function ($chunk = null) {
        $this->chunkById($chunk ?: config('scout.chunk.searchable', 500), function ($models) {
            $models->filter->shouldBeSearchable()->searchable();

            event(new ModelsImported($models));
        });
    });
}
```

This would cause the searchable call to not be forwarded to the eloquent query builder, but instead be called directly from the relation class so that it can use the `chunkById` method off of the `hasManyThrough` relation.

I'm happy to put in a pull request for this if this is an approach you would be happy with or if you can give some guidance I'm happy to try working through a different approach.

Thanks

**Comment by driesvints** [comment]
@ebrigham1 can you maybe whip up a test repo for me to reproduce this? I'll try to debug from there and see if I can fix this. Please commit your custom changes separately from the base skeleton.

**Comment by ebrigham1** [comment]
@driesvints thanks for looking into this, I appreciate it. I've created a repository with a [pull request](https://github.com/ebrigham1/scout_bug/pull/1) with all changes on top of the base laravel + scout skeleton code.

I used laradock + elasticsearch to get a quick working example, but if you aren't using laradock and elasticsearch to reproduce you can probably look exclusivly at this [commit](https://github.com/ebrigham1/scout_bug/pull/1/commits/d6a568bea16e744c20249bbd97169c9dac7f6d16).

The easiest way to reproduce once you have your environment setup would be to run `php artisan migrate:fresh --seed` followed by `php artisan tinker` and then once in the tinker shell you can run commands like the following:

```php
// This will work showing that its not the relationship that is messed up
Country::whereHas('posts')->first()->posts()->first();

// These will not work again because chunkById is using the base builder version
Country::whereHas('posts')->first()->posts()->searchable();
Country::whereHas('posts')->first()->posts()->unsearchable();
```
Please let me know if you need any more information to reproduce this or if I can do anything to help.

**Comment by driesvints** [comment]
I've sent in a PR for this: https://github.com/laravel/scout/pull/416

Thanks for reporting this 👍

**Comment by ebrigham1** [comment]
That looks like it should work to me, thanks @driesvints!
