### ISSUE TITLE
Restrict Indexing to a Subset of Your Data?

### ISSUE THREAD

**Issue by dennisoderwald** [laravel/scout#42]
I think Scout needs a function to select which entries are indexed. The implementation of Algolia's Laravel Plugin has an `indexOnly()` function.

https://github.com/algolia/algoliasearch-laravel#restrict-indexing-to-a-subset-of-your-data

**Comment by pvanhemmen** [comment]
You can set the `hidden` property on the model for all fields that should not be indexed. At least this works for me in combination with the elasticsearch driver. All hidden fields will not be converted to JSON or arrays and thus not be pushed to the index. The `visible`property should work as well, but I haven't tested it yet.

https://laravel.com/docs/5.3/eloquent-serialization#hiding-attributes-from-json

**Comment by driesvints** [comment]
You can use the `toSearchableArray` method.
