### ISSUE TITLE
Scout Import Descending

### ISSUE THREAD

**Issue by Sladewill** [laravel/scout#423]
On the import command there doesn't appear to be an option to order the results:

https://github.com/laravel/scout/blob/8.x/src/Console/ImportCommand.php
https://github.com/laravel/scout/blob/8.x/src/Searchable.php#L119

For certain search engines the document ids match exactly the model id, in these instances the more recent data is more relevant to import to give a smoother transition. Would it be possible to make to order ascending by default as to not affect existing setups but have an option like --sort-by=desc.

**Comment by driesvints** [comment]
Feel free to send in a PR 👍
