### ISSUE TITLE
Undefined class constant 'VERSION'

### ISSUE THREAD

**Issue by leonardonadin** [laravel/scout#426]
- Scout Version: 2.2.0
- Laravel Version: v7.29.3
- PHP Version: 7.3.18
- Database Driver & Version: MySQL 8.0.16

- guzzlehttp/guzzle: 7.2.0

### Description:
Error:
Undefined class constant 'VERSION'
/vendor/algolia/algoliasearch-client-php/src/Support/UserAgent.php in Algolia\AlgoliaSearch\Support\UserAgent::getDefaultSegments at line 50

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md
Constant GuzzleHttp\ClientInterface::VERSION is removed. Added GuzzleHttp\ClientInterface::MAJOR_VERSION instead.

### Steps To Reproduce:
Update Guzzle

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
