### ISSUE TITLE
Id is a must for toSearchableArray

### ISSUE THREAD

**Issue by actuallymab** [laravel/scout#43]
If anyone approves me, I may send a PR on this. When I modify `toSearchableArray` method in model classes, if I do not put id to returned array it returns me an exception: `undefined index id at  AlgoliaEngine.php line 134`

**Comment by nowned** [comment]
Definitely send in a PR on this, had `id` in my `$hidden` array and it caused me a lot of confusion what was breaking

**Comment by EdwardNelson** [comment]
How would you tackle this? toSearchableArray() is used throughout the code base. Maybe this is something to PR the docs for. Any suggestions?

**Comment by mpash** [comment]
@EdwardNelson Laravel has an array helper function [`array_only()`](https://laravel.com/docs/5.3/helpers#method-array-only). You'll need to include whatever the `id` column is on your table structure in every one of your `toSearchableArray()` calls, like I've done here.
```
public function toSearchableArray()
    {
        return array_only($this->toArray(), ['id', 'name', 'title']);
    }
```

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
