### ISSUE TITLE
not support php8. in laravel has, but in scout no

### ISSUE THREAD

**Issue by simonproud** [laravel/scout#431]

**Comment by freekmurze** [comment]
Probably PHP 8 support isn't here yet because the underlying Algolia dependency doesn't have PHP 8 support.

We need to have a little more patient. Pretty share that, when Algolia adds PHP 8 support for this package, Scout will soon have a PHP 8 compatible release 👍

**Comment by driesvints** [comment]
Please see https://github.com/laravel/scout/pull/425
