### ISSUE TITLE
Cannot call any model method from toSearchableArray()

### ISSUE THREAD

**Issue by goddas** [laravel/scout#433]
- Scout Version: 8.4
- Laravel Version: 8.12.3
- PHP Version: 7.4
- Database Driver & Version: mariaDB

### Description:
```
public function toSearchableArray()
    {
        $data = [
            'excerpt' => $this->excerpt() //string
        ];

        return $this->transform($data);
    }
```
Calling artisan scout:reimport/import, the job will fail with `App\Page::excerpt must return a relationship instance.` 
I'm using queues (db driver). Why can't I call any model methods here?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
