### ISSUE TITLE
Undefined property: Laravel\Scout\Builder::$engine when using macro example

### ISSUE THREAD

**Issue by francoism90** [laravel/scout#435]
- Scout Version: 8.5.0
- Laravel Version: 8.12
- PHP Version: 7.4.13
- Database Driver & Version: MariaDB

### Description:

https://laravel.com/docs/8.x/scout#builder-macros

### Steps To Reproduce:

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Laravel\Scout\Builder;

class ScoutServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        Builder::macro('count', function () {
            return $this->engine->getTotalCount(
                $this->engine()->search($this)
            );
        });
    }
}
```

Registed in `app.php`:
```[2020-12-14 18:40:15] local.ERROR: Undefined property: Laravel\Scout\Builder::$engine {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: Laravel\\Scout\\Builder::$engine at /srv/http/project/api/app/Providers/ScoutServiceProvider.php:28)```

**Comment by driesvints** [comment]
There's a typo. The `$this->engine->getTotalCount(` needs to be `$this->engine()->getTotalCount(`. I'll fix this, thanks.
