### ISSUE TITLE
unsearchable() not removing model from index

### ISSUE THREAD

**Issue by chrisgrim** [laravel/scout#444]
Software | Version
-- | --
PHP | 7.4.7
Elasticsearch | 7.3.2
Laravel | 8.15.0
Laravel Scout | 8.5.0
Mysql | 8.0.22

### Description:
unsearchable() does not remove model from index

### Steps To Reproduce:
In my event when an event is published I change the status to 'p', In my event model I have
```
public function shouldBeSearchable()
    {
        return $this->status === 'p';
    }
```
This works great but now I am running into an issue. After an event has been published if I go back to the event and decide I want to embargo it (publish it at a certain time in the future) I update the event status to 'e' and add an embargo date. I just discovered however that after updating the event it still remains in my index and searchable.
I went and looked at the laravel scout documentation and they have unsearchable(). So now I tried
```
$event->update([
                'show_times' => $request->showtimes,
                'embargo_date' => $request->embargo_date,
                'closingDate' => $lastDate,
                'showtype' => $type,
                'timezone_id' => $request->timezone ? $request->timezone['id'] : null,
                'status' => 'e'
            ]);
            return $event->unsearchable();
```
However this still doesn't remove the event from the index.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
