### ISSUE TITLE
There is no need to delete data on creating

### ISSUE THREAD

**Issue by uyson** [laravel/scout#445]
I think where not need to delete from es on creating,  because there no data to delete .
https://github.com/laravel/scout/blob/54070f7b68fed15f25e61e68884c4110496b8aa1/src/ModelObserver.php#L82

**Comment by driesvints** [comment]
This method is for both creating and updating.

**Comment by driesvints** [comment]
Also: please try asking these questions on a support channel first and not use the issue tracker for this. Thanks

**Comment by uyson** [comment]
yes, it's fire on deleting and updating, but search engine not data to delete. why we send to delete action to search engine?

**Comment by uyson** [comment]
> Also: please try asking these questions on a support channel first and not use the issue tracker for this. Thanks

thanks to reply

**Comment by driesvints** [comment]
Feel free to attempt a PR if you want to change anything here 👍
