### ISSUE TITLE
scout:import will fail when chunkById is called with a `Ambiguous column` error  if you join another table

### ISSUE THREAD

**Issue by jrgns** [laravel/scout#447]
Steps to replicate:

1. Have a model with more than 500 records and uses `id` as it's primary key.
2. In your `makeAllSearchableUsing` function in the model join on another table that also has an `id` field.
3. Run `scout:import`

This will result in `SQLSTATE[42702]: Ambiguous column: 7 ERROR:  column reference \"id\" is ambiguous` after the first batch has been processed.

This can be fixed by specifying the table and column names as additional parameters in the chunkById method - https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Builder.html#method_chunkById

**Comment by driesvints** [comment]
Please re-open this with a filled out issue template.

**Comment by jrgns** [comment]
See ##448
