### ISSUE TITLE
scout:import will fail when chunkById is called with a `Ambiguous column` error if you join another table

### ISSUE THREAD

**Issue by jrgns** [laravel/scout#448]
- Scout Version: 8.6.0
- Laravel Version:7.3.40
- PHP Version: 7.4.11
- Database Driver & Version: Postgres 9.5

### Description:

scout:import will fail with an `Ambiguous column` error when if your import query contains more than one table (by using a join). It fails only *after* the first batch has been processed, so when chunkById is called. 

The following error is raised:

```
SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference \"id\" is ambiguous
```

### Steps To Reproduce:

1. Have a model with more than 500 records and uses id as it's primary key. Alternatively ensure that the `scout.chunk.searchable` setting is set to less than the number of records returned by the searchable query.
2. In your `makeAllSearchableUsing` function in the model join on another table that also has an id field.
3. Run scout:import
4. The error will occur AFTER the first batch has been processed.

Example `makeAllSearchableUsing`

```php
    public function makeAllSearchableUsing($query)
    {
        return $query->with('roles');
    }
```

This can be fixed by specifying the table and column names as additional parameters in the chunkById method - https://laravel.com/api/7.x/Illuminate/Database/Eloquent/Builder.html#method_chunkById

**Comment by driesvints** [comment]
Can you maybe whip up a quick app for us to reproduce the problem? Please make a second commit with your custom changes apart from the app skeleton.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
