### ISSUE TITLE
Integrate MeiliSearch, an open-source search engine

### ISSUE THREAD

**Issue by curquiza** [laravel/scout#454]
Hello there! 👋

Thanks for this awesome tool!

I work for [MeiliSearch](https://github.com/meilisearch/MeiliSearch), we are building an open-source and easy-to-use search engine. We provide (thanks to @shokme who is one of our best contributors) a Laravel Scout extension for MeiliSearch. This integration is currently our most used integration: most of our users enjoy the MeiliSearch experience with `meilisearch-laravel-scout`.

Our laravel-scout integration -> https://github.com/meilisearch/meilisearch-laravel-scout
The official MeiliSearch documentation -> https://docs.meilisearch.com/

The `meilisearch-laravel-scout` integration has been built to be totally compliant with `laravel/scout` without any addition. See the `Engine.php` file ->https://github.com/meilisearch/meilisearch-laravel-scout/blob/main/src/Engines/MeilisearchEngine.php

We wanted to know if it would be possible to **integrate MeiliSearch the same way Algolia is integrated** 😁

FYI, if you agree with this integration, another one of our best contributors (@mmachatschek) has already started the work to integrate MeiliSearch (https://github.com/mmachatschek/scout/tree/add_meilisearch_support).
Of course, we would totally understand if it's not possible for you to integrate us!
Sorry if it's not the right place for this kind of request.

Thanks for your time 🙂

PS: @shokme or @mmachatschek, feel free to comment on this issue if you want to add something about what you built 🙂

**Comment by taylorotwell** [comment]
Hello! Can you PR it to see how much code it would be? We don't want to take on any extra maintenance burden so we would need some commitment that MeiliSearch will be able to maintain this even if it is integrated into Scout by making all future maintenance PRs, etc.

**Comment by mmachatschek** [comment]
@taylorotwell 
I can't speak for the MeiliSearch-Team but offering an out-of-the-box implementation for an engine that at least works mostly like algolia (and is open source) would be very beneficial.

On the maintenance side I would definitly be open for help, either with PRs and upcoming issues. (I'm already helping on the MeiliSearch repo)

The team around MeiliSearch and espacially @curquiza are very fast with responses to questions and PRs.

**Comment by curquiza** [comment]
Thanks @mmachatschek for having opened the PR #455!! 

@taylorotwell, thank you for your quick answer! Yes, of course, the integration team of MeiliSearch will be available to maintain and answer questions of the users!
You can ping me when needed, I watch this repo for "participating and mention" and I regularly check my GitHub notification! You can count on the MeiliSearch team to be available!

**Comment by taylorotwell** [comment]
Thanks for the responses. Will continue discussion as needed on the PR.
