### ISSUE TITLE
Paginator never has more

### ISSUE THREAD

**Issue by sudomabider** [laravel/scout#46]
In `Builder::paginate`
```
$results = Collection::make($engine->map(
    $rawResults = $engine->paginate($this, $perPage, $page), $this->model
));
```
`$results` is always the same count as `$perPage` therefore

```
->hasMorePagesWhen(($results->count() / $perPage) > $page)
```
always returns `false`.

Potentially why this is happening?

__Edit:__ 
```
$engine->paginate($this, $perPage, $page)
```
does return the total number of hits in the array. Perhaps we should use this to determine whether there's more?

__Edit2:__

This works fine:
```
->hasMorePagesWhen(($rawResults['nbHits'] / $perPage) > $page);
```

Since we have access to the total number of hits we could easily add a `LengthAwarePaginator` which people seem to be wanting. Or we could expose the number of hits and other related stuff so we can build it ourselves.

**Comment by Skysplit** [comment]
This is probably fixed

**Comment by sudomabider** [comment]
Can confirm it's fixed. Probably will be released soon. Closing. Thanks!

**Comment by sudomabider** [comment]
This is probably closed too soon...reopening so others can see.
