### ISSUE TITLE
Performance issue with relations and queue

### ISSUE THREAD

**Issue by ybert** [laravel/scout#462]
- Scout Version: 8.6.1
- Laravel Version: 6.20.8
- PHP Version: 7.3
- Database Driver & Version: Algolia

### Description:

I have a Book model with categories and author relations.
In Book model  I have : 
```
    protected function makeAllSearchableUsing($query)
    {
        return $query->with(['author', 'categories']);
    }

    public function toSearchableArray()
    {
        return [
            'author_name' => $this->author->name,
            'category_name' => $this->categories->first()->title
        ];
    }
```
I import data massively with php artisan scout:import . I have 20 millions of records.
I use a chunk of 500. In my mind, it should do 3 sql queries per 500 records in queue. One each for books, author and categories.

I noticed it is very slow. 
In fact when I pay attention on what sql queries executed, I saw that relations are not loaded when I used them in toSearchableArray method. So it does 2 additionnal queries by book record. 

I think the problem is relations are not loaded when the queue is executed. I checked data in queue, and it contains relations. But when I dump unserialized data from the queue, relations disappears.

**Comment by mmachatschek** [comment]
This is actually a problem of the ´SerializesModels´ trait that is not able to restore the relations of a Eloquent Collection.

I already PR'd this here https://github.com/laravel/framework/pull/36712 but unfortunatly this was closed.

Maybe this is a good usecase to fix the issue with that trait with this example.

**Comment by driesvints** [comment]
It's not wanted to load all of those relationships again after deserializing. That can cause some serious overload issues when you're handling lots and lots of relationships.

Instead, rethink your DB model and work towards something that doesn't requires you to load all of those relationships into memory.

**Comment by ybert** [comment]
@driesvints So, what the makeAllSearchableUsing function is for ?

I think it is made for that. If I don't want relations to be loaded, I just don't overwrite this function.

**Comment by ybert** [comment]
So actually, it is impossible to use scout if we want to import data from one relation as it will do one db query for each row. 
Is it really as it should work ?

So a schema with simple Product/Category or Book/Author is unusable with scout ?

@mmachatschek @driesvints Am I right ?
@taylorotwell What do you think ?
