### ISSUE TITLE
How to deploy and use laravel-scout and Meilisearch to ec2 instance

### ISSUE THREAD

**Issue by madhavanswami** [laravel/scout#467]
I am new to laravel and meilisearch. I know how to deploy meilisearch alone on ec2 but now i want to use laravel with meilisearch.
i am not able to understand how to get the usecase running. Someone please help me.
Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
