### ISSUE TITLE
Option to set `MakeSearchable`'s retries and backoff

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/scout#474]
Every day a few exceptions are thrown in my application because of connection issues with Algolia, reported about it [here](https://github.com/laravel/scout/issues/427).
I think the option to increase the number of retries and backoff could eliminate these connection issues with Algolia, and make Scout more configurable and flexible for its users.

**Comment by driesvints** [comment]
From what I read, this should be done automatically by the client so I don't think there's anything we can do in Scout? 

https://www.algolia.com/doc/api-client/methods/advanced/#retry-logic

/cc @julienbourdeau

**Comment by MatanYadaev** [comment]
@driesvints I'm talking about being able to add `$retries` and `$backoff` properties to `MakeSearchable` job.

**Comment by driesvints** [comment]
@MatanYadaev talked this over with the team. Feel free to attempt a PR, thanks.
