### ISSUE TITLE
Cursor Pagination in Scout

### ISSUE THREAD

**Issue by WiGeeky** [laravel/scout#475]
Hello,
Since Cursor pagination has been added to the Laravel framework recently (https://github.com/laravel/framework/pull/37216), I was wondering whether this can be implemented for Scout as well?

**Comment by driesvints** [comment]
Not sure if this is needed in scout? How would you use this?

**Comment by crynobone** [comment]
Scout map the results using relevant based on keyword, where cursor pagination focus on attribute > lastId such as:

```sql
select * from users where id > 15 order by id asc limit 15;
```

**Comment by driesvints** [comment]
Right. Don't think this is needed in Scout.
