### ISSUE TITLE
Indirect modification of overloaded property  has no effect

### ISSUE THREAD

**Issue by NatBLida68** [laravel/scout#478]
i'm not sure is it right to ask  here but this is my issue 

my job model  toSearchableArray is 

    public function toSearchableArray()
    {
        $array = $this->searchableArray(); //common columns 
        $array['id'] = 'j'.$this->id;
        $array['party_name']= isFilled($this->customer)?$this->customer->name:'';
        $array['party_code']= isFilled($this->customer)?$this->customer->id:'';
        return $array;
    }

customer is a relation that this   job belongsTo  customer 
so when i import data using scout import 
this two lines throws error 
$array['party_name']= isFilled($this->customer)?$this->customer->name:'';
        $array['party_code']= isFilled($this->customer)?$this->customer->id:'';

 Indirect modification of overloaded property App\Model\Job\Job::$customer has no effect

clearly i'm not  trying to modify customer relation anywhere just picking name and its id for  my array 
+ with the same code i can save,edit,update,delete job and its doesn't throws any error 
only the import is throwing such an error
(using scout v9 with meilisearch)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
