### ISSUE TITLE
Batching (mainly for MeiliSearch)

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/scout#487]
Hi!

I propose a feature for MeiliSearch that would allow for batching of `->searchable()` and `->unsearchable()` queries.

The issue is that MeiliSearch is not equipped to handle hundreds of single item updates (they'll block the indexing queue for a long time). It's **much** faster for MeiliSearch to handle one update request with 100 items than 100 requests with one item.

So, I would like to bring up discussion regarding a feature that would batch the update requests into one. My first idea was something along the lines of:

* Have a configurable `batch_updates` configuration option, which would be disabled if the value is `0`, `1` or an invalid number. It would be enabled if the user configures a number there (ie `100`).
* Scout would then continuously store updated item ID-s (in `->searchable()` and `->unsearchable()` calls) until:
  a) The number of IDs reaches `100`.
  b) Updates stop coming in for `n` number of seconds (I was thinking 60 or 90, it's essentially a debounce).
* Then it would send out the update to the search engine driver.

This doesn't have to be solved through a configuration option, there could also be a separate `BatchedSearchable` trait that would handle this.

Is this something that would fit into Laravel Scout or this something the `meilisearch-php` driver should handle?

Thanks for hearing me out!

**Comment by driesvints** [comment]
I think in this case it's best that you send in a PR so we can look at the actual code needed to make this happen. Then we can decide if we want to merge it in. Thanks!
