### ISSUE TITLE
Queue executes jobs if the SCOUT_DRIVER was set to null

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/scout#495]
- Scout Version: 9.2.1
- Scout Driver: MeiliSearch
- Laravel Version: 8.49.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL

### Description:

HI all.

I'm trying to integrate scout to mine project and want to disable scout for local and stage env using `SCOUT_DRIVE=null` but found that the scout still executes queue jobs.

### Steps To Reproduce:
1. set `SCOUT_DRIVE=null`
2. set `'after_commit' => true` in `scout.php` config
3. run queue
4. do any operation for `Searchable` model 

We can see that the queue executes jobs from scout, I guess it's a dummy jobs, but these are unnecessary operations for this. 

Is this the expected behavior?

**Comment by driesvints** [comment]
It's `SCOUT_DRIVER`, not `SCOUT_DRIVE`.

**Comment by siarheipashkevich** [comment]
> It's `SCOUT_DRIVER`, not `SCOUT_DRIVE`.

sorry, I made a typo in description

**Comment by siarheipashkevich** [comment]
@driesvints should I open new issue with fixed typo?

**Comment by driesvints** [comment]
The current behavior is expected. The queued jobs are still fired but Scout isn't indexing anything.

**Comment by siarheipashkevich** [comment]
Got it, thanks
