### ISSUE TITLE
Add an ability to retrieve hit metadata for MeiliSearch like for Algolia for model instances

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/scout#496]
Hi all.

What do you think about an ability for retrieving hit metadata for MeiliSearch from response like for Algolia [Retrieve hit metadata](https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?client=php#retrieve-hit-metadata)?

It is needed for retrieving the result of the search from MeiliSearch as [Attributes to highlight](https://docs.meilisearch.com/reference/features/search_parameters.html#attributes-to-highlight) or something else for instances of the searchable models.

Currently we need to manually write this logic:
1. get raw search results from MeiliSearch
2. get models by ids from search result from db
3. map needed properties from search result (for highlight attributes we have `_formatted` property in raw data) to our instances

Thanks.

**Comment by driesvints** [comment]
Yes, that sounds reasonable. Feel free to attempt a PR.
