### ISSUE TITLE
Change Default Chunk Size

### ISSUE THREAD

**Issue by stevebeyatte** [laravel/scout#499]
I was indexing 8,000,000 records via MeiliSearch on an AWS machine with 32GB memory, 4 CPUs, and 200GB storage. Every time I imported them to the machine, it was agonizingly slow- meaning the estimated time of completion was 1 week. 

It took me a week to realize the default Scout chunk size is 500. I changed it to 10,000 and 8MM records indexed in less than an hour.

I'm not sure if changing the default chunk size is reasonable but for MeiliSearch, you will not index more than 100K records with a chunk size of 500. It will break, 100% of the time and this is confirmed by their devs.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
