### ISSUE TITLE
Elasticsearch Support

### ISSUE THREAD

**Issue by hernandev** [laravel/scout#5]
hi @taylorotwell, I've been using Elasticsearch over the past year with Laravel, and i'm halfway building it's engine for scout, just given a heads up in case you don't want Elastic support direct here. that case I'm gonna build it as a separate package based on scout instead.

Thanks

**Comment by iolson** [comment]
Will this support Elasticsearch on AWS as well as self hosted versions? I was using a package but it didn't support AWS Elasticsearch

**Comment by hernandev** [comment]
Using the official PHP Client complatible with multiple elasticsearch versions, as well, i'm adding support for multihost elastic cluster, should be compatible with Amazon, but we can try making it flexible if the differences are too big. @iolson you can help me with the testing there afterwards

**Comment by hernandev** [comment]
Initial PR sent, some improvements on the way, including tests.

https://github.com/laravel/scout/pull/6

@taylorotwell give some insight if I should or not continue to work on this.

**Comment by dwightwatson** [comment]
Taylor did welcome community contribution of Elasticsearch support in his Laracon talk. Happy to help test with standalone/AWS Elasticsearch if you need.

**Comment by hernandev** [comment]
Great @dwightwatson the origianl PR was closed and opened again at https://github.com/laravel/scout/pull/7, any help testing would be appreciated

**Comment by hernandev** [comment]
people can contribute on the merged code and discuss it specificly, closing it
