### ISSUE TITLE
queued searches don't obey makeAllSearchableUsing()

### ISSUE THREAD

**Issue by jayenne** [laravel/scout#500]
- Scout Version: latest
- Scout Driver: MeiliSearch
- Laravel Version: 8.50.0
- PHP Version: 8.0.0
- Database Driver & Version: MariaDB latest

### Description:
queued searches don't obey makeAllSearchableUsing()

### Steps To Reproduce:
create & spin up a new laravel with scout (any driver)
set .env `SCOUT_QUEUE=false`
create and seed two models (ModelA & ModelB), one with a relationship between them.
add fn to ModelA
```
protected function makeAllSearchableUsing($query)
{
     return $query->with('ModelB');
}
```
add `\App\Models\ModelA::preventLazyLoading(! app()->isProduction());` to `AppServiceProvider`

from the console...
run composer dumpautoload
run scout:import "App\Models\ModelA"

*notice how the import works fine & search db is popluated as expected

set .env `SCOUT_QUEUE=true`
*notice how console reports no issues but also how the queue fails with `Illuminate\Database\LazyLoadingViolationException: Attempted to lazy load ... but lazy loading is disabled`

**Comment by jayenne** [comment]
I've seen some chatter on queued job not getting a model's relationships which would explain this but it then does this then make `makeAllSearchesUsing()` poinless when using `SCOUT_QUEUE=true`? or just in conjunction with scout:import?
- either way, maybe this should be clarified in the documentation too?

I'd like to know if I can use scout queue and `with` if anyone has a way of doing this?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
