### ISSUE TITLE
Manual Indexing

### ISSUE THREAD

**Issue by Stevemoretz** [laravel/scout#502]
Hi I don't know if this is already possible or not, I couldn't find a question template or a discussion section so here I am.

I normally use laravel and WordPress togheter, I want to know if there is a way that instead of what update and create is doing automatically right now, if I could do it myself somehow. 

The entries are made in WordPress so no create or update happens for me, however I can write an api that would let me know that ID 48 is created just now, or ID 48 is been edited and now if I could do what create and update does I'd have no problem.

Thanks for reading this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
