### ISSUE TITLE
where() clauses don't work with new MeiliSearch version

### ISSUE THREAD

**Issue by mechelon** [laravel/scout#504]
- Scout Version: v9.2.3
- Scout Driver: MeiliSearch 
- MeiliSearch Version v0.21.0 via takeout on Docker
- Laravel Version: 8.50.0
- PHP Version: 8.0.7
- Database Driver & Version: 10.5.5-MariaDB Homebrew

### Description:
It seems that the parameter name for `filters` in the MeiliSearch API has changed to `filter` (singular!) and the Scout package needs to be adjusted.

### Steps To Reproduce:
- Write a search query with `->where()` condition

e.g.:
```
$query = ProductVariant::search($query)
            ->where('daily_monitoring', 1)
            ->where('status', 1)
            ->get();
```
(`status` and `daily_monitoring` are both set up as filterable attributes correct)

Error:
```
local.ERROR: Json deserialize error: unknown field `filters`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `facetsDistribution` at line 1 column 22 {"userId":89,"exception":"[object] (MeiliSearch\\Exceptions\\ApiException(code: 400): Json deserialize error: unknown field `filters`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `facetsDistribution` at line 1 column 22 at /Users/dianascharf/Dev/greenzero-platform/vendor/meilisearch/meilisearch-php/src/Http/Client.php:197)
```

I could narrow down the error to these to lines in this file:
https://github.com/laravel/scout/blob/9.x/src/Engines/MeiliSearchEngine.php#L97
https://github.com/laravel/scout/blob/9.x/src/Engines/MeiliSearchEngine.php#L112

I changed 'filters' to 'filter' locally and it works perfectly fine. 

It seems like a very recent change to me because the filter example in the docs of the meilisearch-php package is also wrong.

I thought about opening a PR myself, but I assume that this would break earlier versions of MeiliSearch, so what's the proper way to handle this?

**Comment by curquiza** [comment]
Hello @mechelon, you are using a RC (release candidate) of MeiliSearch -> the v0.21.0 is not out yet so the MeiliSearch integrations are not compatible at the moment. An update of the [`meilisearch-php`](https://github.com/laravel/scout/blob/167752d6f8e7a1d4d5a8415c44b60371e9324779/composer.json#L54) will be necessary once the new version is out. You can follow this repository to know when you can update it -> https://github.com/meilisearch/meilisearch-php

The latest available version of MeiliSearch is v0.20.0, see: https://github.com/meilisearch/MeiliSearch/releases

**Comment by driesvints** [comment]
Thanks @curquiza

**Comment by driesvints** [comment]
Thanks for reporting @mechelon. As @curquiza says, this should be available out of the box when the newer SDK version is released.

**Comment by mechelon** [comment]
Okay, thank you! Didn't notice that takeout installs the release candidate as a default.
