### ISSUE TITLE
map function from MeiliSearchEngine is using getKeyName() instead of getScoutKeyName()

### ISSUE THREAD

**Issue by diogoaguiar** [laravel/scout#506]
- Scout Version: 9.2.5
- Scout Driver: MeiliSearch
- Laravel Version: 8.54.0
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 5.7

### Description:
While using the MeiliSearch driver, and custom model ID set with `getScoutKey()` and `getScoutKeyName()` methods, I was getting no results and the following warning repeatedly, whenever performing a search:

> <warning>PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /var/www/html/vendor/laravel/scout/src/Engines/MeiliSearchEngine.php on line 202</warning>

I checked the specified line and knowticed that at the line 200 the method used to fetch the key's name was the model's deafult `getKeyName()`.
https://github.com/laravel/scout/blob/86c406cc1211237cff29e349851b21121c29d776/src/Engines/MeiliSearchEngine.php#L200 
I changed it to `getScoutKeyName()`, and started getting the expected results and the warning was gone.

### Steps To Reproduce:
1. Set the indexable data for the model with `toSearchableArray()` and exclude the model's primary key;
2. Set a custom primary key using the `getScoutKey()` and `getScoutKeyName()` methods;
3. Import data with `artisan scout:import ...`;
4. Perform a search using `artisan tinker` (Example: `Product::search('Shirt')->get();`)

**Comment by mmachatschek** [comment]
This is kind of a know problem: 

- https://github.com/laravel/scout/pull/484
- https://github.com/laravel/scout/pull/485

Unfortunately changing this would be a breaking change and requires more configuration than just changing geKeyName to getScoutKeyName as pointed out here https://github.com/laravel/scout/pull/484#issuecomment-863189618

**Comment by driesvints** [comment]
see the above. Thanks @mmachatschek

**Comment by diogoaguiar** [comment]
So, for the moment, we can't use getScoutKey() or getScoutKeyName() with MeiliSearch and toSearchableArray() must contain model's primary key. Is this correct?
