### ISSUE TITLE
Got the issue with Invalid URL: scheme is missing

### ISSUE THREAD

**Issue by dungnh** [laravel/scout#517]
### Environment
- OS: MAC Bir Sug
- Laravel run with Valet 2.15.4 with secure
- Scout Version: ^9.2
- Scout Driver: MeiliSearch v0.21.1
- Laravel Version: ^8.14
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 8

### Description:

I have installed the newest MeiliSearch with MAC, Valet and Laravel 8 with Scout. And I got exception when run meilisearch function:

```
Symfony\Component\HttpClient\Psr18RequestException

Invalid URL: scheme is missing in "/indexes/xxxxxx/documents". Did you forget to add "http(s)://"?
```
Please help how can I resolve this issue?

**Comment by driesvints** [comment]
This seems like an issue you should post on the meilisearch issue tracker
