### ISSUE TITLE
Automatically reindexing on save() wont reindex relation

### ISSUE THREAD

**Issue by nezaboravi** [laravel/scout#522]
- Scout Version:  v9.2.8
- Scout Driver: MeiliSearch
- Laravel Version:  8.58.0
- PHP Version: 8.0.9
- Database Driver & Version:  mySql 8.0.25 for macos11.3 on x86_64 (Homebrew)

### Description:
I have a model User, and a model Profile
When I do PHP artisan scout:import, 
this happens:
```php
User.php

  public function getFullNameAttribute(): string
    {
        return ucfirst($this->profile->first_name) . ' ' . ucfirst($this->profile->last_name);
    }
public function toSearchableArray(): array
    {
        $this->load('profile');
        $data = $this->only(['id']);
        $data['name'] = $this->fullName; // see above method how is created 
        $data['email'] = $this->email;
        $data['type'] = $this->profile->type ?? '';
        return $data;
    }

```

User is indexed in meilisearch index.

When I try to change user data, something like:
```php
auth()->user()->profile->first_name = 'John';
auth()->user()->save();
```

The user has been changed in the database, however, meilisearch index is not updated. It will update only when I run scout:import.

Now, in another model, that does not use relation in toSearchableArray,
```php
Product.php
public function toSearchableArray(): array
    {
        $data = $this->only(['id']);
        $data['title'] = $this->title;
        return $data;
    }
```
When I update it:
```php
$product->title = 'John';
$product->save();
```

It gets updated immediately in meilisearch as well.

So it leads me to believe that when relationship model is used in toSearchableArray, index is not updated.

Is this a bug, or I am doing something wrong?

**Comment by mmachatschek** [comment]
Profile is a relation on your Product model, when updating the profile, the Product model isn't touch and therefore no update event is executed that gets picked up by the Scout events. You can "touch" the product model when updating the profile like this https://laravel.com/docs/8.x/eloquent-relationships#touching-parent-timestamps after adding this, model events for the Product model are executed as well.

**Comment by mmachatschek** [comment]
And secondly I think this should be like this with a push instead of a save in order to save the relationships of the User model:

```auth()->user()->profile->first_name = 'John';
auth()->user()->push();
```
In your example, the profile isn't saved to the database, thats also an additonal point why there is no change in the index

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by nezaboravi** [comment]
@driesvints not really, you know, looking at support channels are just a toon of asked questions, no one is replying, or, they do, very very rarely. (on discord at least)

**Comment by nezaboravi** [comment]
> Profile is a relation on your User model, when updating the profile, the Product model isn't touch and therefore no update event is executed that gets picked up by the Scout events.
> 
> You can "touch" the User model when updating the profile like this https://laravel.com/docs/8.x/eloquent-relationships#touching-parent-timestamps after adding this, model events for the User model are executed as well and your index gets updated.

Thank you mate
when you do save() it does touch() parent method and updated updated_at column.
trying to use touch() explicitly, did not work too.
Parent is updated, updated_at is updated, but not index.
I will check user->push. Thank  you kind sir :)
