### ISSUE TITLE
Add support MeiliSearch v0.22.0

### ISSUE THREAD

**Issue by wassim** [laravel/scout#523]
[v0.22.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.22.0) introduces some breaking changes and new features like sorting at query time!
@curquiza

**Comment by driesvints** [comment]
Feel free to send in a pr that's non breaking for the current release.

**Comment by curquiza** [comment]
Hello!
FYI, the sort feature is not breaking 🙂

**Comment by wassim** [comment]
@curquiza

The scout:import fails when I try to update sortable attributes.

```
$url = config('scout.meilisearch.host');
$hit = new Client($url);
$hit->index($this->searchableAs())->updateSortableAttributes(['created_at']);
```

```
MeiliSearch\Exceptions\FailedJsonDecodingException 

Decoding json payload failed: "Syntax error".

at vendor/meilisearch/meilisearch-php/src/Http/Client.php:227
    223▕     {
    224▕         try {
    225▕             $decoded = json_decode($content, true, 512, JSON_THROW_ON_ERROR);
    226▕         } catch (JsonException $e) {
  ➜ 227▕             throw new FailedJsonDecodingException(sprintf('Decoding json payload failed: "%s".', $e->getMessage()), $e->getCode(), $e);
    228▕         }
    229▕ 
    230▕         return $decoded;
    231▕     }
```

**Comment by curquiza** [comment]
What is your version of meilisearch-php? Your version of MeiliSearch?

**Comment by wassim** [comment]
@curquiza meilisearch-php [v0.19.1](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.19.1)

**Comment by curquiza** [comment]
Which version of MeiliSearch do you use?
```bash
curl http://127.0.0.1:7700/version
```
You might want to replace `http://127.0.0.1:7700` by your MeiliSearch server address if you are not working locally

**Comment by wassim** [comment]
@curquiza sorry, forgot to restart the MeilSearch server after upgrade. Thanks for the follow up.
