### ISSUE TITLE
`where()` clauses don't work with latest MeiliSearch version

### ISSUE THREAD

**Issue by Lavendar77** [laravel/scout#527]
- Scout Version: ^9.2
- Scout Driver: MeiliSearch
- Laravel Version: ^8.54
- PHP Version: ^8.0
- MeiliSearch version: 0.22.0

### Description:
It seems that the MeiliSearch server does not allow where clauses on the direct model attributes anymore.

### Steps To Reproduce:
```php
Model::search($keyword)->where('is_active', true)->get();
```

### Error:
```bash
{
    "message": " --> 1:1\n  |\n1 | is_active=\"\"\n  | ^-------^\n  |\n  = attribute `is_active` is not filterable, available filterable attributes are: ",
    "exception": "MeiliSearch\\Exceptions\\ApiException",
    "file": "...vendor/meilisearch/meilisearch-php/src/Http/Client.php",
    "line": 199,
    "trace": [...]
}
```

### I still went further to add, but this does not show the correct result:
```php
Model::search($keyword, function (Indexes $meilisearch, $query, $options) {
    $meilisearch->updateFilterableAttributes([
        'is_active',
     ]);

     return $meilisearch->search($query, $options);
})->where('is_active', true)->get();
```

**Comment by driesvints** [comment]
Ping @curquiza

**Comment by Lavendar77** [comment]
Hello @curquiza 

### Following your reply on:
> Hello @mechelon, you are using a RC (release candidate) of MeiliSearch -> the v0.21.0 is not out yet so the MeiliSearch integrations are not compatible at the moment. An update of the [`meilisearch-php` dependency](https://github.com/laravel/scout/blob/167752d6f8e7a1d4d5a8415c44b60371e9324779/composer.json#L54) will be necessary once the new version is out. You can follow this repository to know when you can update it -> https://github.com/meilisearch/meilisearch-php
> 
> The latest stable version of MeiliSearch that is available is v0.20.0, see: https://github.com/meilisearch/MeiliSearch/releases

### What I did:
I am trying to downgrade now using `brew install meilisearch@0.20.0` and even `brew install meilisearch@v0.20.0`, but does not work. 

### Error
```bash
Warning: No available formula or cask with the name "meilisearch@0.20.0". Did you mean meilisearch?
==> Searching for similarly named formulae...
This similarly named formula was found:
meilisearch ✔
To install it, run:
  brew install meilisearch ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by curquiza** [comment]
Hello @driesvints and @Lavendar77 

The error mentioned your field is not a `filterableAttributes`.

`updateFilterableAttributes` is an asynchronous task and might take time to be applied. It's a setting.
You should apply this setting change once only, and before doing any search, so not in the `Model::search()` callback.
Here are the docs, only options should be passed: https://laravel.com/docs/8.x/scout#customizing-engine-searches

**Comment by driesvints** [comment]
Thanks @curquiza

**Comment by StubyProjects** [comment]
Would be cool if we could add a $filterableAttributes Array to the eloquent model, so you wont have to update the filterable settings everytime we need to call where on a scout search query

**Comment by curquiza** [comment]
It cannot be automatic because it would drastically impact the performance during the search but also the size of the DB on the disk if Meilisearch would add each field as filterable 🙂
However
- if you have any feature requests regarding Meilisearch, you can ask them here: https://github.com/meilisearch/product/
- if you have any questions regarding the Meilisearch core engine in general: https://github.com/meilisearch/meilisearch/discussions
