### ISSUE TITLE
support operators in filter

### ISSUE THREAD

**Issue by G3z** [laravel/scout#529]
Both algolia and meilisearch supports operatators other than `=` when using filters

` <, <=, =, !=, >=, > ` are available for both engine

[Algolia docs](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-numeric-value/#applying-a-numeric-filter)
[MeiliSearch docs](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#using-filters)

is it possible to support this ?

from what i understand:
`Laravel\Scout\Builder::where` has to accept 3 parameters instead of 2
and
`Laravel\Scout\Engines\AlgoliaEngine::filters` and `Laravel\Scout\Engines\MeiliSearchEngine::filters` to apply the operator

if you agree I can prepare a PR

**Comment by driesvints** [comment]
Yeah that sounds interesting, definitely. Probably best to send to master for breaking changes. If you can and preserve the current behavior as much as possible to minimize the breaking changes that'd be great. Thanks!
