### ISSUE TITLE
paginateRaw() results array is incorrect

### ISSUE THREAD

**Issue by patlamontagne** [laravel/scout#530]
- Scout Version: ^9.2
- Laravel Version: ^8.60
- PHP Version: ^8.0
- Scout Driver: MeiliSearch 
- Meilisearch version: 0.22.0

### Description:
When using `paginateRaw()`,  the `$paginator->items()` method returns this result array instead of the expected items array.

```php
[
  "hits" => [], // here's the actual items array
  "nbHits" => 100,
  "exhaustiveNbHits" => false,
  "query" => "",
  "limit" => 24,
  "offset" => 0,
  "processingTimeMs" => 0,
]
```

I havent tested with other engines but I think this could be a compatible fix :
```php
// Laravel\Scout\Builder::paginateRaw

$results = $engine->paginate($this, $perPage, $page);

$items = isset($results['hits']) ? $results['hits'] : $results; // fix

$paginator = Container::getInstance()->makeWith(LengthAwarePaginator::class, [
    'items' => $items,
    ...
]);
```

**Comment by driesvints** [comment]
Ping @curquiza

**Comment by curquiza** [comment]
Hello @driesvints and @patlamontagne!
I'm not sure to understand the issue.
Isn't the purpose of `rawPaginate()`, to get the whole result? Using only `paginate()` will make return the array of `hits`.

**Comment by patlamontagne** [comment]
I would be expecting `rawPaginate()` to return a paginator working exactly like `paginate()` only calling `$paginator->items()` should return the collection/array of raw results from the meilisearch query instead of the usual collection of eloquent models.

The paginator itself needs  `items` to be the collection of items to work properly. I found out that when using livewire's tailwind default pagination template, the `rawPaginate()` version of the paginator breaks when calling `firstItem()` and `lastItem()` since it's checking the array length of the meilisearch query result array instead of the length of the actual results, thus always displaying `Showing 1 to 7 of x total`  (7 is the length of the array I showed on my first comment) even though the first page contained 24 actual results in this case.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by patlamontagne** [comment]
@driesvints I might be able to do that in the upcoming days, but before I proceed, can any of you guys confirm that the paginator using raw data is (or isn't) supposed to work out of the box when rendered in a template? Has it ever with former versions? And by that I mean looping directly through `$paginator->items()` expecting to display the result and rendering the pagination links with `$paginator->links()`

From my point of view it should, because what's even the point of initializing a paginator if it doesn't understand its own results properly.  However, seems like it's not limited to `meilisearch` engine, the same thing happens with the `collection` engine, so either it's been overlooked when implementing `paginateRaw`, either it's intentional like @curquiza is implying.

I will save all of us precious time and won't create a repo if it's intentional, I'll just keep overriding the Scout Builder on my project and move on.

Thank you!

**Comment by mmachatschek** [comment]
The docblock of the `paginateRaw()` method states `Paginate the given query into a simple paginator with raw data`. Raw in scouts context means the result returned by the underlying search engine of the submitted search. 

The method was introduced with PR https://github.com/laravel/scout/pull/220 to be able to get the faceted filters, aggregations etc. from the search engine with the possibility to use the pagination feature of laravel.
If you need to get the results from the `paginateRaw()` method with MeiliSearch then you will need to call `$paginator->items()['hits']`

**Comment by driesvints** [comment]
Thanks @mmachatschek
