### ISSUE TITLE
Laravel Scout Meilisearch: Says Imported Models, but doesn't

### ISSUE THREAD

**Issue by PR4M** [laravel/scout#536]
- Scout Version: ^9.2
- Scout Driver: MeiliSearch
- Laravel Version: ^8.21
- PHP Version: 8.0.1
- Database Driver & Version: MySQL

### Description:
Running `php artisan scout:import "App\Models\:name" always returns: 
All [App\Models\Content] records have been imported.

But the model records were never stored on Meilisearch. Neither the index was automatically created during the import process (as I saw on Youtube, running the scout import command seems auto-creating the Meilisearch index if it does not exist. 

I had to run `php artisan scout:index contents` to create the contents index on Meilisearch.

Note:
All the configuration of Meilisearch on the server is done correctly, the `meilisearch_key` is also already in place. 
`scout_queue` is already set to false or at the moment, no queue driver is used and running. 

### Steps To Reproduce:
- Add Searchable Trait on Content.php model (Still doesn't work)
- Override the `toSearchableArray` like the following: 
```
public function toSearchableArray(): array
{
    return [
        'id'   => $this->getKey(), // this *must* be defined
        'name' => $this->name,
    ];
}
```
Which described as a solution here: [Scout says imported data, but doesnt] (https://stackoverflow.com/questions/68615150/laravel-scout-meilisearch-says-imported-data-but-doesnt) is also not affecting

Run the following artisan commands (had no effect)

`php artisan cache:clear
php artisan route:clear
php artisan config:cache
composer dumpautoload`

I also notice that on other people, the scout:import always returns with numbers of records that have been imported such as: 
- "Imported [App\Models\:name] models up to: 100" 
- All [App\Models\Content] records have been imported.

But in my case, it's only: All [App\Models\Content] records have been imported.

Thank you.

**Comment by driesvints** [comment]
Please provide the exact Scout and Meilisearch versions when submitting issues.

Did you:

- Upgrade Meilisearch binary to the very latest version?
- Upgrade scout to the very latest version?
- Restarted Meilisearch process after upgrading?

**Comment by PR4M** [comment]
Here's the exact Meilisearch version:
```
{
    "commitSha": "928930ddd552596f51280a17c143cf38079cdea9",
    "commitDate": "2021-09-13T10:17:10+00:00",
    "pkgVersion": "0.22.0"
}
```

Here's the exact Scout version: 
v9.2.10

- I think my Meilisearch is its very latest version
- And the Scout too
- I never upgrade Meilisearch, just installed it recently

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by ianbrucey** [comment]
Also having the same issue. I keep running scout import, but no data is being pushed. Has there been any updates on this issue?

**Comment by curquiza** [comment]
This might not be related to Laravel, check your task status using this route in MeiliSearch. You will know if the import failed or is still processing.
https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status

**Comment by michaelklopf** [comment]
We have similar issues, the problem is that scout says all is good, but not even tasks are created in meilisearch. Doing it with curl on the machine does create entries in the index.

**Comment by XZzYassin** [comment]
are you guys using any queues? because I think `Laravel\Scout\Jobs\MakeSearchable` are being pushed to the queue but is not being consumed by any worker.

**Comment by mrpritchett** [comment]
Did anyone figure this out? Having what seems like the same issue as above. No MakeSearchable jobs are being picked up.

**Comment by mmachatschek** [comment]
@klipitkas this most likely is a combination of unknowingly using the laravel task queue for [laravel scout](https://github.com/laravel/scout/blob/877bce500c7d1cc467176dea9bc0c87640c270fb/config/scout.php#L44) and not running any worker or meilisearchs task queue not done with the tasks being sent https://www.meilisearch.com/docs/learn/advanced/asynchronous_operations .

**Comment by kamasuPaul** [comment]
If you're here searching for a solution because when you batch import using something like `php artisan scout:import "App\Models\Post"` and `meilsearch` is not showing the imported data, it's probably because you're not running a queue. The batch import uses a queue. So running `php artisan queue:listen` might help you.

**Comment by erycson-cubo** [comment]
I'm only recently having this problem, in my case I discovered that the MakeSearchable Job is always receiving empty $models, so nothing is processed/sent to Meilisearch.

I'm using:

PHP
laravel/framework 10.25.0,
laravel/scout 10.2.4,
meilisearch/meilisearch-php: 1.6.0

Docker
getmeili/meilisearch:v1.6

**Comment by erycson** [comment]
I'm only recently having this problem, in my case I discovered that the MakeSearchable Job is always receiving empty $models, so nothing is processed/sent to Meilisearch.

And yes, I'm sure the queue is being executed

I'm using:

PHP
laravel/framework 10.25.0,
laravel/scout 10.2.4,
meilisearch/meilisearch-php: 1.6.0

Docker
getmeili/meilisearch:v1.6
redis:latest

My conclusion: The queue is sent to Redis, but when processing, none of the items sent to the queue appear
