### ISSUE TITLE
can I use query builder?

### ISSUE THREAD

**Issue by hrmshandy** [laravel/scout#54]
Hi @taylorotwell

Can I use query builder like ordering and grouping ?,  I find in documentation but there is only where clauses and I try to use orderBy but instead an error `Call to undefined method Laravel\Scout\Builder::orderBy()`.

Thank you!

**Comment by sudomabider** [comment]
One of the main reasons to use a search engine like Algolia is to utilize their own ranking system, which is much more powerful and faster than doing it locally. The results from scout should already be an ordered list, although you can customize the ranking logic pretty heavily if you want. That's probably why ordering is not implemented and probably won't be.

Just my opinion.

**Comment by julienbourdeau** [comment]
There is now an `orderBy` method, although I don't think it's used if you're using algolia.

With Algolia, the best way would be to define (in your dashboard) a replica index, that mirrors your main index but with a different sorting. Then while querying, you can target this index with the `within` method.
https://laravel.com/docs/5.5/scout#searching

```php
$orders = App\Order::search('Star Trek')
    ->within('tv_shows_popularity_desc')
    ->get();
```
