### ISSUE TITLE
Integration with Typesense, an open-source alternative to Algolia / ElasticSearch

### ISSUE THREAD

**Issue by jasonbosco** [laravel/scout#543]
Hi team 👋 

I'm Jason, one of the authors of [Typesense](https://github.com/typesense/typesense), which is an open source alternative to Algolia and an easier to use alternative to ElasticSearch. [Here's](https://typesense.org/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch/) a comparison article for context and [examples](https://github.com/typesense/typesense/blob/master/SHOWCASE.md) of folks that use Typesense in production.

One of our community members @AbdullahFaqeir built a [Scout driver for Typesense](https://github.com/devloopsnet/laravel-scout-typesense-engine) and it's been a popular way for Laravel users to integrate with Typesense. So we've been in the process of [adopting it](https://github.com/typesense/laravel-scout-typesense-driver) officially into the @typesense Github org with @hi019's help. 

However, another member of our community pointed out #454 over the weekend in our Slack channel and suggested that we get in touch with you to add support for Typesense directly into Scout. 

@AbdullahFaqeir has offered to update and contribute his work into Laravel Scout and also be a long-term maintainer, answer questions, etc and from the Typesense side, we're happy to also help users integrate Typesense effectively through Scout and help shepherd this integration. 

Would you be ok with a PR that adds support for Typesense into Laravel Scout?

**Comment by driesvints** [comment]
Heya sorry but we have no plans beyond the current drivers. It's best that you release this as a third party package.

**Comment by jasonbosco** [comment]
@driesvints Appreciate the swift response. Any particular reason drivers for additional search engines are not allowed natively in Scout any more?

I’d imagine it would be a net benefit to Laravel users if more search engines worked out of the box with Scout. Did the scope of the project change?

**Comment by driesvints** [comment]
We don't want to take on the maintenance burden of another driver.

**Comment by jasonbosco** [comment]
@driesvints Looking at recent issues in this repo I see what you mean. Just want to say that Typesense is quite stable, scaleable and is already being used in production by several teams. So hopefully the maintenance burden is much lesser.

In any case, a Typesense contributor is offering to take on the maintenance burden of the scout driver itself, so it doesn’t fall on the core team. 

Does that help? 

I’m biased, but I really think that having Typesense as a built-in engine will help Laravel users discover and use a search engine that is open source and just works out of the box.
