### ISSUE TITLE
Soft Deletes not working with MeiliSearch 0.23.1

### ISSUE THREAD

**Issue by lukasleitsch** [laravel/scout#544]
- Scout Version: 9.3.1
- Scout Driver: MeiliSearch
- MeiliSearch Version: 0.23.1
- Laravel Version: 8.70.2
- PHP Version: 8.0.12
- Database Driver & Version: 10.6.4-MariaDB

### Description:

Scout can't filter records if `soft_delete` is enabled in the scout config. With `soft_delete` enabled the search failed with `--> 1:1 | 1 | __soft_deleted=0 | ^------------^ | = attribute `__soft_deleted` is not filterable, available filterable attributes are:`

As far as I see MeiliSearch needs the field `__soft_deleted` as filterable Attributes: https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html

It seems that Scout isn't add the `__soft_deleted` to the filterable attributes. 

### Steps To Reproduce:

- `git clone https://github.com/lukasleitsch/laravel-scout-bug-report.git`
- Create a database and setup Laravel
- Add meilisearch config to `.env`

```
SCOUT_DRIVER=meilisearch
MEILISEARCH_HOST=http://127.0.0.1:7700
MEILISEARCH_KEY=masterKey
```
- `php artisan migrate:fresh --seed `
- Open the index page of the Laravel installation in your browser
- The welcome.blade.php contains a search in post and will fail with an exception

**Comment by driesvints** [comment]
Thanks @mmachatschek

**Comment by lukasleitsch** [comment]
Thank you very much for the explanation, @mmachatschek 

I was a little bit confused after reading [the documentation](https://laravel.com/docs/8.x/scout#soft-deleting) and the [comment in the `scout.php` config](https://github.com/laravel/scout/blob/ad961771d1f38aadc01e658e5a9bd83a90a828f7/config/scout.php#L77).

I guessed that scout handles everything after enabling the option in the config.

**Comment by mmachatschek** [comment]
@driesvints where should a info be added? to the config file and or the docs?

**Comment by driesvints** [comment]
Docs probably

**Comment by wazimshizm** [comment]
tried https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model as per your instructions. and added

```
public $meilisearchSettings = [
            'filterableAttributes' => [
                '__soft_deleted',
            ],
        ];
```

Just throws
`Call to undefined method MeiliSearch\Endpoints\Indexes::filterableAttributes()` when running the command.

tried looking at the instructions as per what was recently added into the documentation. We have to make post calls to make it work? I don't understand how this is accomplished in laravel. Please excuse my lack of understanding of MeiliSearch I've just started trying to incorporate it. This seems like a large hurdle just to include deleted records.

**Comment by mmachatschek** [comment]
```diff
public $meilisearchSettings = [
-            'filterableAttributes' => [
+            'updateFilterableAttributes' => [
                '__soft_deleted',
            ],
        ];
```

**Comment by wazimshizm** [comment]
> ```diff
> public $meilisearchSettings = [
> -            'filterableAttributes' => [
> +            'updateFilterableAttributes' => [
>                 '__soft_deleted',
>             ],
>         ];
> ```

Legend, Thank-you!

**Comment by dwightwatson** [comment]
Did anyone find a solution for this using Scout out of the box with Meilisearch? Looks like the solutions above require customising the engines or sync commands.
