### ISSUE TITLE
Send new records or updates into big chunks

### ISSUE THREAD

**Issue by totiherms** [laravel/scout#548]
Hi, I have an index with about 300k documents. I've imported to meilisearch at once, using chunks of 10k records, and meilisearch indexes it very fast (about 10-15 seconds per chunk)

Now, every time a record is added, laravel scouts sends to meilisearch a document to index one by one, and this is very time-consuming, for example I've added 1700 records, which will take about 13 days to process...

is it feasible, for example, to get all the changes made in the last x minutes and send them together in chunks to meilisearch?

One by one addition:
{
        "status": "processed",
        "updateId": 283,
        "type": {
            "name": "DocumentsAddition",
            "number": 1
        },
        "duration": 372.581,
        "enqueuedAt": "2021-11-13T10:36:06.802658925Z",
        "processedAt": "2021-11-13T14:19:17.667221286Z"
    },

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
