### ISSUE TITLE
soft delete a record wouldn't delete the meilisearch index

### ISSUE THREAD

**Issue by tommy66374** [laravel/scout#549]
- Scout Version: "laravel/scout": "^9.3",
- Scout Driver: "meilisearch/meilisearch-php": "^0.19.2"
- Laravel Version: "laravel/framework": "^8.54",
- PHP Version: 8.0.11
- Database Driver & Version:

### Description:
With default settings, soft delete a record wouldn't delete the meilisearch index, still can search the soft deleted record

### Steps To Reproduce:
Homestead.yaml
```
features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: false
    - webdriver: false
    - meilisearch: true
```

.env
```
SCOUT_DRIVER=meilisearch
MEILISEARCH_HOST=http://127.0.0.1:7700
MEILISEARCH_KEY=masterKey
```

Car model
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;

class Car extends Model
{
    use HasFactory;
    use SoftDeletes;
    use Searchable;

    public function toSearchableArray()
    {
        $array = $this->toArray();

        return $array;
    }
}
```

config/scout.php with default settings and then use command
```
php artisan scout:import "App\Models\Car"
```

in the cars table only have 1 record, soft delete this record
```
$car->delete();
```

search again the deleted record ID 1
```
Car::search('1')->get()->dd();
```

expect there is no result, but it return the ID 1 record with deleted_at timestamp

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
