### ISSUE TITLE
Unable to Set Custom ObjectId

### ISSUE THREAD

**Issue by osama-klabs** [laravel/scout#551]
- Scout Version: 9.3
- Scout Driver: Algolia
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver: mysql

### Description:
I am unable to change objectId using getScoutKey
Default objectId App\Models\Product::1 for model Product
i need to change this to Product::1

I tried

`public function getScoutKey()
    {
        return 'Product::'.$this->id;
    }`

but it inserting  App\Models\Product::Product::1

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
