### ISSUE TITLE
Pagination with subquery returns no or limited data

### ISSUE THREAD

**Issue by jkalousek** [laravel/scout#552]
- Scout Version: 9.3.2
- Scout Driver: MeiliSearch
- Laravel Version: 8.69
- PHP Version: 8.0.3
- Database Driver & Version: 0.24

### Description:
My problem seems related or at least somewhat similar to #450 in regards that The results break when I append an subquery.

I have table "Materials" filled with about 17 500 rows.

### Steps To Reproduce:
When I run:
`$materials = Material::where('price_per_unit', '>', 0)->simplePaginate(30);`
I get correct data and pagination works fine.
![image](https://user-images.githubusercontent.com/8996764/143614759-9c3573bf-0ac0-4688-adeb-e5f386c7d359.png)

`$materials = Material::search($request->query('s'))->simplePaginate(10);` with search term will give me:
![image](https://user-images.githubusercontent.com/8996764/143614895-99269761-a730-4894-888a-686b1fcaf34e.png)
which seem correct and expected and again, pagination works...

...but when I try to use search with subquery as in first query with same search term as last time I get no data at all:
```
$materials = Material::search($request->query('s'))->query(function ($builder) {
                return $builder->where('price_per_unit', '>', 0);
            })->simplePaginate(10);
```
![image](https://user-images.githubusercontent.com/8996764/143615118-112faa4f-dc25-459f-81d0-e04d170c382c.png)

My serch term and table column `price_per_unit` have plenty common records which are shown with during second example so there should not be any problem with actual data.

Only thing that I'm no sure of and might be totally irrelevant is MeiliSearch has search parameter "limit" which the docs says is of value 20 by default. I can imagine that there could be no matches if output from query is limited. But I assume that this is handled by scout?

**Comment by jkalousek** [comment]
UPDATE: I was just playing with the search terms and with some other terms I manage to get on first page 5 results (should have returned 10) and then 10 on second page 8 on third page and 9 on fourth page. So there seems to be really something wrong with how much data is returned.

**Comment by mmachatschek** [comment]
@jkalousek when you do a normal `->paginate(10)` on the second query instead of `->simplePaginate(10)` do get 0 results too? Secondly do you get results if you do:

```php
$materials = Material::search($request->query('s'))->query(function ($builder) {
                return $builder->where('price_per_unit', '>', 0);
            })->raw();
```

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
