### ISSUE TITLE
Soft delete doesn't work

### ISSUE THREAD

**Issue by koushik355** [laravel/scout#554]
- Scout Version: 9.3.2
- Scout Driver: MeiliSearch
- Laravel Version: 8.52.0
- PHP Version: 8.0.8
- Database Driver & Version: PostgreSQL 13.2, compiled by Visual C++ build 1914, 64-bit

### Description:
If I add `soft_delete` to true, it doesn't work. Please check the steps the reproduce. 
It works perfectly fine with `soft_delete` to `false`

### Steps To Reproduce:

Change the `soft_delete` in `config/scout.php` to 
`'soft_delete' => true`

Then 
`php artisan config:clear`
`php artisan scout:flush "App\Models\ModelName"`
`php artisan scout:import "App\Models\ModelName"`

Open the shell using 
`php artisan tinker`

Now search using your model
`ModelName::search('testing')->get()`

`MeiliSearch\Exceptions\ApiException with message 'Attribute `__soft_deleted` is not filterable. Available filterable attributes are: ``.'`

**Comment by driesvints** [comment]
@mmachatschek @curquiza can one of you check into this?

**Comment by mmachatschek** [comment]
@koushik355 this is the same problem like https://github.com/laravel/scout/issues/549 you need to tell the MeiliSearch Index that this field is filterable or it wont work

**Comment by mmachatschek** [comment]
@driesvints I still think this PR https://github.com/laravel/docs/pull/7423 is worth merging. I may find some time soon to add an additional example command to the docs on how to tackle this situation.

**Comment by driesvints** [comment]
Thanks @mmachatschek

**Comment by koushik355** [comment]
@mmachatschek Thank you. Solved it using that. 

To anyone who runs into the same problem, here is how to solve it. 
The most optimal way to create a command that you can execute every time whenever you add a new model into index 
Steps to solve this problem completely for once and all
Create a command 
`php artisan make:command ResetMeiliSearch`

```
$client = new Client(config('scout.meilisearch.host'), config('scout.meilisearch.key'));
        $index = (new ModelName())->searchableAs();
      
        $client->index($index)->updateSortableAttributes(['id']); // optional I added it because I wanted to sort using the ID
        
        $client->index($index)->updateFilterableAttributes(['__soft_deleted']); // this will do the trick 

        $this->info('Reset the search');
```

Make sure to import this at the top 

`use MeiliSearch\Client;`

The next time you add another model to the index, you can add something to this command file to solve it.

**Comment by mmachatschek** [comment]
@koushik355 and others here is a working command that should be executed with each deployment or MeiliSearch update 

https://gist.github.com/mmachatschek/c27ecb45b479d033d68f4355861b10d8

This automatically gets the needed configuration for each model/index and applies the update methods on the index. It's derived from the archived wiki article https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model

**Comment by koushik355** [comment]
@mmachatschek I did try that but it didn't update it. I'm pretty sure that it didn't fail either because there's no log or error message while executing the commands. Here is what I followed

1. made changes to `scout.php` as mentioned in the gist
2. `php artisan config:cache`
3. `php artisan scout:import "App\Models\ModelName"`
4. `php artisan tinker` 
5. Searched for my model using this `ModelName::searchable()->first()`

and the result was the same which is 
![image](https://user-images.githubusercontent.com/66407490/144453967-0011c407-7d3a-4e54-8c3f-088be79615e4.png)


@mmachatschek Please do let me know if I'm doing it correctly or not. I would really love for this trick to work as it makes life way easier. I've already spent a very significant amount of time trying to get everything right for this particular thing. Thank you.

**Comment by koushik355** [comment]
The solution for me was to create a command and update those settings so that anytime on any env I needed or any dev needed it we could execute it. Here is what my solution looked like 
```
<?php

namespace App\Console\Commands;

use App\Models\PostedJob;
use Exception;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use MeiliSearch\Client;

/**
 * Class ResetMeilisearchSorting
 * @package App\Console\Commands
 */
class ResetMeilisearchSorting extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'reset:meilisearch';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'This will reset the filterable attributes, searchable attributes, sortable attributes of PostedJob Index on Meilisearch';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        // change max execution time as it might take some time to reindex it
        ini_set('max_execution_time', 180);
        try {
            $client = new Client(config('scout.meilisearch.host'), config('scout.meilisearch.key'));
            $index = (new PostedJob())->searchableAs();
            $clientIndex = $client->index($index);

            $clientIndex->updateRankingRules([
                'typo',
                'words',
                'proximity',
                'attribute',
                'wordsPosition',
                'exactness',
                'desc(id)',
                'desc(created_at)'
            ]);

            /**
             * Don't distinct by any value. If something like this was put by accident, then delete this
             */
            $clientIndex->resetDistinctAttribute();
            $clientIndex->updateSearchableAttributes([
                'batch_posting_id',
                'sites',
                'site_ids',
                'title',
                'company',
                'job_type',
                'description',
                'city',
                'province',
                'country',
                'category_names'
            ]);

            $clientIndex->updateFilterableAttributes([
                'title',
                '__soft_deleted',
                'city_id',
                'province_id',
                'country_id',
                'site_ids',
                'category_ids',
                'created_at'
            ]);

            $clientIndex->updateSettings([
                'sortableAttributes' => [
                    'id',
                    'created_at'
                ]
            ]);

//            $model = addslashes('App\Models\PostedJob');
//            Artisan::call('scout:flush ' . $model);
//            Artisan::call('scout:import ' . $model);
            $this->info('Made changes to the index of PostedJob Index on Meilisearch');
        } catch (Exception $e) {
            $this->error($e->getMessage());
        }
    }
}

```

**Comment by andreasmatu** [comment]
> @koushik355 and others here is a working command that should be executed with each deployment or MeiliSearch update
> 
> https://gist.github.com/mmachatschek/c27ecb45b479d033d68f4355861b10d8
> 
> This automatically gets the needed configuration for each model/index and applies the update methods on the index. It's derived from the archived wiki article https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model

Do you know if there are any plans on integrating this into laravel scout natively? 
This workaround should be mentioned in the docs, although i think there should be an integrated process in scout.
