### ISSUE TITLE
Meilisearch: Sortable and Filterable Attributes not updating when including _geo attribute

### ISSUE THREAD

**Issue by mxmtsk** [laravel/scout#555]
- Scout Version: 9.3.2
- Scout Driver: MeiliSearch
- Laravel Version: 8.73.1
- PHP Version: 8.0.13
- Database Driver & Version: MySQL 8

### Description:
To make some attributes filterable and sortable I've written a small artisan command to do the work for me. Now I wanna use [Meilisearch's Geosearch functionality](https://docs.meilisearch.com/reference/features/geosearch.html). For that, I added `_geo` to the array of filterable and sortable attributes by using Laravel Scouts respective methods.

It doesn't throw an error but it also doesn't make the attributes filterable or sortable anymore.

This is the code:

```php
    public function handle()
    {
        $client = new Client(config('scout.meilisearch.host'));

        $client->index('pubs')->updateSortableAttributes(['_geo']);
        $this->info('Updated sortable attributes...');

        $client->index('pubs')->updateFilterableAttributes([
            '_geo',
            'cashless_payment',
            'smoking',
            'outside_seating',
            'food',
            'barrierfree',
        ]);
        $this->info('Updated filterable attributes...');

        return Command::SUCCESS;
    }
```

To check if this is an issue with Meilisearch, I've executed the same command directly on Meilisearch, which worked without a problem:

```bash
curl \
  -X POST 'http://localhost:7700/indexes/pubs/settings/filterable-attributes' \
  -H 'Content-type:application/json' \
  --data-binary '[
        "_geo",
        "cashless_payment",
        "smoking",
        "outside_seating",
        "food",
        "barrierfree"
  ]'
```

> {"updateId":2}

```bash
curl \
  -X GET 'http://localhost:7700/indexes/pubs/updates/2' \
  -H 'Content-type:application/json'
```

Update response
```json
{"status":"processed","updateId":2,"type":{"name":"Settings","settings":{"filterableAttributes":["_geo","barrierfree","cashless_payment","food","outside_seating","smoking"]}},"duration":0.047,"enqueuedAt":"2021-11-30T12:46:13.716435Z","processedAt":"2021-11-30T12:46:13.764012Z"}%
```

### Steps To Reproduce:
1. add the `_geo` fields to any model:

```php
    public function toSearchableArray()
    {
        $array = $this->toArray();


        $array['_geo'] = [
            'lat' => 52.520008, // hardcoded for reproduction purposes
            'lng' => 13.404954,
        ];

        return $array;
    }
```

2. update the filterable attributes:

```php
     $client->index('pubs')->updateFilterableAttributes([
            '_geo',
        ]);
```

3. Try to query by Geo Distance
```php
        $params = [
	        "latitude" => 52.489769,
	        "longitude" => 13.324380
        ];
        $distance = 100000;
        return Pub::search('', function (Indexes $meilisearch, string $query, array $options) use ($params, $distance) {
            $options['filter'] = "_geoRadius({$params['latitude']}, {$params['longitude']}, {$distance})";
            $options['sort'] = [
                "_geoPoint({$params['latitude']}, {$params['longitude']}):asc",
            ];
            return $meilisearch->search($query, $options);
        })->take(10)->get();
```

**Comment by mmachatschek** [comment]
@mxmtsk please try to get in touch with a support channel on MeiliSearch Slack they will get you up and running.
This issue looks to me like an implementation problem, specific to your usecase.

**Comment by driesvints** [comment]
Seems like a feature request to me. Feel free to submit a PR or open an issue on the meilisearch repo.

**Comment by homeoftheunits** [comment]
Hi, i have the same problem. Is there an solution in the meantime? 

Cheers
Ralf

**Comment by curquiza** [comment]
Hello @homeoftheunits 

You can contact our support (the Meilisearch support) by sharing the detailed steps to reproduce, including the Meilisearch error you get at the final step.
- [Slack](https://meilicommunity.slack.com/join/shared_invite/zt-c4rs8tpi-ZId_q3fw~7cqeuzFG4XHaA#/shared-invite/email)
- [GitHub discussions](https://github.com/meilisearch/meilisearch/discussions)

Before contacting us, you might want to check your settings are well being imported to Meilisearch using [this route](https://docs.meilisearch.com/reference/api/settings.html#get-settings).

**Comment by homeoftheunits** [comment]
I know. But it looks like, that it's an Scout Problem. I check this

**Comment by Schipsi** [comment]
Update for those looking for a quick fix : 

After looking at Meilisearch logs i found an error during the index : 
```
"The document with the id: `1` contains an invalid _geo field: `{\"lat\":\"52.51667\",\"lng\":\"13.38333\"}`."
```

When checking the docs, `lat` and `lng` are supposed to be float and not string : https://docs.meilisearch.com/learn/advanced/geosearch.html#preparing-documents-for-location-based-search

My guess is that the geo fields are not properly changed back to float when indexed by Meilisearch, casting them to float in the `toSearchableArray` method fixed this for me. 
In database the values were stored as float, but that didn't seems to be enough.

Hope this will be useful.


```
    public function toSearchableArray(): array
    {
        return [
            '_geo' => [
                'lat' => (float) $this->geo_lat,
                'lng' => (float) $this->geo_lng,
            ],
        ];
    }
```

**Comment by 99linesofcode** [comment]
The solution proposed by @Schipsi resolved the issue for me as well. Without the cast to `float` my index remains empty despite flushing and updating the indices. Looks to me like an issue with `laravel/scout`.

**Comment by curquiza** [comment]
Hello! FYI, once Meilisearch v0.28.0 will be out, this problem will not exist anymore!
Just don't forget to update your meilisearch-php client when upgrading your Meilisearch version!

**Comment by furmannodesol** [comment]
I'm using meilisearch v0.29.0, however the _geo index remains empty despite flushing and updating the indices. tried both by casting as float and string. 
`'_geo' => [
                'lat' => (float) $this->latitude,
                'lng' => (float) $this->longitude,
            ],`

**Comment by erycson** [comment]
> Hello! FYI, once Meilisearch v0.28.0 will be out, this problem will not exist anymore! Just don't forget to update your meilisearch-php client when upgrading your Meilisearch version!

I updated the client to version 0.25.0, but it didn't work

In my tests, I noticed the following behavior:

```php
// This doesn't work, this is always sent empty
"_geo" => ["lat" => 10.23, "lng" => (float) 10.23], 

// This is sent correctly, but it's not usable because it needs to be "_geo"
"geo" => ["lat" => 10.23, "lng" => 10.23],
```
