### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by oulfr** [laravel/scout#557]
Using search method in laravel scout with more than one page throw key index exception .
In file: src/Engines/CollectionEngine.php
never use index like that to get the first element of list $results[0], it's better to use array_pop that give the last element of the list

**Comment by driesvints** [comment]
Feel free to attempt a pr. Thanks.

**Comment by oulfr** [comment]
i dont understand how you manage your issue, the first time i have seen your issue page in github i said wow this project have zero issue all are corrected but after my issue i have understand how you manage issue!! samply you close them there is no correction. in my opinion this not serious !!
