### ISSUE TITLE
Undefined array key 0 pagination

### ISSUE THREAD

**Issue by oulfr** [laravel/scout#558]
- Scout Version: 9.3.0
- Scout Driver: Collection
- Laravel Version: 8.65
- PHP Version: 8.0
- Database Driver & Version: Mysql 5.0

### Description:
The scout collection driver throw an exception with pagination:
	ErrorException
Undefined array key 0

### Steps To Reproduce:

1. Enable scout driver in .env: SCOUT_DRIVER=collection
2. Add route to web.php:

          Route::get('search', '\Modules\Model\Http\Controllers\ModelController@search')->name('model.search')
3. Create search method:
      
         public function search(Request $request): \Illuminate\Http\JsonResponse
          {
            $list = Model::search($request->q)->paginate(1);
            return response()->json($list);
          }

Go to this URL : http://localhost/test/search?q=a&page=2

       Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
       D:\PROGRAMMES\xampp\htdocs\doctolib\vendor\laravel\scout\src\Engines\CollectionEngine.php:170

correction : ##556

**Comment by driesvints** [comment]
Please provide a way to reproduce this without `$request->q`. Please give me the exact search string that'll trigger this.

**Comment by oulfr** [comment]
You can search in any model first we need a string column and in the model add this searchable column:

       public function toSearchableArray()
         {
            return ['name', 'email','...'];
        }

When there is many row with name begin with 'a' we can search like this:
          
                 public function search(Request $request): \Illuminate\Http\JsonResponse
               {
                $list = Model::search('a')->paginate(1);
                return response()->json($list);
               }

**Comment by driesvints** [comment]
I can't reproduce this sorry. Everything works fine and I get the JSON result when I paginate through different pages. Please try a support channel if you need help with this:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by driesvints** [comment]
That also still just works for me.

**Comment by oulfr** [comment]
are you sure that your result contains something ? maybe you arent in collection driver or your search result is empty
