### ISSUE TITLE
Use dynamic index when importing collections of models

### ISSUE THREAD

**Issue by bobmulder** [laravel/scout#560]
Hi there! 

There is an usecase where I want to make my models searchable in indexes separated by language.

I discovered there is partial support for this in Scout. At first, you have the `searchableAs` method to define a custom index for the model. Great. However, when importing collections of those models, things will go slightly different:

```php
$index = $this->meilisearch->index($models->first()->searchableAs());
```

> https://github.com/laravel/scout/blob/9.x/src/Engines/MeiliSearchEngine.php#L54

When updating a collection of models, the used index will be taken from the first model. It will not look at the other models' custom indexes.

I think this could be solved by using a `groupBy` on the collection, and update those items per index. It would look like something like this:

```php
    public function update($models)
    {
        if ($models->isEmpty()) {
            return;
        }

        $grouped = $models->groupBy(fn($item) => $item->searchableAs());

        foreach ($grouped as $index => $models) {

            if ($this->usesSoftDelete($models->first()) && $this->softDelete) {
                $models->each->pushSoftDeleteMetadata();
            }
    
            $objects = $models->map(function ($model) {
                if (empty($searchableData = $model->toSearchableArray())) {
                    return;
                }
    
                return array_merge(
                    [$model->getKeyName() => $model->getScoutKey()],
                    $searchableData,
                    $model->scoutMetadata()
                );
            })->filter()->values()->all();
    
            if (! empty($objects)) {
                $index->addDocuments($objects, $models->first()->getKeyName());
            }

        }

    }
```

> Please note this is just pseudo code and has not been tested

When it comes to searching through Scout, there is already [support to search in custom indexes](https://laravel.com/docs/8.x/scout#custom-indexes). There is no need to change anything on that part.

Through this issue I'd like to get some feedback on the idea and the supposed change. Does this make sense to you, or am I missing something? If you are positive about this I'd be happy to open a pull request with the changes.

**Comment by driesvints** [comment]
I think it was only intended to use a single index per model type. I'm not sure it's wanted overal to have dynamic indexes.

@mmachatschek @curquiza do any of you maybe know if that's wanted?

**Comment by mmachatschek** [comment]
The Meilisearch Engine driver tries to mimic the Algolia Engine. As far as I invastigated this, the AlgoliaEngine does the same thing. It always gets the index name from the first model in the update statement.

As MeiliSearch supports using multiple indexes I think this is worth PRing to support the functionality

**Comment by driesvints** [comment]
Thanks @mmachatschek.

@bobmulder feel free to send in a PR. I *think* this can be sent to the current release since you couldn't have dynamic indexes before.

**Comment by bobmulder** [comment]
Thank you @mmachatschek, I've introduced #561 to make this happen for `MeiliSearchEngine`. 

I have no experience with Algolia, but  according to the code I suppose we could do the same for `AlgoliaEngine`. Do you agree?
