### ISSUE TITLE
Implement fallback driver on failure

### ISSUE THREAD

**Issue by brad-tilmor** [laravel/scout#562]
Hi, I was thinking that since Scout is built to integrate with external search services, it would be useful to allow for a fallback to the Eloquent driver upon failure of that external service (say an API key expires, the service is down, etc) to prevent end-user service interruptions. 

If you think that would be useful, I can take a crack at implementing it if you'd like!

**Comment by driesvints** [comment]
Hey @brad-tilmor, we don't think a fallback driver makes much sense ourselves. We feel that people in general won't be maintaining two separate drivers. Sorry

**Comment by brad-tilmor** [comment]
@driesvints, I'm envisioning that it would fall back to the Eloquent driver by default, since they clearly wouldn't be using both Algolia and Meilisearch for instance. Currently, if say, a hosted Meilisearch server is down for instance, it times out, which would break functionality for the end-user. I think it'd be vastly preferable to simply return the results more slowly from the database, you don't agree? 

I don't imagine it would be too terribly hard to implement a fallback for basic searches, and I could probably hack together some sort of `->onFailure()` hook that allows developers to customize what happens on failure, if they for instance happen to be using more complex searches that require drilling into the underlying driver functionality.

**Comment by driesvints** [comment]
No, we don't feel that this would be of much use ourselves, sorry.

**Comment by brad-tilmor** [comment]
Okay, well as a scout user I disagree, but that's fine.
