### ISSUE TITLE
Missing tag/changelog for laravel/scout v9.3.3

### ISSUE THREAD

**Issue by caugner** [laravel/scout#563]
- Scout Version: 9.3.3
- Scout Driver: Algolia / MeiliSearch
- Laravel Version: 8.77.1
- PHP Version: 8.1.0
- Database Driver & Version:

### Description:

Packagist has a version v9.3.3 of this package, but there is no corresponding tag/changelog.

### Steps To Reproduce:

See: https://packagist.org/packages/laravel/scout#v9.3.3

**Comment by driesvints** [comment]
We'll get that removed. Thanks for making us aware 👍

**Comment by caugner** [comment]
Thanks for the quick response.

Are you considering actually *removing* that version *from Packagist* though? Wouldn't that mean that `composer install` will start failing for folks who have that version in their `composer.lock` (except if they have it in their cache or use a proxy).

**Comment by driesvints** [comment]
This was a faulty release. We're gonna remove the tag.

**Comment by caugner** [comment]
Just to understand: Are you recommending folks having already updated to this 9.3.3 to manually downgrade to 9.3.2 then? 🤔 

If you remove 9.3.3 now and release a new 9.3.3 version later, I tend to think that Composer would not offer to update folks from (removed) 9.3.3 to (future) 9.3.3. Unless this release does indeed have major faults (i.e. instead of just being 9.3.2 with a different version number, it seems to work for us), I would guess the safest option is to re-release 9.3.2 as 9.3.4, avoiding the issue for folks (like me 👋) already having 9.3.3 in their `composer.lock`.

**Comment by driesvints** [comment]
I released v9.3.4 👍
