### ISSUE TITLE
Sorting feature is missing in MeiliSearch Engine

### ISSUE THREAD

**Issue by bedus-creation** [laravel/scout#572]
- Scout Version: 9.3.4
- Scout Driver:  MeiliSearch
- Laravel Version: 8.61
- PHP Version: 8.0.14
- Database Driver & Version: Mysql 8

### Description:
MeiliSearch supports sorting feature out of the box after defining sortable parameters while indexing. The given `orderBy` method is supposed to work for sorting. Consider the following code. 

```php
return User::search('Admin')
        ->orderBy("id", "desc")
        ->get();
```

The above code should generate a query like in https://github.com/laravel/scout/blob/9.x/src/Engines/MeiliSearchEngine.php#L114

```php
public function paginate(Builder $builder, $perPage, $page) 
 { 
     return $this->performSearch($builder, array_filter([ 
         'filters' => $this->filters($builder), 
         'limit' => (int) $perPage, 
         'sort'=> ['id:desc'],
         'offset' => ($page - 1) * $perPage, 
     ])); 
 } 
```
But the `sort` options is missing while performing the search. 

https://github.com/laravel/scout/blob/7811f6d025cd0024da19a065b0eefb43e6e7eb69/src/Engines/MeiliSearchEngine.php#L114-L121

https://github.com/laravel/scout/blob/7811f6d025cd0024da19a065b0eefb43e6e7eb69/src/Engines/MeiliSearchEngine.php#L99-L105

**Comment by driesvints** [comment]
This sounds like a feature request. We'd be happy to receive PR's.

/cc @mmachatschek

**Comment by mmachatschek** [comment]
Hi @bedus-creation,

this feature is plausable but was already tried to be implemented here https://github.com/laravel/scout/pull/537

Maybe this is useful to the DatabaseEngine too and all engines could benefit from a generic solution. @driesvints

**Comment by driesvints** [comment]
@taylorotwell can we maybe revisit the PR from above that @mmachatschek linked to?

**Comment by driesvints** [comment]
The related pr was merged

**Comment by bedus-creation** [comment]
I think sort option is still missing in paginate function #537

**Comment by driesvints** [comment]
@bedus-creation please send in a PR
