### ISSUE TITLE
Skip adding where clauses when search is empty on `DatabaseEngine`

### ISSUE THREAD

**Issue by rodrigopedra** [laravel/scout#581]
Right now if we search for an empty string, for example in a endpoint that lists all users:

```php
Route::get('/api/users', fn () => User::search(request()->query('q'))->paginate());
```

Even when the search string is empty, the where clauses are added:

```sql
select *
from `users`
where (`users`.`name` like '%%' or `users`.`email` like '%%' or match (`users`.`notes`) against ('' in natural language mode))
order by `id` desc
limit 30 offset 0
```

Which for the database driver is irrelevant and could lead the query optimizer to pickup a wrong index (when more constraints are added).

If skipping adding the where clauses when the search string is empty is a desirable I can send a PR.

**Comment by driesvints** [comment]
Yeah I think so. Feel free to PR 👍

**Comment by rodrigopedra** [comment]
Thanks @driesvints , sent PR #582
