### ISSUE TITLE
A facade root has not been set. 

### ISSUE THREAD

**Issue by giojkd** [laravel/scout#588]
- Scout Version: 9.4.4
- Scout Driver: Algolia
- Laravel Version: 8.83.1
- PHP Version: 8.0.15
- Database Driver & Version:

### Description:

Get this message on runtime: "A facade root has not been set."

### Steps To Reproduce:

add searchable trait to any models and run

**Comment by giojkd** [comment]
`[2022-02-17 01:19:06] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:200)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(125): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(112): Illuminate\\Log\\LogManager->get(NULL)
#2 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\\Log\\LogManager->driver()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\\Log\\LogManager->error('A facade root h...', Array)
#4 /Users/giovanniorlandi/Sites/Jinn/app/Exceptions/Handler.php(41): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(RuntimeException))
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): App\\Exceptions\\Handler->report(Object(RuntimeException))
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(RuntimeException))
#7 /Users/giovanniorlandi/Sites/Jinn/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2022-02-17 01:19:06] laravel.ERROR: A facade root has not been set. {"exception":"[object] (RuntimeException(code: 0): A facade root has not been set. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/ModelObserver.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/Searchable.php(26): Laravel\\Scout\\ModelObserver->__construct()
#2 [internal function]: App\\Models\\Product::bootSearchable()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(272): forward_static_call(Array)
#4 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(252): Illuminate\\Database\\Eloquent\\Model::bootTraits()
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(228): Illuminate\\Database\\Eloquent\\Model::boot()
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(206): Illuminate\\Database\\Eloquent\\Model->bootIfNotBooted()
#7 [internal function]: Illuminate\\Database\\Eloquent\\Model->__construct(Array)
#8 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#9 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('App\\\\Models\\\\Prod...')
#10 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('App\\\\Models\\\\Prod...', Array, true)
#11 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('App\\\\Models\\\\Prod...', Array)
#12 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('App\\\\Models\\\\Prod...', Array)
#13 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('App\\\\Models\\\\Prod...', Array)
#14 /Users/giovanniorlandi/Sites/Jinn/config/laracombee.php(50): app('App\\\\Models\\\\Prod...')
#15 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require('/Users/giovanni...')
#16 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#17 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#18 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 /Users/giovanniorlandi/Sites/Jinn/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
[2022-02-17 01:19:07] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:200)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(125): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(112): Illuminate\\Log\\LogManager->get(NULL)
#2 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\\Log\\LogManager->driver()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\\Log\\LogManager->error('A facade root h...', Array)
#4 /Users/giovanniorlandi/Sites/Jinn/app/Exceptions/Handler.php(41): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(RuntimeException))
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): App\\Exceptions\\Handler->report(Object(RuntimeException))
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(RuntimeException))
#7 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2022-02-17 01:19:07] laravel.ERROR: A facade root has not been set. {"exception":"[object] (RuntimeException(code: 0): A facade root has not been set. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/ModelObserver.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/Searchable.php(26): Laravel\\Scout\\ModelObserver->__construct()
#2 [internal function]: App\\Models\\Product::bootSearchable()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(272): forward_static_call(Array)
#4 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(252): Illuminate\\Database\\Eloquent\\Model::bootTraits()
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(228): Illuminate\\Database\\Eloquent\\Model::boot()
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(206): Illuminate\\Database\\Eloquent\\Model->bootIfNotBooted()
#7 [internal function]: Illuminate\\Database\\Eloquent\\Model->__construct(Array)
#8 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#9 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('App\\\\Models\\\\Prod...')
#10 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('App\\\\Models\\\\Prod...', Array, true)
#11 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('App\\\\Models\\\\Prod...', Array)
#12 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('App\\\\Models\\\\Prod...', Array)
#13 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('App\\\\Models\\\\Prod...', Array)
#14 /Users/giovanniorlandi/Sites/Jinn/config/laracombee.php(50): app('App\\\\Models\\\\Prod...')
#15 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require('/Users/giovanni...')
#16 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#17 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#18 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
[2022-02-17 01:19:15] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:200)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(125): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(112): Illuminate\\Log\\LogManager->get(NULL)
#2 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\\Log\\LogManager->driver()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\\Log\\LogManager->error('A facade root h...', Array)
#4 /Users/giovanniorlandi/Sites/Jinn/app/Exceptions/Handler.php(41): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(RuntimeException))
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): App\\Exceptions\\Handler->report(Object(RuntimeException))
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(RuntimeException))
#7 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2022-02-17 01:19:15] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:200)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(125): Illuminate\\Log\\LogManager->resolve(NULL, NULL)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(112): Illuminate\\Log\\LogManager->get(NULL)
#2 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\\Log\\LogManager->driver()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\\Log\\LogManager->error('A facade root h...', Array)
#4 /Users/giovanniorlandi/Sites/Jinn/app/Exceptions/Handler.php(41): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(RuntimeException))
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): App\\Exceptions\\Handler->report(Object(RuntimeException))
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(RuntimeException))
#7 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 {main}
"} 
[2022-02-17 01:19:15] laravel.ERROR: A facade root has not been set. {"exception":"[object] (RuntimeException(code: 0): A facade root has not been set. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/ModelObserver.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/Searchable.php(26): Laravel\\Scout\\ModelObserver->__construct()
#2 [internal function]: App\\Models\\Product::bootSearchable()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(272): forward_static_call(Array)
#4 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(252): Illuminate\\Database\\Eloquent\\Model::bootTraits()
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(228): Illuminate\\Database\\Eloquent\\Model::boot()
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(206): Illuminate\\Database\\Eloquent\\Model->bootIfNotBooted()
#7 [internal function]: Illuminate\\Database\\Eloquent\\Model->__construct(Array)
#8 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#9 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('App\\\\Models\\\\Prod...')
#10 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('App\\\\Models\\\\Prod...', Array, true)
#11 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('App\\\\Models\\\\Prod...', Array)
#12 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('App\\\\Models\\\\Prod...', Array)
#13 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('App\\\\Models\\\\Prod...', Array)
#14 /Users/giovanniorlandi/Sites/Jinn/config/laracombee.php(50): app('App\\\\Models\\\\Prod...')
#15 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require('/Users/giovanni...')
#16 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#17 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#18 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
[2022-02-17 01:19:15] laravel.ERROR: A facade root has not been set. {"exception":"[object] (RuntimeException(code: 0): A facade root has not been set. at /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258)
[stacktrace]
#0 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/ModelObserver.php(47): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#1 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/scout/src/Searchable.php(26): Laravel\\Scout\\ModelObserver->__construct()
#2 [internal function]: App\\Models\\Product::bootSearchable()
#3 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(272): forward_static_call(Array)
#4 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(252): Illuminate\\Database\\Eloquent\\Model::bootTraits()
#5 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(228): Illuminate\\Database\\Eloquent\\Model::boot()
#6 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(206): Illuminate\\Database\\Eloquent\\Model->bootIfNotBooted()
#7 [internal function]: Illuminate\\Database\\Eloquent\\Model->__construct(Array)
#8 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(917): ReflectionClass->newInstanceArgs(Array)
#9 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build('App\\\\Models\\\\Prod...')
#10 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve('App\\\\Models\\\\Prod...', Array, true)
#11 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve('App\\\\Models\\\\Prod...', Array)
#12 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make('App\\\\Models\\\\Prod...', Array)
#13 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('App\\\\Models\\\\Prod...', Array)
#14 /Users/giovanniorlandi/Sites/Jinn/config/laracombee.php(50): app('App\\\\Models\\\\Prod...')
#15 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require('/Users/giovanni...')
#16 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#17 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#18 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /Users/giovanniorlandi/Sites/Jinn/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
