### ISSUE TITLE
Relations run twice when querying

### ISSUE THREAD

**Issue by sudomabider** [laravel/scout#59]
This is only happening when the searchable model's `$with` array contains relations _and_ a `load()` is performed with additional relations on the search results. The relations in the `$with` array are loaded twice.
### Examlple:

Model `Product` has 

```
protected $with = ['sale'];
```

Then in the search controller

```
$products = Product::search($term)->paginate();
$products->load(['categories', 'image']);
```

The `sale` relation query is run twice.

If I put everything into `$with` or move everything into `load()` then it only runs once.

---

Interestingly the two `sale` query statements have the `product_id` in completely different orders.

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
