### ISSUE TITLE
The Authorization header is missing. It must use the bearer authorization method.

### ISSUE THREAD

**Issue by gstamosbg** [laravel/scout#593]
- Scout Version: 9.4.4
- Scout Driver: MeiliSearch
- Laravel Version: 8.83.1
- PHP Version: 8.0.16
- Database Driver & Version: xx

### Description:

The Authorization header is missing. It must use the bearer authorization method.

### Steps To Reproduce:
After last update of meilisearch, i cant access my indexes.
I am receiving ->

`{
    "message": "The Authorization header is missing. It must use the bearer authorization method.",
    "exception": "MeiliSearch\\Exceptions\\ApiException",
    "file": "/var/www/website/vendor/meilisearch/meilisearch-php/src/Http/Client.php",
    "line": 197,
    "trace": [
        {
            "file": "/var/www/website/vendor/meilisearch/meilisearch-php/src/Http/Client.php",
            "line": 177,
            "function": "parseResponse",
            "class": "MeiliSearch\\Http\\Client",
            "type": "->"
        },`

**Comment by mmachatschek** [comment]
@gstamosbg you are using an incompatible version of meilisearch/meilisearch-php and meilisearch it self. Consult the releases page https://github.com/meilisearch/meilisearch-php/releases to check which version you need to use in order to correctly connect to meilisearch.

**Comment by gstamosbg** [comment]
> @gstamosbg you are using an incompatible version of meilisearch/meilisearch-php and meilisearch itself. Consult the releases page https://github.com/meilisearch/meilisearch-php/releases to check which version you need to use in order to correctly connect to meilisearch.

Oh yes, I hadn't seen it.
`- Upgrading meilisearch/meilisearch-php (v0.18.3 => v0.22.0): Extracting archive`

After that, problem was solved.

Thanks alot,
have a nice day/night :)
