### ISSUE TITLE
Search results limiting still returning all results

### ISSUE THREAD

**Issue by samfrjn11** [laravel/scout#594]
- Scout Version: 9.4.4
- Scout Driver: Database
- Laravel Version: 9.1.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8.0.28

### Description:
Support for limiting results on the CollectionEngine was added in #569 but the collection still returns all results when `->take(i)` is used.
The application is not throwing an error when using the `->take()` method, but it's not adding the limit and offset parameters to the SQL query either.

### Steps To Reproduce:
- Create a model with Searchable trait
- `SearchableModel::search($value)->take(5)->get();`

**Comment by driesvints** [comment]
Ping @keithbrink, do you have any ideas here?

**Comment by driesvints** [comment]
I just noticed you're using the database driver but reporting on the collection engine. It seems this isn't implemented yet on the database engine: https://github.com/laravel/scout/blob/9.x/src/Engines/DatabaseEngine.php#L56

Feel free to send in a PR if you want 👍
