### ISSUE TITLE
Error creating index with scout:index command

### ISSUE THREAD

**Issue by alexseik** [laravel/scout#595]
- Scout Version: 9.4.5
- Scout Driver: MeiliSearch
- Laravel Version: 8.75.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.0

### Description:
Error creating index with command `php  artisan scout:index [name] --key [keyName]`

Undefined array key "primaryKey" in file `/meilisearch/meilisearch-php/src/Endpoints/Indexes.php` inside method `create` called by `MeiliSearchEngine::createIndex`.

`primaryKey` seems to have been depreciated. It is not returned by [POST] /index endpoint.

### Steps To Reproduce:

* Install new meilisearch v0.25
* Update Laravel\Scout to its new version
* Launch `php  artisan scout:index [name] --key [keyName]`

**Comment by driesvints** [comment]
Is your Meilisearch binary compatible with your installed Meilisearch PHP version? https://github.com/meilisearch/meilisearch-php#-compatibility-with-meilisearch

**Comment by alexseik** [comment]
@driesvints Thanks so much for the quickness! Effectively I was using meilisearch-php v0.18 instead v0.22. With meilisearch-php v0.22.0 and meilisearch v0.25 and scout v9.4.5 everything work fine!
