### ISSUE TITLE
I need to wait a second before index is imported again

### ISSUE THREAD

**Issue by martijnderidder** [laravel/scout#597]
Scout Version: 9.4.0
Scout Driver: Elasticsearch
Laravel Version: 9.0.1
PHP Version: 8.0.13
Database Driver & Version: MariaDB 10

### Description:
When i am searching and i delete something in the search results, and i request the same search XHR again, it takes a second to reindex again. 

1. I am searching for 'user X' in the users list, and find 10 users.
2. I delete user X, so with the same query i expect 9 users now
3. But when i execute in the controller this: `$user->delete()` and fire directly a new XHR request, i noticed the user is still visible in the records. But when i add a `sleep(1)` in the controller, its working.

I expect this is because the index is not refreshed. And i see an old version of the indexed imports.

I don't use a queue, so that should not be the problem i guess?
I also tried to use : `$user->unsearchable()`, but that is also not working.

**Comment by driesvints** [comment]
@mmachatschek do you know this?

**Comment by mmachatschek** [comment]
@martijnderidder 

Even though you may have turned off queueing of Scout jobs, meilisearch will put the update asynchronously on its internal queue and therefore needs some time until its processed. 
If you need to wait for your delete/update to finish, you probably need to write a wrapper around the update and deletion that accesses the meilisearch sdk and will wait for the records to beeing processed.

**Comment by driesvints** [comment]
Thanks @mmachatschek

**Comment by driesvints** [comment]
Btw, we'd appreciate a PR to the docs if anything can be clarified around this.

**Comment by martijnderidder** [comment]
@mmachatschek I am using Elasticsearch, but i guess its the same answer haha.. thnx!  

Btw, how would you guys fix this problem? When i am loading the page, would you use a empty search() method or maybe making two methods? One for loading user list without searching, and doing it with eloquent... and when a users search, just another method where you use laravel scout?

**Comment by mmachatschek** [comment]
@driesvints 

> Btw, we'd appreciate a PR to the docs if anything can be clarified around this.

I added an PR to the docs that clarifies why the updates are async https://github.com/laravel/docs/pull/7747

@martijnderidder 

> I am using Elasticsearch, but i guess its the same answer haha.. thnx!

Upps. Didn't see its Elasticsearch. But anyways same thing. The Engine is just not ready or done with processing the queue.

If you want the operation to be fully synchronous (trade off in UX as the user waits longer for a search result but is viable in your situation) you can do something like [this](https://github.com/algolia/scout-extended/blob/1534b7060f70f82ceade6b50db2e8a9ac8b5869f/src/Jobs/UpdateJob.php#L142). You would need to extend your ES-driver and modify your `update` method.

If you have any other questions about this, please check out the scout channel on [discord](https://discordapp.com/invite/KxwQuKb).
