### ISSUE TITLE
Pagination doesn't work 

### ISSUE THREAD

**Issue by Geczy** [laravel/scout#60]
See here
https://laracasts.com/discuss/channels/laravel/laravel-scout-paginate-not-working

`"Undefined variable: elements"`

**Comment by sudomabider** [comment]
Same issue as #46 

Fix already in place just needs to be released.

**Comment by astritzeqiri** [comment]
@sudomabider When will this release or which version has it with LengthAwarePaginator because i downloaded it and it still has Paginator

**Comment by sudomabider** [comment]
@astritzeqiri sorry I'm not a contributor so I don't know. 

In the meantime though, if you know how to do it, you can create a custom `Builder` class extending `\Laravel\Scout\Builder` overriding just the `paginate` method. Bind this custom `Builder` to the service container as `\Laravel\Scout\Builder` then scout should use your own pagination logic instead.

**Comment by sudomabider** [comment]
@astritzeqiri seems like the LengthAwarePaginator was also merged into master: #62. You can use master for now if you're comfortable with it.

**Comment by astritzeqiri** [comment]
@sudomabider It's fixed now thank you vey much

**Comment by powelski** [comment]
Any plans when are going to have next release? I don't want to use master and this bug is rather fatal 😃
