### ISSUE TITLE
registerSearchableMacros should not be in the Searchable trait

### ISSUE THREAD

**Issue by ivanomatteo** [laravel/scout#601]
### This is only a code improvement consideration

BaseCollection::macro() deal with a static associative array, so make no sense repeat the macro registration every time the Searchable trait is booted.

functions:
registerSearchableMacros(),
queueMakeSearchable(),
queueRemoveFromSearch()

should be placed in some other place, and invoked only one time (on the provider boot or on the first trait boot).

**Comment by driesvints** [comment]
I don't think there's a big issue here but if you want you can always attempt a PR 👍

**Comment by ivanomatteo** [comment]
@driesvints yes, I'm agree, is not a issue, if i have time I'll make a PR +1
