### ISSUE TITLE
Cant index the entities ( Undefined index: primaryKey)

### ISSUE THREAD

**Issue by masoud-me** [laravel/scout#603]
- Scout Version: 0.12.5
- Scout Driver: MeiliSearch 
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: mysql 
- SDK Version (If using a third-party service): #.#.#

### Description:
i have problem with index command (PHP artisan scout:index XXX)
while i run this command i get 

` ErrorException 

  Undefined index: primaryKey

  at vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php:47
     43▕         $options['uid'] = $uid;
     44▕ 
     45▕         $response = $this->http->post(self::PATH, $options);
     46▕ 
  ➜  47▕         return new self($this->http, $response['uid'], $response['primaryKey']);
     48▕     }
     49▕ 
     50▕     public function all(): array
     51▕     {

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

`
bug it creates the index , and i the search work correctly , but when i want to update the entities via Model i get below error : 
`
"message": "Undefined index: errorCode",
    "exception": "ErrorException",
    "file": "/home/matican-pc2/work/esgtrade/vendor/meilisearch/meilisearch-php/src/Delegates/HandlesIndex.php",
    "line": 64,
`

**Comment by driesvints** [comment]
> SDK Version (If using a third-party service): #.#.#

Please fill this in and resubmit.

**Comment by masoud-me** [comment]
updated the issue @driesvints

**Comment by driesvints** [comment]
What's your `meilisearch/meilisearch-php` version?

**Comment by masoud-me** [comment]
my meili search version is :  0.25.2

**Comment by driesvints** [comment]
That's your binary version. What's your SDK version?

**Comment by masoud-me** [comment]
How can i find it ?

**Comment by driesvints** [comment]
Composer.lock file

**Comment by masoud-me** [comment]
Update : 

The problem has been fixed; I didn't create the index for the relations of my model, which I want to generate cache for them.
