### ISSUE TITLE
scout:import --all flag

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/scout#605]
Hey.

After doing scout:flush the usual next step is to import everything back. To achieve that, you have to import every model one by one.

Instead, a `--all` flag could be introduced that would iterate over all models that use `Searchable` trait and call `scout:import` on every found model.

**Comment by driesvints** [comment]
I don't think we have plans to add this ourselves but you can always attempt a PR if you want. Thanks

**Comment by oprypkhantc** [comment]
@driesvints I'll be happy to implement it myself, but I see no point in spending time if it's going to get declined. Can you specify whether it's worth trying?

**Comment by driesvints** [comment]
I don't review Pr's, Taylor does. Your best bet is to try a PR or release it as a package perhaps.
