### ISSUE TITLE
Problem with the new Meilisearch Version

### ISSUE THREAD

**Issue by homeoftheunits** [laravel/scout#607]
Hi everybody,

i have problems with the newest Meilisearch version. I found out, that the Meilisearch-PHP-Wrapper in Scout is out of date. Is it possible, that scout can update the version of the wrapper? Someone that install meilisearch with sail, will have the same problem as i. 

The Problem is, in the old meilisearch wrapper, this command will always send the Bearer Token
```
$this->headers = array_filter([
    'Authorization' => sprintf('Bearer %s', $this->apiKey),
]);
```
With older meilisearch versions, this will not be a problem. But with the newest version of meilisearch you got the error: The provided API key is invalid.

In the new Version of the Wrapper, it is updated to this:
```
if (null != $this->apiKey) {
    $this->headers['Authorization'] = sprintf('Bearer %s', $this->apiKey);
}
```

So, it would be nice, if you can update the wrapper version :)

Cheers
Ralf

**Comment by driesvints** [comment]
Can you send in a PR?

**Comment by mmachatschek** [comment]
>  Is it possible, that scout can update the version of the wrapper?

@homeoftheunits just like the algolia php sdk, the meilisearch php sdk is a suggested package for laravel/scout. This means if you want to use one of the services, you need to make sure, you're using the correct version of the SDK for the service in use.

The [docs mention](https://laravel.com/docs/9.x/scout#meilisearch), that you always need to review your dependencies when you update your composer dependencies or upgrade your search service like meilisearch.

This package can not include the SDK version of algolia and meilisearch, as users may use different services with different version. A user which uses Algolia wouldn't want the meilisearch php sdk installed and vice versa.

@driesvints

**Comment by homeoftheunits** [comment]
I just wanted to point out that there are currently problems because you have the sdk in your composer.json:

`"meilisearch/meilisearch-php": "^0.19",` 

Sorry for that. I update it by myself

**Comment by driesvints** [comment]
@homeoftheunits that's in require-dev which shouldn't affect userland.

**Comment by homeoftheunits** [comment]
Sure, i know, but I still just wanted to draw attention to it. So, i do it by myself, and everybody is happy :)
