### ISSUE TITLE
Attribute not filterable nor sortable

### ISSUE THREAD

**Issue by JerryBels** [laravel/scout#611]
- Scout Version: 9.4.5
- Scout Driver: MeiliSearch
- Laravel Version: 9.4.1
- PHP Version: 8.1.2
- Database Driver & Version: mysql/mysql-server:8.0
- SDK Version (If using a third-party service): `curl   -X GET 'http://localhost:7700/version' : {"commitSha":"unknown","commitDate":"unknown","pkgVersion":"0.26.1"}`

### Description:

Hello. Using basic sail, I tried to implement search with Scout, going for Meilisearch. Search itself works great, but when I'm trying to filter or sort... It simply fails. I don't see anything in the doc that would explain this.

I read [here](https://github.com/meilisearch/meilisearch-php#-compatibility-with-meilisearch) that only Meilisearch 0.26 is compatible, well I was on 0.25 so I updated the image but it doesn't help.

### Steps To Reproduce:

Nothing special really... 

```
    public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'name' => "{$this->first_name} {$this->last_name}",
            'first_name' => $this->first_name,
            'last_name' => $this->last_name,
            'email' => $this->email,
        ];
    }

// ...

User::search($this->search)->orderBy('id', 'asc')
Attribute `id` is not sortable. Available sortable attributes are: ``.

User::search($this->search)->where('email', 'my@email.com')
Attribute `email` is not filterable. Available filterable attributes are: ``.
```

Minimal repo with the issue : https://github.com/JerryBels/example-search

**Comment by JerryBels** [comment]
So I did some digging in Meilisearch doc. If I manually add the arguments to to filterable and sortable lists, everything works as intended.

```
$client->index('users')->updateFilterableAttributes(['id', 'email']);
$client->index('users')->updateSortableAttributes(['id', 'email'])
```

`orderBy` isn't even documented in [Scout's documentation](https://laravel.com/docs/9.x/scout) but `where` is, and it should definitely AT LEAST include a warning that Meilisearch needs this manual work - the best option being the ability to config the wanted filterable / orderable columns somehow.

**Comment by driesvints** [comment]
So, Scout's docs aren't meant to be a documentation for Meilisearch. That's what Meilisearch docs are for. We note in our docs:

<img width="758" alt="Screenshot 2022-04-04 at 10 26 10" src="https://user-images.githubusercontent.com/594614/161504664-099051e5-7b50-430c-9349-3b68b22c9196.png">

I can find the following in the Meilisearch PHP readme: https://github.com/meilisearch/meilisearch-php#-compatibility-with-meilisearch

<img width="948" alt="Screenshot 2022-04-04 at 10 27 12" src="https://user-images.githubusercontent.com/594614/161504727-3b9a843a-7cfe-4a43-a650-39896e5f1946.png">

I can't find docs about `updateSortableAttributes`, only: https://docs.meilisearch.com/learn/advanced/geosearch.html#sorting-results-with-geopoint

<img width="877" alt="Screenshot 2022-04-04 at 10 28 36" src="https://user-images.githubusercontent.com/594614/161504814-a9a50785-d75b-4f54-95fe-2ed7d51527df.png">

So it's best that you take this up with the Meilisearch team to properly document. Of course, you're free to attempt a PR to the Laravel docs. Thanks

**Comment by JerryBels** [comment]
Yeah I thought as much after digging much more. Although I really thought Scout was said to resolve everything by itself, so I guess the docs could use a little more clarity on this. Resolved my issue with an artisan command I will integrate in my flow, that will initiate Meilisearch fields properly. But basically, in case someone ends up here : 

```
$client = new Client(config('scout.meilisearch.host'), config('scout.meilisearch.key'));
User::makeAllSearchable();
$client->index('users')->updateSearchableAttributes(['id', 'email']);
$client->index('users')->updateSortableAttributes(['id']);
$client->index('users')->updateFilterableAttributes(['roles']);
```

`updateSearchableAttributes` is very usefull if you want something like `roles` being sent so it can be used as a filter, while still not returning results when searching for the strings it contains.

**Comment by iteniasim** [comment]
so, there is no way to get the sortable and filterable indexes automatically from config for meilisearch so that it works with just scout:import artisan command?
been trying to get the sortable attributes working from config since yesterday with no luck

**Comment by JerryBels** [comment]
Hey, yes since then Scout integrated a better solution, see the last version's docs : https://laravel.com/docs/10.x/scout#configuring-filterable-data-for-meilisearch

You can configure everything in scout config file and then `php artisan scout:sync-index-settings` will do the trick. Please note than when working on a sail env, if you `sail down` and `sail up` again, you will have to reinit your indexes with above command again and **current data in your DB won't be sync automatically**. I kept a custom command file where I call all of my models' searchable initializer, and call this file after `sail up` and scout sync : 

```php
namespace App\Console\Commands;

use App\Models\User;
use App\Models\Email;
use Illuminate\Console\Command;
use MeiliSearch\Client;

class initMeilisearch extends Command
{
    protected $signature = 'init:meilisearch';

    protected $description = 'Inits Meilisearch indexes data';

    public function handle()
    {
        User::makeAllSearchable();
        Email::makeAllSearchable();
        // more models
    }
}

```

Also, if you're using Horizon, make sure for it to be up again, otherwise your indexes will be empty as no job will be processed...

**Comment by ambitionphp** [comment]
Method 'ping' not found in \Meilisearch\Client
