### ISSUE TITLE
Using Searchable Pivot Model in Using() statement causes error on unsearchable()

### ISSUE THREAD

**Issue by logan-jobzmall** [laravel/scout#614]
- Scout Version: 9.4.5
- Scout Driver: Algolia
- Laravel Version: 8.83.2
- PHP Version: 8.0.17

### Description:
When using `->sync([])` on a model's `BelongsToMany` relationship that uses a custom Pivot model `using(PivotModel::class)`, and that `PivotModel` is using the `Searchable` trait, the `RemoveFromSearch` queued job to remove the detached models causes an error: `All objects must have an unique objectID (like a primary key) to be valid.`

If a custom getScoutKey() is specified in said `PivotModel`, the error becomes: `The 'objectID' attribute is required to use action=deleteObject near line:1 column:61`

### Steps To Reproduce:

1. Make sure that queues are enabled for Scout
2. Using a model, let's say the `User` model, create a `BelongsToMany` relationship to another model (let's use `Post` for instance) - and make sure it is that uses a pivot table (`user_posts`) and make sure that is has the directive. Make sure that this pivot table has an incrementing ID for a primary key.
3. Create a `UserPost` Pivot model for this, and make sure the aforementioned `belongsToMany` relationships is
`->using(UserPost::class)`. Add the Searchable trait to `UserPost`, and decorate `public $incrementing = true;`
5. Try to use `$user->posts()->sync([$post_ids])` to sync posts with the user and then `$user->posts()->sync([])` to detach them. You should end up with this error.

**Comment by driesvints** [comment]
@logan-jobzmall I'll re-open this once you've provided a repo. Thanks
