### ISSUE TITLE
Meilisearch engine pagination total broken

### ISSUE THREAD

**Issue by eliasjtg** [laravel/scout#615]
- Scout Version: 9.4.6
- Scout Driver: MeiliSearch
- Laravel Version: 8.83.6
- PHP Version: 8.0.16
- Database Driver & Version: Mysql 8.0.28-0ubuntu0.20.04.3
- SDK Version (If using a third-party service): 0.23.1

### Description:

This issue is related with https://github.com/laravel/scout/issues/535 and map id with key name, the solution was https://github.com/laravel/scout/commit/8a7782c5ce72b9407a3cb2e29a4865cf4efc964b creating mapIdsFrom method

The same issue is occurring with the method keys in Engine, does not take into account mapIdsFrom and call directly mapIds, which breaks the pagination count.

A solution is create keysFrom method:

```
/**
     * Get the results of the query as a Collection of primary keys.
     *
     * @param  \Laravel\Scout\Builder  $builder
     * @param  string  $key
     * @return \Illuminate\Support\Collection
     */
    public function keysFrom(Builder $builder, $key)
    {
        return $this->mapIdsFrom($this->search($builder), $key);
    }
```

and modify the getTotalCount method:

```
/**
     * Get the total number of results from the Scout engine, or fallback to query builder.
     *
     * @param  mixed  $results
     * @return int
     */
    protected function getTotalCount($results)
    {
        $engine = $this->engine();

        $totalCount = $engine->getTotalCount($results);

        if (is_null($this->queryCallback)) {
            return $totalCount;
        }

        $ids = $engine->mapIdsFrom(
            $results,
            $key = Str::afterLast($this->model->getScoutKeyName(), '.')
        )->all();

        if (count($ids) < $totalCount) {
            $ids = $engine->keysFrom(tap(clone $this, function ($builder) use ($totalCount) {
                $builder->take(
                    is_null($this->limit) ? $totalCount : min($this->limit, $totalCount)
                );
            }), $key)->all();
        }

        return $this->model->queryScoutModelsByIds(
            $this, $ids
        )->toBase()->getCountForPagination();
    }
```

Changing `$key = Str::afterLast($this->model->getScoutKeyName(), '.')` and calling $engine->keysFrom reusing the `$key` variable

### Steps To Reproduce:

Using query() reproduce the bug

return Post::search($search)->query(function($query) {
    $query->with('image');
})->paginate(5);

**Comment by driesvints** [comment]
@mmachatschek is this a Meilisearch incompatibility again?

**Comment by mmachatschek** [comment]
@driesvints not a incompatibility.

@eliasjtg this is worth a PR to the `MeiliSearchEngine.php` and the `Builder.php`

**Comment by driesvints** [comment]
I've been checking into the fix here but I'm a little concerned about the `$this->search($builder)` call in `keysFrom`. That seems a bit overkill and will reduce performance? Thoughts?

**Comment by eliasjtg** [comment]
@mmachatschek I would gladly do a PR, but I'm not very familiar with them, I don't know how to do it

**Comment by eliasjtg** [comment]
@driesvints i share your concern, in the test I see that I had 192 records and I noticed something:

The pagination are chunked in 5 but the total are 192 records

```
is_null($this->limit) ? $totalCount : min($this->limit, $totalCount)
```

`$this->limit` are null what caused the 192 ids to be consulted, this can cause problems with thousand of records

**Comment by driesvints** [comment]
I just noticed you were using `->with` in a subquery and that's not supported. `with` can only be used on the base query for eager loading and not in subqueries.

With the following example, everything works fine and I get the correct pagination results:

```php
User::search('e')->query(function($query) {
    $query->where('id', '>', 10);
})->paginate(15);
```

So I don't see an issue right now.

**Comment by slovenianGooner** [comment]
I am having a similar issue:

```php
// URL: ?page=1
Document::search("e")->paginate(15);
// nbHits = 15
```

But if I load page 2, the pagination is correct.
```php
// URL: ?page=2
Document::search("e")->paginate(15);
// nbHits = 893
```

The only difference in the params is that with page 1, we sent "offset" of 0, and with page 2, the "offset" is 15.

**Comment by curquiza** [comment]
Hello @slovenianGooner 
This is something related to the Meilisearch behavior, and not related to laravel/scout if I'm correct.
The Meilisearch support is available to help you on our side 😄 
We've opened a discussion to explain the behavior of `nbHits` in more detail: https://github.com/meilisearch/product/discussions/467
Otherwise, for any other questions related to Meilisearch you can open [a discussion here](https://github.com/meilisearch/meilisearch/discussions) or join [our slack](https://meilicommunity.slack.com/ssb/redirect).

Hope it helps 😄

**Comment by eliasjtg** [comment]
@driesvints

**Comment by driesvints** [comment]
Ah I was mistaking this for a subquery but it's actually indeed attaching the where clause to the base query.

**Comment by eliasjtg** [comment]
Please reopen the merge request, the bug is currently active, I'll try to help by digging deeper, on the server we had to use Build::macro to override the pagination method to make it work

**Comment by driesvints** [comment]
@eliasjtg I think for now, since you're the only one experiencing this, it's best to attempt a PR if you know a solution. 

I'm still unsure if the usage of `->with()` there actually makes sense...

**Comment by SadeghPM** [comment]
problem still exists.
Another problem for pagination count comes from `mapIds` in `MeiliSearchEngine.php`.
In functions comment the problem described!
```php
    /**
     * Pluck and return the primary keys of the given results.
     *
     * This expects the first item of each search item array to be the primary key.
     */
    public function mapIds($results)
    {
```
First item of each search result is not primary key.

**Comment by MatusBoa** [comment]
@SadeghPM 

Found same problem with this. Hours of debugging and the whole problem was that primaryKey was not on the first place in `hits` (result from meilisearch)

**Comment by SadeghPM** [comment]
hi @driesvints 
this is very serious bug in meilisearch driver and could be fix easily.

cc @MatusBoa
