### ISSUE TITLE
syncWithSearchUsingQueue using invalid config values

### ISSUE THREAD

**Issue by danielsimkus** [laravel/scout#620]
Hello,

I may be reading wrong but I've noticed in the code it uses the following config fields which don't exist in the config file.
`scout.queue.queue` and `scout.queue.connection` - these aren't in the config that gets published, and may be from a time before `scout.queue` was a `bool`.

```
    public function syncWithSearchUsing()
    {
        return config('scout.queue.connection') ?: config('queue.default');
    }
    public function syncWithSearchUsingQueue()
    {
        return config('scout.queue.queue');
    }
```

Should we add `scout.queue_name` and `scout.connection` back into the config and use those? 
I'm happy to submit a PR if that sounds reasonable.

**Comment by driesvints** [comment]
This is intentional. See the commit: https://github.com/laravel/scout/commit/79869d5277ecc1f964774477adf90bc2bdc3676f

Might need some documentation though. Welcoming PR's for that 👍

**Comment by danielsimkus** [comment]
Sorry just to confirm, that means you accept both a boolean or an array value for `scout.queue` ?

It does look like there isn't any `===` checks against it but if someone did add them in the future without noticing, it could have adverse affects potentially.

Happy to update the docs either way, if that's intentional thats fine 👍
