### ISSUE TITLE
output on vscode git bash terminal is a bit weird when publishing scout vendor.

### ISSUE THREAD

**Issue by zerexei** [laravel/scout#623]
- Scout Version: 9.4
- Scout Driver: Database
- Laravel Version: 9.11
- PHP Version: 8.0.2
- Database Driver & Version: mysql
- SDK Version (If using a third-party service): #.#.#
- Meilisearch CLI Version (If using Meilisearch): #.#.#
- Git Bash Version: 2.36

### Description:
The output on vscode git bash terminal is a bit weird when publishing scout vendor.

![vendor-publish-scout-output](https://user-images.githubusercontent.com/69749146/167168445-3f1d0e2b-2412-4028-ba3a-9a9dc7270ab7.png)

### Steps To Reproduce:
1. composer install laravel/scout
2. php artisan vendor:publish
3. 7

**Comment by driesvints** [comment]
Seems to work fine for me with latest Scout and Laravel.

<img width="806" alt="Screenshot 2022-05-09 at 10 12 03" src="https://user-images.githubusercontent.com/594614/167368058-85c75101-5c66-4bf5-97ab-c269ada70b58.png">
