### ISSUE TITLE
extra options

### ISSUE THREAD

**Issue by VanoDevium** [laravel/scout#626]
I have looked at a large number of issues related to passing additional options to a search query.

It all comes down to using a callback.

But it seems to me that in most cases, using a callback is a verbose thing.

Why not just make an `extra()` method, in which each user of the scout can simply pass an array of additional parameters that will simply merge into the final request.

I will try to describe with code example:

> using callback
```php
Movie::search('marvel', static function (Indexes $meili, string $query, array $options) {
    return $meili->search($query, array_merge($options, [
        "attributesToRetrieve" => [
            "id",
            "title",
        ],
        "attributesToHighlight" => [
            "title",
        ],
    ]));
})
    ->orderBy('release_date', 'desc')
    ->raw();
```

> using method extra()
```php
Movie::search('marvel')
    ->extra([
        "attributesToRetrieve" => [
            "id",
            "title",
        ],
        "attributesToHighlight" => [
            "title",
        ],
    ])
    ->orderBy('release_date', 'desc')
    ->raw();
```

**Comment by driesvints** [comment]
I think, right now we have no plans to add a method specific for Meilisearch for this. Feel free to continue to use the callback.

**Comment by Wei102193** [comment]
why is attributesToHighlight not working for me?? Do I need to update some setttings?

**Comment by Wei102193** [comment]
> why is attributesToHighlight not working for me?? Do I need to update some settings?

NVM, I used get() instead of raw(), that was why It did not show the _formatted object.
