### ISSUE TITLE
Meilisearch Pagination with deprecated nbHits

### ISSUE THREAD

**Issue by swapnilsarwe** [laravel/scout#636]
Support in Scout for meilisearch 0.28.0

**Setup**:
PHP: 8.1
meilisearch-http: 0.28.0
"laravel/framework":  "v9.20.0"
"laravel/scout": "v9.4.9"
"meilisearch/meilisearch-php": "v9.20.0",
"meilisearch/meilisearch-php": "^0.23",

Meilisearch has renamed `nbHits`  as per the new release [v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0). 
Because of which we get `Undefined array key "nbHits"` if we are using pagination with Meilisearch.

We can use `estimatedTotalHits` instead of `nbHits` to fix this.
Meilisearch team have suggested better way of pagination on this link [Meilisearch Pagination](https://docs.meilisearch.com/learn/advanced/pagination.html)

**Comment by mmachatschek** [comment]
@swapnilsarwe you need to use the correct `meilisearch/meilisearch-php` package in conjunction with meilisearch itself. Check the releases page of [meilisearch/meilisearch-php here](https://github.com/meilisearch/meilisearch-php/releases) to find out which SDK version is compatible with which meilisearch server version.

The problem you are describing is solved by upgrading the SDK version.

https://github.com/laravel/scout/pull/633

**Comment by driesvints** [comment]
Thanks @mmachatschek
