### ISSUE TITLE
Paginate with global scopes shows wrong number of pages and hides relevant results

### ISSUE THREAD

**Issue by JerryBels** [laravel/scout#639]
- Scout Version: 9.4.9
- Scout Driver: MeiliSearch
- Laravel Version: 9.18.0
- PHP Version: 8.1.7
- Database Driver & Version: mysql/mysql-server:8.0
- SDK Version (If using a third-party service): #.#.#
- Meilisearch Version (If using Meilisearch): 0.26.1
- Meilisearch-php Version (If using Meilisearch): 0.23.1

### Description:

When having a global scope applied to a model, and searching on that model, the search (obviously) doesn't take into account the global scope. So the search returns the full result, which is further filtered by the global scope, resulting in a different number of results to display than the paginate method of scout expected, and eventually empty pages.
For example, a global scope to show a salesperson only his customers in a list, and a search on said customers. The search will return customers belonging to everyone, then the global scope will apply its filter and narrow down the result, which won't be taken into account by the paginate method.

![a](https://user-images.githubusercontent.com/4408419/182369667-624b3cc3-61d5-4c44-aa2d-e2260f362f0c.png)

### Steps To Reproduce:

- Create a model filtering results with a global scope.
- Make this model searchable
- Witness the scope filtering the results after the search is done and the pages count being wrong.
- Try not to cry. Cry a lot.

[EDIT] I created a repos to demonstrate the issue. Simply run the seeds and witness the issue on the home screen : https://github.com/JerryBels/scout-global-scope-bug

**Comment by JerryBels** [comment]
I realized the bug is even worse than that. It's not only that the page count is wrong, it's that if one of the legit results is on page 2, you won't see it right away - you have to go to page 2 to see it. Page 1 :

![1](https://user-images.githubusercontent.com/4408419/182598028-db7fd662-df26-460c-ad49-6ff7301306a8.png)

And then go to page 2 : 

![2](https://user-images.githubusercontent.com/4408419/182598049-b10f1fd3-1bd1-4769-88a2-4aa6e1826e86.png)

All of this is very logical behavior, since Scout calls the search engine and gets legitimate results, them being filtered only after. I'm not sure how to fix this. It seems impossible to fix post search - I checked Scout's and its engines code for a few days now. But I don't know how Scout could possibly change its request to the engine so it takes the global scope into account, nor do I see a way to somehow add this as usable data into the engine... 

For now I backed away from using a global scope in favor of adding more filterable fields to the search engine, and using advanced filters in the callback function. But it's too bad - global scopes were very interesting for my use case.

**Comment by JerryBels** [comment]
Created a repository demonstrating the issue - https://github.com/JerryBels/scout-global-scope-bug

**Comment by driesvints** [comment]
No idea what's going on here. @mmachatschek do you know?

**Comment by driesvints** [comment]
It seems we're not pursuing a fix right now for this: https://github.com/laravel/scout/pull/640. I've sent in a PR to document this limitation here: https://github.com/laravel/docs/pull/8104. Sorry about that.

**Comment by JerryBels** [comment]
Yeah I kinda expected this to be the outcome. I didn't find an easy way to fix this either. Thanks for reporting back.
