### ISSUE TITLE
two primary key for laravel scout

### ISSUE THREAD

**Issue by sajad-nyn** [laravel/scout#642]
hey folks. i have a problem in laravel scout.
i have a table with two primary key (id,serverId) and meilisearch does not support two primary key in one index .
in laravel scout i want to specify different primary key of combine between two primary keys  like : uid= id_serverId.

how  is it possible for me?

**Comment by sajad-nyn** [comment]
also i have created this index but with laravel scout but when i want to use search i have this error:
Column not found: 1054 Unknown column 'uid' in 'where clause'

**Comment by driesvints** [comment]
Unfortunately this is not possible.

**Comment by sajad-nyn** [comment]
> Unfortunately this is not possible.

why???
