### ISSUE TITLE
Breaking queue on database driver

### ISSUE THREAD

**Issue by syn6UK** [laravel/scout#644]
- Scout Version: 9.4.5
- Scout Driver: Database
- Laravel Version: 9.4.1
- PHP Version: 8.1
- Database Driver & Version: MYSQL 8

### Description:

Not sure exactly what is causing this, but there are a few pattenrs i've observed with this.

The following circumstances neec to be considered.

- All models are using Ordered UUIDs as opposed to incrementing integers.
- The driver is database
- The queue setting is true
- The model in question is called Donor, and first_name and last_name are searchable, and have fulltext indexes included in respective migration.

### Steps To Reproduce:

Occurs when Model::Create is called and the above circumstnaces are in place. If i set queue to false in config/scout.php, it works fine.

`
Illuminate\Queue\
InvalidPayloadException
in [C:\WebDeveloper\Websites\api.qrpay.test\webroot\vendor\laravel\framework\src\Illuminate\Queue\Queue.php ](https://github.com/laravel/scout/issues/new?assignees=&labels=&template=1_Bug_report.md)(line 108)
        }        $payload = json_encode($this->createPayloadArray($job, $queue, $data), \JSON_UNESCAPED_UNICODE);        if (json_last_error() !== JSON_ERROR_NONE) {            throw new InvalidPayloadException(                'Unable to JSON encode payload. Error code: '.json_last_error()            );        }        return $payload;
`

**Comment by syn6UK** [comment]
My model

`

class Donor extends Authenticatable
{

    use Searchable,
        SoftDeletes,
        HasOrderedUUID,
        HasApiTokens,
        HasDataColumn;

    protected $guarded = [];

    public static function getCustomColumns(): array
    {
        return [
            'id',
            'anonymous',
            'title',
            'first_name',
            'last_name',
            'email',
            'phone',
            'password',
            'stripe_customer_id'
        ];
    }

    public function toSearchableArray()
    {
        $array = [
            "first_name" => $this->first_name,
            "last_name" => $this->last_name
        ];

        return $array;
    }

}

`




My Migration


`
return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('donors', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->boolean('anonymous')->default(false);
            $table->string('title');
            $table->string('first_name');
            $table->string('last_name');
            $table->string('email');
            $table->string('phone');
            $table->string('password');
            $table->string('stripe_customer_id');
            $table->json('data')->nullable(); // ADHOC DATA SUCH AS MAPPING DONORS TO EXTERNAL SYSTEMS
            $table->fullText('first_name');
            $table->fullText('last_name');
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('donors');
    }
};

`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
