### ISSUE TITLE
Collection with pagination data not matched or giving unwanted results with where clause.

### ISSUE THREAD

**Issue by hannanmiah** [laravel/scout#648]
- Scout Version: 9.4.10
- Scout Driver: MeiliSearch
- Laravel Version: 9.25.0
- PHP Version: 8.1.9
- Database Driver & Version: Mysql@8.0.30-0ubuntu0.22.04.1
- SDK Version (If using a third-party service): #.#.#
- Meilisearch CLI Version (If using Meilisearch): 0.28.1

### Description:
![image](https://user-images.githubusercontent.com/36930986/189752508-a9c4bfed-91ed-447c-abaf-ae7d6d0af9d3.png)

Thic code will output:
![image](https://user-images.githubusercontent.com/36930986/189752906-64ddfd32-76d1-41bd-828e-24fb3078ea30.png)
output collection size is 1. But
![image](https://user-images.githubusercontent.com/36930986/189753094-5deda62e-8c49-43ae-bf63-923574be4936.png)
But this is the total count

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
