### ISSUE TITLE
Support for compatibility with popular column sorting libraries

### ISSUE THREAD

**Issue by TechhDan** [laravel/scout#649]
Is there a chance Scout would be able to add support for working with column sorting libraries such as [Kyslik / Column Sortable](https://github.com/Kyslik/column-sortable) or [S-Damian / Larasort](https://github.com/s-damian/larasort). Both of these libraries combined together would make an amazing way to facilitate creating data-tables like functionality.

The problem is both of these libraries make use of traits on models which hook into the query builder. When searching using scout on both of these libraries the problem is the same for both of them. ```Method Laravel\Scout\Builder::autosort does not exist```. I've opened up an issue for both [S-Damian / Larasort](https://github.com/s-damian/larasort/issues/2) and [Kyslik / Column Sortable](https://github.com/Kyslik/column-sortable/issues/202) but i believe this might be better suited to be fixed within Scout. I'm using Laravel 9.

Thanks!

**Comment by driesvints** [comment]
Hi there. Right now, we don't have plans for this, sorry.
