### ISSUE TITLE
model update() event dont trigger event in scout

### ISSUE THREAD

**Issue by kiwo12345** [laravel/scout#650]
- Scout Version: 9.4.9
- Scout Driver: MeiliSearch
- Laravel Version: 9.2
- PHP Version: 8.0.2

### Description:

The model update() event doesnt seem to trigger a event in scout to remove the items

`Items::where('state', 2)->where('active', 1)->limit(1000)->update(['active' => 0]);`

I have set

```
public function shouldBeSearchable()
    {
        return $this->active == 1;
    }
```

Which should make the rows unsearchable if they get saved with a different value?

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/190588009-afd2c8f9-0780-4066-afd1-347a0af3d271.png)

**Comment by driesvints** [comment]
Thanks @crynobone

**Comment by kiwo12345** [comment]
Thank you for the clarification @crynobone, is there any way to do a bulk update and also remove the items from the search index?
