### ISSUE TITLE
add computed properties from raw results 

### ISSUE THREAD

**Issue by andreasbakir** [laravel/scout#659]
In Meilisearch when you sort by a geoPoint, Meilisearch will automatically add the computed property "_geoDistance" to the results. But this field is not included in the search results when you call the ```->paginate();``` or ```->get();``` on the query builder. But when you call the ```->raw();``` method the computed property is obviously included in the results. 

So casting the raw results into eloquent models omits this computed property, I already tried something with accessors, appends, addSelect but all of this didn't work.

**Comment by mmachatschek** [comment]
@andreasbakir the normal `->get()` method will load a fresh version of the model from the database, so you will not have the geoDistance property in the model. If this is something you depend on you have to write a wrapper around the raw result and load the models from the database by yourself (as of now).

@driesvints after discovering that algolia also supports a geo search, it may be useful to users to add additional info to the returned model.

https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/how-to/geo-ranking-info/
- `_rankingInfo` could be added to the corresponding db model

https://docs.meilisearch.com/learn/advanced/geosearch.html#finding-the-distance-between-a-document-and-a-geopoint
- `_geoDistance` will be added bei meilisearch if you perform a geo search with a geopoint

**Comment by driesvints** [comment]
I think this might indeed be useful. We'd need to figure out a way to set this extra metadata on eloquent models. Probably through a new property on the Searchable trait? Not sure. Feel free to try a PR for this. Thanks!
