### ISSUE TITLE
When query parameter to load page is not `query`, Scout renames it to `query`

### ISSUE THREAD

**Issue by Jamesking56** [laravel/scout#662]
A little bug I found with Scout.

If you have a page which puts the search query as a URL parameter like so:

`http://example.com/mypage?search=someterm`

If you're using Scout and then having a Laravel Paginator on the results page, it renames the URLs in the paginator to:

`http://example.com/mypage?query=someterm`

Looks like `query` is hard-coded in a lot of places, like here for example:

https://github.com/laravel/scout/blob/e43ef0ac5b88a74506215f04d30f625c68192f98/src/Builder.php#L371

**Comment by Jamesking56** [comment]
Example code here that shows the problem:

```php
class MyController extends Controller
{
    public function index(Request $request)
    {
        if ($request->has('search')) {
            $results = User::search($request->get('search'))
                ->paginate(25);
        } else {
            $results = User::latest()
                ->paginate(25)
        }

		return $results->toArray()['links'];
    }
```

Notice that the links from the paginator now have `?query=` instead of `?search=` due to the hard-coding inside of Scout

**Comment by driesvints** [comment]
Please re-post this with a filled out issue template. Thanks

**Comment by Jamesking56** [comment]
#664
