### ISSUE TITLE
Scout Algolia identify with a different guard

### ISSUE THREAD

**Issue by woutervandamme** [laravel/scout#663]
Currently, when using the 'identify' variable for Algolia, scout currently sends the ip address + the id of the current logged in user to Algolia.

I'd like to have a way to overwrite the used authentication guard. It currently only supports the default guard.

**Comment by driesvints** [comment]
Actually it should already be possible with an override:

```php
$user->search(..., ['X-Algolia-UserToken' => $yourAuthedUser->getKey()]);
```

I haven't tried this but I think it should work. But I agree, an easier way to override this would be cool. An extra option could be added for this, feel free to send in a PR if you like.
