### ISSUE TITLE
Filter without search

### ISSUE THREAD

**Issue by Stevemoretz** [laravel/scout#665]
I'm new to scout, so I don't know if this is already included or not?

What I'm exactly talking about is using the where and whereIn without search so it filters the whole index, is an empty string for search the right solution here or is there a special value, or a special way?

Or a feature needs to be added?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
