### ISSUE TITLE
Pagination shows wrong number of pages due to hard limit

### ISSUE THREAD

**Issue by JerryBels** [laravel/scout#667]
Scout Version: 9.4.12
Scout Driver: MeiliSearch
Laravel Version: 9.34
PHP Version: 8.1.7
Database Driver & Version: mysql/mysql-server:8.0
SDK Version (If using a third-party service): #.#.#
Meilisearch Version (If using Meilisearch): 0.29.1
Meilisearch-php Version (If using Meilisearch): 0.24.2

### Description:

Meilisearch have a hard limit of 1000 elements that can be retrieved by a single query. There are lots of talks about it that can be found around their github and on their doc. It's all good, but because of that Scout's pagination is buggy. When having a request that should bring back more than 1000 results, the number of pages is on par with the full result expected from the request, but the pages after 1000 results have been reached are empty. 

There is a solution to increase the hard limit : https://github.com/meilisearch/product/discussions/477 but honestly it doesn't fix Scout's bug, no matter the limit we're potentially displaying pages that can be empty.

### Steps To Reproduce:

https://github.com/JerryBels/scout-pagination-bug

Run the seeds and try to reach page 40, then 41. 40 works, 41 does not.

**Comment by mmachatschek** [comment]
having pages return more than 1.000 items is not the typical use case. The hard limit is more or less a "security" feature of meilisearch. For your specific use case, you must set the `maxTotalHits` on the index pagination setting. There is nothing we can do from scout side.


https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0#:~:text=Limit%20of%20documents%20returned%20by%20search

**Comment by JerryBels** [comment]
I kindly disagree with you. When you have an e-commerce, returning more than 1000 items is a very common use case. I'm building a CRM, and returning thousands of items is usual. I don't have a problem that I can't resolve, indeed I can set the param, as I said above, but a bug remains for scout. And I think Scout should limit the number of pages according to the hard limit, maybe using a config parameter or something like that.

**Comment by JerryBels** [comment]
So it looks like Meilisearch themselves are making enhancements for pagination systems : https://github.com/meilisearch/meilisearch/discussions/2635

Apparently this should be in v0.30 of Meilisearch. I suggest we wait and make use of it when it's out, it should be pretty easy to fix scout's bug with it.

**Comment by mmachatschek** [comment]
@JerryBels on a second glance, it looks like you are talking about two separate issues? At one side, that there are not more than 1.000 results returned by meilisearch and the second issue, you encounter is the mismatch of the total hits.

for the second issue, you are right, there is a new pagination api that solves these issues. Check this PR for more info on whats changing on scout side, as soon as this new pagination api is released https://github.com/laravel/scout/pull/666

**Comment by JerryBels** [comment]
Well, I was talking only about one issue, the second you name, but it looks like you guys were already on it, and this new pagination api will indeed fix the problem. The first is not an issue as it is configurable. Since you were already aware of this and the PR is already packed and waiting, I'm closing this issue.
