### ISSUE TITLE
Can't populate _geo field in meilisearch from Scout

### ISSUE THREAD

**Issue by cs-media** [laravel/scout#668]
- Scout Version: 9.4.12
- Scout Driver: Meilisearch v0.29
- Laravel Version: 9.39.0
- PHP Version: 8.1.10
- Meilisearch CLI Version: 0.25.0

### Description:
I'm using scout and Meilisearch and can't seem to populate the _geo field with a float or a string.

public function toSearchableArray()
 {
     return [
         'lat' => (float) $this->address->lat,           // WORKS FINE
         'lng' => (float) $this->address->lng,         // WORKS FINE
         '_geo' => [                                                  // EMPTY
                'lat' => (float) $this->address->lat,    // NOT SHOWN
                'lng' => (float) $this->address->lng,  // NOT SHOWN
          ]
    ];
 }

Is this the correct syntax to send a _geo object to Meilisearch from Scout? I can't see anything in the Scout documentation on how to send data in this format, the Meilisearch documentation says:

> "When using JSON and NDJSON, _geo must contain an object with two keys: lat and lng. Both fields must contain either a floating point number or a string indicating, respectively, latitude and longitude:"

`{
  …
  "_geo": {
    "lat": 0.0,
    "lng": "0.0"
  }
}`

Any help getting this working would be greatly received :)

**Comment by cs-media** [comment]
I've just tried adding (object), flushing and reimporting and it's the same.

**Comment by mmachatschek** [comment]
The code looks ok. I suppose the index is not configured for geo functionallity.

@cs-media please ask on the corresponding meilisearch slack channels. They are really helpful when you have any questions about configuring or support questions.

Laravel Scout seems to work ok here 👍

**Comment by driesvints** [comment]
Thanks @mmachatschek

**Comment by cs-media** [comment]
For anyone else struggling with this, the _geo data is being stored, but the Meilisearch Dashboard doesn't output the _geo fields. A search via curl showed the lat and lng just fine.

A GitHub issue has created to resolve this: [https://github.com/meilisearch/mini-dashboard/issues/358](https://github.com/meilisearch/mini-dashboard/issues/358)
