### ISSUE TITLE
DB Transaction rollBack, search index still updated

### ISSUE THREAD

**Issue by tommy66374** [laravel/scout#673]
- Scout Version: 9.5.1
- Scout Driver: MeiliSearch
- Laravel Version: 9.43.0
- PHP Version: 8.1.12
- Database Driver & Version: (Homestead) mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
- SDK Version (If using a third-party service): "http-interop/http-factory-guzzle": "^1.2",
- Meilisearch CLI Version (If using Meilisearch): "meilisearch/meilisearch-php": "^0.26.0"

### Description:

DB Transaction rollBack, and go to `http://my-project.test:7700` , search the record of the post, the field is updated to new value.

expect the index record of the post is unchanged

### Steps To Reproduce:

scout.php

```
    'after_commit' => true,
```

Controller

```
    public function update(StorePostRequest $request, Post $post)
    {
        try
        {
            DB::beginTransaction();

            $post->update($request->validated());
            $post->searchable();

            throw new Exception('Update error.');

            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();

            return back()->withInput();
        }

        return to_route('posts.show', $post);
    }
```

I haven't tested create() , destroy() , restore() , forceDelete() in the controller

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
