### ISSUE TITLE
Class Laravel\Scout\Console\Str not found

### ISSUE THREAD

**Issue by Gsuper36** [laravel/scout#679]
- Scout Version: 9.6.1
- Scout Driver: custom OpenSearch
- Laravel Version: 8.83.27
- PHP Version: 7.4

### Description:
Missing use Illuminate\Support\Str statement in DeleteIndexCommand

### Steps To Reproduce:
php artisan scout:delete-index {name}

https://github.com/laravel/scout/blob/9.x/src/Console/DeleteIndexCommand.php#L56

**Comment by driesvints** [comment]
Thanks. I released a patch version that should fix this.
