### ISSUE TITLE
The query callback takes a lot of memory.

### ISSUE THREAD

**Issue by reefki** [laravel/scout#680]
- Scout Version: 9.6.2
- Scout Driver: MeiliSearch
- Laravel Version: 9.45.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8
- SDK Version (If using a third-party service): meilisearch/meilisearch-php 0.26.1

### Description:
The query callback takes a lot of memory. 

### Steps To Reproduce:

PHP Debug Bar performance results with query callback vs without query callback

```
Entry::search('')->paginate()
```
![Screen Shot 2022-12-25 at 05 29 38](https://user-images.githubusercontent.com/10998084/209452527-c5f0a383-26f1-4741-994c-fe452f238b16.png)

```
Entry::search('')->query(fn ($query) => $query)->paginate()
```
![Screen Shot 2022-12-25 at 05 29 06](https://user-images.githubusercontent.com/10998084/209452531-155d4703-318a-4c9f-8c60-4c3c2c18c805.png)

**Comment by reefki** [comment]
After some digging, The `getTotalCount()` seems to be the cause https://github.com/laravel/scout/blob/9.x/src/Builder.php#L384

My temporary solution is creating a custom macro for paginating the results and using `nbHits` value as the paginator total value. This is maybe not a good solution but at least it is faster and more memory friendly.

**Comment by driesvints** [comment]
This is expected. If you use a custom `queryCallback` then we'll need to fetch the ID's separately and do a manually count based on the amount of them. This results in a lot more memory being used.
