### ISSUE TITLE
Support Search Parameters in Scout for MeiliSearch

### ISSUE THREAD

**Issue by lucasRolff** [laravel/scout#682]
It would be super nice to support the various Search Parameters from MeiliSearch, especially the matching strategy ( https://docs.meilisearch.com/reference/api/search.html#matching-strategy ) - in some cases the "last" strategy isn't ideal when one wants to do somewhat strict searches.

**Comment by driesvints** [comment]
Heya, I sent in a PR. Can you try it out to see if that works for you and reply on the PR? https://github.com/laravel/scout/pull/683
