### ISSUE TITLE
Separate query callback for eager loading relationships.

### ISSUE THREAD

**Issue by leroy** [laravel/scout#684]
Happy new year!

Currently, we're using Scout in combination with Meilisearch. The following code uses a query callback to enrich the result with relationship data and pagination.

```php
$products = $query
            ->query(fn ($query) => $query->with([
                'baseproduct',
                'baseproduct.brand',
                'baseproduct.category',
                'baseproduct.parentmodel',
                'baseproduct.submodel', ]
            ))
            ->paginate();
```

Currently the pagination in the `Scout\Builder` refetches the results from the engine whenever a query callback is defined. On our end this results in a slower response because the `Scout\Builder` queries the engine for a result of all the records to get a total count result.

This was changed in commit https://github.com/laravel/scout/commit/675364316737203415fecdc5af9bdefe5fb3e238

However whenever a query callback is defined to specify eager loading this should not be necessary because the query result wouldn't differ.

My proposal would be to add a specific callback on the `Scout\Builder` to specify any eager loading the developer wants to do.

```php

Model::search()->with(function($builder) { $builder->with() })

```

If this could be a viable solution let me know and I will create PR to implement this.

**Comment by taylorotwell** [comment]
Hey there!

Whether a PR would be accepted for this really just depends on the complexity of the PR and the benefit it imparts. Thanks!
