### ISSUE TITLE
Does not register with Meilisearch

### ISSUE THREAD

**Issue by leeweaver2222** [laravel/scout#692]
- Scout Version: #0.7..1
- Scout Driver: / MeiliSearch / Database / Collection
- Laravel Version: 9
- PHP Version: 8
- Database Driver & Version: SQL
 - SDK Version (If using a third-party service): #.#.#
- Meilisearch CLI Version (If using Meilisearch): 0.30..5

### Description:
When installing Scout Driver everything is ok

When installing Meilisearch and using 

php artisan scout:import "App\Models\Product"

The error comes up 
Undefined variable $meilisearchClientClassName

After looking on the Meilisearch Website Laravel Scout is not connecting with the configuration.

Downgraded to Laravel Scout 0.7.0 the previous version to reproduce the error the error disapeared.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
