### ISSUE TITLE
Laravel Nova Search Relationship With Scout

### ISSUE THREAD

**Issue by nouman-ashraf-awan** [laravel/scout#704]
- Scout Version: 9.4
- Scout Driver: Typesense
- Laravel Version: 8.0
- PHP Version: 8.0
- Typesense Version: 5.0

In Laravel Nova, With belongsToMany relationship on the search bar, search apply on all models without filtering on the relation models only. It's working without scout but not with. Is it a bug or am i missing something ?

**Comment by driesvints** [comment]
Please report this to Nova instead.

**Comment by crynobone** [comment]
This has been reported and fixed (https://github.com/laravel/nova-issues/issues/5307). It will be available on the next release.

**Comment by nouman-ashraf-awan** [comment]
@crynobone We are using Nova 3. Will it be supported for previous versions too.

**Comment by marijoo** [comment]
@crynobone This still applies to Nova 4 – using the latest version here and this is still happening.
