### ISSUE TITLE
Not possible to index in descending order

### ISSUE THREAD

**Issue by patriziotomato** [laravel/scout#706]
- Scout Version: v9.8.1
- Scout Driver: ElasticSearch
- Laravel Version: 10.1
- PHP Version: 8.2

### Description:

Since the Query Builder Macro is using `chunkById()` which iterates using the `forPageAfterId()` method, which itself is assuming the you're IDs are incremeting, the `$builder->macro('searchable')` is not working together with a custom order like this:

```php
    public function makeAllSearchableUsing($query): Builder
    {
        return $query->latest();
    }
```

### Steps To Reproduce:

```php
    public function makeAllSearchableUsing($query): Builder
    {
        return $query->latest();
    }
```

This indexes only one iteration without any failure.

Solutions:
- Add note to documentation, that changing the sorting is not supported and causes undefined trouble
- Validate whether a "manual" sorting has been set and throw an Exception
- Change the iteration behavior to support a custom sorting

Then index like this

```php
        $query = $self->newQuery()
            ->when(true, fn($query) => $self->makeAllSearchableUsing($query))
            ->when($softDelete, fn($query) => $query->withTrashed())
            ->when($this->limit, fn($query) => $query->limit($this->limit))
            ->searchable()
```

**Comment by driesvints** [comment]
Changing sorting indeed isn't allowed as that's handled by the search engine. Feel free to send in a PR to the docs 👍
