### ISSUE TITLE
Scout v10 release with Meilisearch v1.0 support

### ISSUE THREAD

**Issue by pedzed** [laravel/scout#707]
I have upgraded my project to Laravel 10. Unfortunately, Meilisearch v1.0 gives errors in my unit tests (https://github.com/meilisearch/meilisearch-php/issues/468). My understanding is that Scout v10 is supposed to support Meilisearch v1.0, but the current Scout 10.x-dev is seemingly not yet ready for release.

As Laravel 10 is already released, I am wondering if Scout v10 will be released as well soon, with support for Meilisearch v1.0?

**Comment by driesvints** [comment]
It's coming very soon. Everything is ready on the 10.x branch.
