### ISSUE TITLE
loses relationships on import

### ISSUE THREAD

**Issue by veneliniliev** [laravel/scout#708]
- Scout Version: 9.8.1
- Scout Driver: MeiliSearch
- Laravel Version: 9.52.4
- PHP Version: 8.1.12
- Database Driver & Version: MySQL 8
- SDK Version (If using a third-party service): 1.0.0
- Meilisearch CLI Version (If using Meilisearch): 1.0.2
- Queue driver: Horizon 5.14.2

### Description:
I have a model with relations in `makeAllSearchableUsing`:
`
$query ->with([
                'parent.parent.parent'
            ]);
`

When the data is imported, some of the relationships are lost. in many cases, sub-relations are lost.

In horizon jobs `Laravel\Scout\Jobs\MakeSearchable` are seen:
`
"relations":
{
"0":
"parent"
},
`

In the model method `toSearchableArray` i have a recursive function to get all names of parents and check `$model->relationLoaded('parent')`. Some of the models don't have all sub-relations.

**Comment by driesvints** [comment]
Right now, it's not possible to load these relationships with Scout. Only basic searching and loading of models is possible.
