### ISSUE TITLE
Error while persisting update to disk: Too many open files

### ISSUE THREAD

**Issue by diazsasak** [laravel/scout#722]
- Scout Version: v9.5.1
- Scout Driver: Meilisearch
- Laravel Version: v9.43.0
- PHP Version: 8.1.16
- Database Driver & Version: MySQL 8.0.32-0ubuntu0.20.04.2
- Meilisearch CLI Version (If using Meilisearch): v0.25.2

### Description:

I got this error in the background, is laravel scout execute too many MakeSearchable Jobs? 

An internal error has occurred. `Error while persisting update to disk: Too many open files (os error 24) at path "/./data.ms/updates/updates_files/.tmp4wVqV6"`.

stacktrace:

/var/www/acme/vendor/meilisearch/meilisearch-php/src/Http/Client.php:184
--
/var/www/acme/vendor/meilisearch/meilisearch-php/src/Http/Client.php:116
/var/www/acme/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesDocuments.php:30
/var/www/acme/vendor/laravel/scout/src/Engines/MeiliSearchEngine.php:74
/var/www/acme/vendor/laravel/scout/src/Jobs/MakeSearchable.php:42
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/Container.php:651
/var/www/acme/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:128
/var/www/acme/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/var/www/acme/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/var/www/acme/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:132
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:124
/var/www/acme/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/var/www/acme/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:116
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:126
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:70
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:98
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:425
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:375
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:173
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:146
/var/www/acme/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:130
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/Util.php:41
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
/var/www/acme/vendor/laravel/framework/src/Illuminate/Container/Container.php:651
/var/www/acme/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
/var/www/acme/vendor/symfony/console/Command/Command.php:312
/var/www/acme/vendor/laravel/framework/src/Illuminate/Console/Command.php:152
/var/www/acme/vendor/symfony/console/Application.php:1020
/var/www/acme/vendor/symfony/console/Application.php:312
/var/www/acme/vendor/symfony/console/Application.php:168
/var/www/acme/vendor/laravel/framework/src/Illuminate/Console/Application.php:102
/var/www/acme/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:155
/var/www/acme/artisan:37

Thank you for your help

### Steps To Reproduce:

the error triggered without user interaction, it happen in the background at the random time.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Also please try meilisearch support first, thanks.
