### ISSUE TITLE
Import query duplicates key column in orderBy causing SQL exception

### ISSUE THREAD

**Issue by gdesoto** [laravel/scout#723]
- Scout Version: 10.0.2
- Scout Driver: tntsearch (12.4.0)
- Laravel Version: 10.5.1
- PHP Version: 8.1.13
- Database Driver & Version: SQL Server 2017 (Microsoft ODBC Driver 17 for SQL Server)
- SDK Version (If using a third-party service): #.#.#
- Meilisearch CLI Version (If using Meilisearch): #.#.#

### Description:
When running the scout:import command for a model, the following error is thrown while the command gets all searchable models from a MS SQL Server database.

> Illuminate\Database\QueryException
> 
> SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique. (Connection: default, SQL: select top 500 * from [users] order by [users].[id] asc, [id] asc)

The `makeAllSearchable` method in `src/Searchable.php` called by the import command adds an `orderBy` on the primary scout key prior to the calling `searchable()` macro. The searchable macro defined in `src/SearchableScope.php` then calls Eloquent's `chunkById` method which adds its own `orderBy` on the model's primary key. When both keys are the same, an error will be thrown.

This issue seems to have started with this change to use `qualifyColumn` method in the `orderBy` [#509](https://github.com/laravel/scout/pull/509#issuecomment-903721511). As a test, I reverted this line and no error was thrown.

Laravel's `chunkByID` method removed existing "orders" for a query prior to adding its own which explains why it didn't throw an error prior to this change. Since `[users].[id] !== [id]` it isn't removed from the query anymore, and now throws the error.

Assuming moving to qualifying column names is the future, then a possible solution may be to find a way to pass the results of `qualifyColumn()` to `chunkById` as the third parameter. Something like...
```diff
        $builder->macro('searchable', function (EloquentBuilder $builder, $chunk = null) {
            $builder->chunkById($chunk ?: config('scout.chunk.searchable', 500), function ($models) {
                $models->filter->shouldBeSearchable()->searchable();

                event(new ModelsImported($models));
-            });
+            }, $builder->qualifyColumn($builder->getModel()->getScoutKeyName()));
        });
```

I haven't tested in other database environments. I didn't come across any other reports of this issue when searching, so I'm thinking other database engines must ignore the duplicated column names in the orderBy query.

### Steps To Reproduce:

1. SQL Server environment
2. Populate database with an Eloquent model for use with Scout (ie: users). Ensure the model's primary key name and scout key name as the same (default).
3. Run the command: `php artisan scout:import "App\Models\User"`
4. Get the error.

**Comment by driesvints** [comment]
Thanks for the great issue report @gdesoto. I *think* you're correct here but want to check with @mmachatschek if he feels the same?

**Comment by mmachatschek** [comment]
@driesvints the issue report looks plausible to me too. would be great to have some kind of test for this issue so we don't miss this in the future if you can come up with one @gdesoto.

**Comment by nunomaduro** [comment]
@gdesoto Are you able to make a pull request fixing the issue you have described, along with corresponding tests?

**Comment by nunomaduro** [comment]
Currently working in a pull request, so lets keep the discussion on there: https://github.com/laravel/scout/pull/740. Also, do you mind of trying the code on that pull request @gdesoto, and let me know if it fixes your issue?
