### ISSUE TITLE
Support for composite full-text indexes in database driver

### ISSUE THREAD

**Issue by ArondeParon** [laravel/scout#724]
It seems like the database driver currently does not support composite full-text indexes.

**Example:**

If annotating my model with the following attribute:

```php
#[SearchUsingFullText(['title', 'content', 'summary'])]
```

I would expect the database to perform this query:

```SQL
MATCH (title, content, summary) AGAINST ('term')`
```

Instead, it does this:

```SQL
WHERE
    MATCH (title) AGAINST ('term')
OR
    MATCH (content) AGAINST ('term')
OR
    MATCH (summary) AGAINST ('term')
```

This makes a crucial difference when using a composite index. In the first case, the query would work as expected, but in the last case, the composite index is ignored and this can even cause query errors because the individual indexes might be missing.

**Comment by driesvints** [comment]
We'd appreciate a PR to support this 👍
