### ISSUE TITLE
Set Limit in My Query

### ISSUE THREAD

**Issue by joaopalopes24** [laravel/scout#725]
### Scout Version

10.0.2

### Scout Driver

Meilisearch

### Laravel Version

10.5.0

### PHP Version

8.2.4

### Database Driver & Version

MariaDB 10.7.8

### SDK Version

1.0.0

### Meilisearch CLI Version

1.1.0

### Description

I'm performing a search via Laravel Scout Builder, and I want to bring all my data, so I set a limit equal to 10,000, but my result is always limited to a thousand results, even changing the limit.

`ContactMessage::search()->take(10000)->get();`

![image](https://user-images.githubusercontent.com/45684782/230486426-e839ce3d-6b71-4227-b4a7-e252036674b9.png)

And in my database, we have over a thousand records.

### Steps To Reproduce

Create a table with over a thousand records, and try to bring everything in using the limit.

**Comment by joaopalopes24** [comment]
Using the Scout count, and below the actual amount in the database.

`ContactMessage::search()->take(10000)->count();`

![image](https://user-images.githubusercontent.com/45684782/230487698-17912674-8ab8-4c51-8e7b-424045bbafe4.png)

**Comment by mmachatschek** [comment]
@joaopalopes24 this is the maxTotalHits setting on meilisearch side which prevents users from scrapping the whole data of a meilisearch DB.

this is the setting (which is by default max 1000 items returned) https://docs.meilisearch.com/reference/api/settings.html#pagination

**Comment by driesvints** [comment]
Thanks @mmachatschek. Wondering if we should note this in the docs because this seems to keep popping up.

**Comment by mmachatschek** [comment]
@driesvints it may be worth mentioning in the docs

**Comment by driesvints** [comment]
@mmachatschek done: https://github.com/laravel/docs/pull/8704

**Comment by joaopalopes24** [comment]
Thank you @mmachatschek @driesvints
