### ISSUE TITLE
InvalidArgumentException 

### ISSUE THREAD

**Issue by mobinaghashahi** [laravel/scout#731]
### Scout Version

3.0.0

### Scout Driver

Algolia

### Laravel Version

10.8.0

### PHP Version

8.1

### Description

hi.
I want to use Algolia and done all step by step documentation but when use `php artisan scout:import` occur a error. error say  

> InvalidArgumentException 
> 
>   json_decode error: Syntax error
> 
>   at vendor\algolia\algoliasearch-client-php\src\Support\Helpers.php:112
>     108▕     public static function json_decode($json, $assoc = false, $depth = 512)
>     109▕     {
>     110▕         $data = \json_decode($json, $assoc, $depth);
>     111▕         if (JSON_ERROR_NONE !== json_last_error()) {
>   ➜ 112▕             throw new \InvalidArgumentException('json_decode error: '.json_last_error_msg());
>     113▕         }
>     114▕
>     115▕         return $data;
>     116▕     }
> 
>   1   vendor\algolia\algoliasearch-client-php\src\RetryStrategy\ApiWrapper.php:214
>       Algolia\AlgoliaSearch\Support\Helpers::json_decode("<html>
> <head><title>403 Forbidden</title></head>
> <body>
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ")
> 
>   2   vendor\algolia\algoliasearch-client-php\src\RetryStrategy\ApiWrapper.php:167
>       Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper::handleResponse(Object(GuzzleHttp\Psr7\Response), Object(Algolia\AlgoliaSearch\Http\Psr7\Request))

you can help me?!
tnks, Mobin Aghashahi :heavy_heart_exclamation:

### step1: 
`composer require "algolia/scout-extended:^2.0"`

### step2:
`php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"`

### step 3: import Searchable to Model
```
namespace App;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use Searchable;
}
```
### step4: Configure API keys 
```
ALGOLIA_APP_ID=DGYZLLYAER
ALGOLIA_SECRET=YourWriteAPIKey

```
### step5: (occur Error on this step):
`php artisan scout:import
`

**Comment by driesvints** [comment]
we unfortunately don't provide support for algolia/scout-extended. Please try their issue tracker or a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
