### ISSUE TITLE
Custom page name is not taken into account.

### ISSUE THREAD

**Issue by jago86** [laravel/scout#735]
### Scout Version

9.8.1

### Scout Driver

Database

### Laravel Version

10.10.0

### PHP Version

8.1.18

### Database Driver & Version

Sqlite 3

### Description

Apparently this is a bug in version 9 of Scout, version 10 does not have this problem.

When a custom parameter name is specified for a pagination. The custom name is not applied to the generated links.

```php
$users = \App\Models\User::search('Ma')
        ->paginate(2, 'mi_custom_page');
```

![imagen](https://github.com/laravel/scout/assets/1690276/2972e4a3-2d3b-4d09-829a-cb10da642400)

### Steps To Reproduce

I created a repo reproducing the bug. You can find it in: https://github.com/jago86/bug-report
If you want to reproduce manually, here are the steps.

## Steps
- Create a fresh laravel instalation.

- Create a `database.sqlite` in database folder (database/database.sqlite)

- Migrate and seed database (use the default database/factoriesUserFactory to create 100 users).

- Install laravel-scout 

```bash
composer require laravel/scout ^9.8
```

- Publish Scout configuration

```bash
php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"
```

Add the `Laravel\Scout\Searchable` trait to the User model and define the **toSearchableArray()** method.

```php
use Laravel\Scout\Searchable;
use Laravel\Scout\Attributes\SearchUsingPrefix;

class User extends Authenticatable
{
    use Searchable, HasApiTokens, HasFactory, Notifiable;
		....
		....
		....

		#[SearchUsingPrefix(['name'])]
    public function toSearchableArray(): array
    {
        return [
            'name' => $this->name,
        ];
    }
}
```

Set the driver to database in .env file

```php
SCOUT_DRIVER=database
```

Search a name in home route (web.php) and pass the results to welcome view. In the paginate method, pass as a second parameter a custom name for the pagination param.

```php
Route::get('/', function () {
		// Search some name that matches with some fields in your database
    $users = \App\Models\User::search('ma')
        ->paginate(2, 'mi_custom_page');

    return view('welcome', ['users' => $users]);
});
```

Somewhere in the welcome view, render the results and the links.

```php
<ul>
    @foreach ($users as $user)
        <li>{{ $user->name }}</li>
    @endforeach
</ul>
<div>{{ $users->links() }}</div>
```

## Expected behavior

The generated links should has the page number under **mi_custom_page** query param, like this 

```php
http://scout-test.test/?query=ma&mi_custom_page=2
```

## Current behavior

The generated links has page number under **page,** ignoring the configured name in **->paginate(2, 'mi_custom_page').**

```php
http://scout-test.test/?query=ma&page=2
```

I can work on a solution to make a PR.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
