### ISSUE TITLE
Scout 10.2.0 - Undefined method makeSearchableUsing

### ISSUE THREAD

**Issue by jonathan-bird** [laravel/scout#736]
### Scout Version

10.2.0

### Scout Driver

Algolia

### Laravel Version

10.10.1

### PHP Version

8.2.5

### Database Driver & Version

8.0.32

### Description

Getting a `Call to undefined method App\Models\Sync\StockProduct::makeSearchableUsing()` error from the `MakeSearchable` job.

Seems that because it's protected, the job cannot call the method.

I tried simplifying my model down and calling my `makeSearchableUsing` from there incase it was a weird issue where I forgot to call `parent::boot()` in my model, but no luck. 

### Steps To Reproduce

1. Create model
2. Set `use Searchable`
3. Setup Scout to use queue
4. Update model (which triggers job)
5. See error caused from the `MakeSearchable` job

OR call `makeSearchableUsing` from the model, which will fail due to being protected.

**Comment by mstaack** [comment]
yes, same for me

**Comment by gdebrauwer** [comment]
I created a PR to fix this https://github.com/laravel/scout/pull/738

**Comment by nunomaduro** [comment]
Fixed on Scout `v10.2.1`.
