### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by mix359** [laravel/scout#744]
Hi to all,

I'm using scout from many years and I always had one main problem, that I have to solve in some way in all of the projects, hacking around the code:
Having a way to use advanced filtering on a search:

All the platform I know have a way to do search using operator like >, <, >=, <=, and advanced operation like checking field existence/non existence, or searching a list of value.
As far as I can see, both Algolia, Meilisearch, Elasticseach and sql can support those operation.
Also, those operation are available on the DatabaseBuilder/EloquentBuilder so every time you have to use scout instead of the database, you have less operator available because of the basic interface.

So I would like to understand if there's a reason why this feature is not implemented?

Eventually I've seen the work from [alibadd](https://github.com/alibaddd/scout) that it's implementing those features.
Is there a chance that those feature can be integrated here?
What requirement does have to pass to have them here?

Thanks
Cheers
Mix

**Comment by driesvints** [comment]
Any search operators are limited by the engine itself. Right now, Scout provides support for `where`/`whereIn` etc. If you could send in a PR with support for more operands, we could maybe have a look. Thanks!
