### ISSUE TITLE
`scout:status` does not show status for models outside App/Models directory

### ISSUE THREAD

**Issue by nasirkhan** [laravel/scout#749]
### Scout Version

^10.2

### Scout Driver

Collection

### Laravel Version

v10.14.1

### PHP Version

8.1.4

### Database Driver & Version

mysql 8

### Description

Recently I started to use Scout and enabled searchable for a number of models. When I run `scout:import` for a model it shows a success message and also shows the search results as expected. 

But all my models are not located under the `App/Models`.  And when I run the `scout:status` command it only shows the status for the models located in the default model directory. 

How can I include other model paths and get the status? 

### Steps To Reproduce

1. use Searchable on 2 models. one Should be under the `App\Models` directory and another could be located any place other than  `App\Models` 
2. `scout:import` both models 
3. run the command `scout:status`
4. the command in step 3 will only show the model status which is located in `App\Models`

**Comment by mmachatschek** [comment]
There is no such command called `scout:status` in this repo. You are probably mixing it up with this repo https://github.com/algolia/scout-extended
