### ISSUE TITLE
Apply global to Scout search

### ISSUE THREAD

**Issue by fusionconsulting** [laravel/scout#753]
### Scout Version

10.2

### Scout Driver

Meilisearch

### Laravel Version

10.4.1

### PHP Version

8.2

### Database Driver & Version

Mysql 8.0

### SDK Version

1.1.1

### Meilisearch CLI Version

1.1.1

### Description

Not sure if this is a bug or a request but when applying global scopes to a Searchable model they are applied after the Scout search to the Eloquent load which makes the pagination incorrect. It would be good to be able to apply a global scope to the Scout builder.

I have a Searchable model which includes a user ID in the filterableAttributes. I also have a global scope to restrict results to the logged in user:

    public function apply(Builder $builder, Model $model): void
    {
        $builder->where('user_id', $this->user->id);
    }

This returns a total count of the number of records in the Scout index but shows 0 results in the paginator items. This is because the scope is applied to the Eloquent query after the Scout search.

Is there a way to apply a global scope to the Scout builder or perhaps a better approach?

### Steps To Reproduce

Apply a basic where scope to a Searchable model. 

The scope will be applied after the Scout search.

**Comment by crynobone** [comment]
Unfortunately, this is something that can't be automated without completely revamping paginated results by getting the full IDs and only generating a new eloquent query with the above scope `whereIn` results ID. 

A simple solution you can do right now is to re-add the logic manually: https://laravel.com/docs/10.x/scout#where-clauses
