### ISSUE TITLE
Setting a queue override per model

### ISSUE THREAD

**Issue by jeffhuys** [laravel/scout#762]
Hi there! In the project I'm working on, we're implementing the `Searchable` trait to more and more of our models.
As this number grows, the amount of jobs in our `jobs` table has grown substantially, causing our search indexes to lag behind a lot.

This means that when we (for instance) update a news article, it will only be updated in the search index hours (if not days) later.

What would really help here is that we could specify a custom queue name in a model, and have multiple workers listen on these queues. This way, high-priority items are not handled with the same priority as all the other `scout`-queue items.

Currently, I'm manually fixing this by setting the `id` of the jobs that must be online right now to `1`. Of course, this is not ideal.

Is there a way to do this already, or is this something that could be a nice addition?

Thanks for reading, and thanks for this great package.

**Comment by crynobone** [comment]
Scout already provides `syncWithSearchUsing()` and `syncWithSearchUsingQueue()` which you can override if you want to.
