### ISSUE TITLE
Can't index documents without PK on Oracle

### ISSUE THREAD

**Issue by xorock** [laravel/scout#763]
### Scout Version

*

### Scout Driver

Meilisearch

### Laravel Version

10.22.0

### PHP Version

8.2

### Database Driver & Version

OCI8 yajra/laravel-oci8

### Meilisearch CLI Version

1.3

### Description

I am working with Oracle version 12c. The table from which the data is retrieved does not have a primary key but there are 2 candidate columns from which this key can be created for meilisearch. The problem is with generating a valid query when indexing the table.

```
    public $incrementing = false;

    protected $primaryKey = 'ndi';

    public function toSearchableArray(): array
    {
        return [
            'id' => $this->getScoutKey(),
            // ...other columns
        ];
    }

    public function getScoutKeyName(): string
    {
        return 'id';
    }

    public function getScoutKey(): string
    {
        return sprintf('%s-%s', $this->ndi, $this->nda);
    }
```

Now, I can override protected function **makeAllSearchableUsing**, alias ID column in raw db select, but scout library enforces full name in order by:

```sql
ORA-00904: "TABLE_NAME"."ID": invalid identifier
Position      : 57
Statement     : select /*+ FIRST_ROWS(500) */ * from "TABLE_NAME" order by "TABLE_NAME"."ID" asc offset 0 rows fetch next 500 rows only
```

Unfortunately, adding an orderBy clause combines the default clause with the custom one.

### Steps To Reproduce

create table without PK
try to override scout key
import with php artisan scout:import "App\Models\TABLE_NAME"

**Comment by driesvints** [comment]
Unfortunately we don't support Oracle databases, sorry. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by xorock** [comment]
Ok, but it is related to https://github.com/laravel/scout/pull/509 and qualifyColumn. It enforces table name so can't use alias or any other solution.
