### ISSUE TITLE
Feature request: Provide contract to go with Searchable trait methods

### ISSUE THREAD

**Issue by jnoordsij** [laravel/scout#771]
Currently there is no trivial way to mark e.g. variables or method arguments as searchable, allowing for calls to searchable-related methods static analysis can understand. Adding a contract with signatures for a set of important public methods would allow for better static analysis, using e.g. `phpstan`/`larastan`.

A particular case where this might be helpful is the current phpstan failure on the [`algolia/scout-extended`](https://github.com/algolia/scout-extended) repo,
see e.g. https://app.circleci.com/pipelines/github/algolia/scout-extended/255/workflows/ec6dc973-ce16-4d43-82e8-a61c2b2b4cd4/jobs/2079/parallel-runs/0/steps/0-109.

**Comment by driesvints** [comment]
Thanks. Right now we don't optimize for static analysis specifically. If you want to make a proposal that we can review, we'd appreciate a PR.
