### ISSUE TITLE
MakeSearchable job runs even if model was not changed

### ISSUE THREAD

**Issue by nesh-ua** [laravel/scout#774]
It is because:
`The saving / saved events will dispatch when a model is created or updated - even if the model's attributes have not been changed`
But why we need run MakeSearchable if model was not changed?
Maybe it could be better to use created and updated event instead saved in model observer?

**Comment by driesvints** [comment]
I'm not sure there's an issue here currently. Scout runs fine in production for many apps. We haven't gotten any reports about things going wrong with too many `MakeSearchable` job runs.
