### ISSUE TITLE
Relationship with ManyToMany

### ISSUE THREAD

**Issue by Abhi0725** [laravel/scout#775]
### Scout Version

10.5.0

### Scout Driver

Meilisearch

### Laravel Version

10.27

### PHP Version

8.1.13

### Database Driver & Version

MySQL 8 for Intel MacOS

### Description

I am trying to query products table which has various categories. 

For e.g Iphone 15 can belong to 'phones', 'gadgets', 'touchscreens' etc.

So basically Product has ManyToMany relationship with Category.

How can I simply filter it with scout? I can do it with user_id though which is in the products table but what about the many-to-many relation?

I did add all the names as attributes in `toSearchableArray ` but obviously that is searching not "filtering".

Any ideas how this can be done?

### Steps To Reproduce

Simply try to filter Many to many relationships.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
