### ISSUE TITLE
Scout currently supports where clause that uses equal (=) operator only. Additional comparison (i.e >, >=, < ...) operation support is required. 

### ISSUE THREAD

**Issue by rrakibul** [laravel/scout#776]
### Description

Hey, 

I added laravel scout package to my laravel 10 project to use locally installed meilisearch in my machine. 

Meilisearch filter currently supports extensive comparison operations like `!=, >, >=, <, <=, TO` 

However scout currently supports where clause that uses equal (=) operator only. Additional comparison operation support is required.

**Comment by driesvints** [comment]
Welcoming PRs, thanks.

**Comment by DurandSacha** [comment]
to increase the capabilities of the searchable object with other operators, there is currently a solution which consists in adding the library [Jeroen-G/Explorer](https://github.com/Jeroen-G/Explorer) ,

example with OR operator : 

`
      $subQuery = new BoolQuery();
      $subQuery->should(new Matching('field1', 'A'));
      $subQuery->should(new Matching('field1', 'B'));
      $search->must($subQuery);
`
