### ISSUE TITLE
Support queryCallback in CollectionEngine

### ISSUE THREAD

**Issue by Peterragheb** [laravel/scout#784]
I'm not sure this is the right place to ask this question. 

I noticed while using scout's CollectionEngine that I'm getting a lazy loading issue while searching on a model with a searchable relationship.

I tried applying a query callback on the scout builder however I noticed that the queryCallback is only called when the engine is database. I'm assuming this behavior is intentional. 

I'm wondering though why not add support for it on the CollectionEngine as well?

**Comment by driesvints** [comment]
Heya, I'm not sure about this sorry. If you want, you can attempt a PR to add it to the CollectionEngine as well and see if Taylor accepts it. Thanks
