### ISSUE TITLE
Formatting data based on the search field

### ISSUE THREAD

**Issue by hebertlima** [laravel/scout#785]
In a scenario where masking and formatting of values are not saved in the database, is there a way to sanitize these fields before conducting a search?

For example:
In the database, the "doc" field is stored as: 4444444444, while the input for searching is 44.444.444-44.

When I perform the search like this: 44.444.444-44, it doesn't yield any results. 

It only works if I search exactly like this: 4444444444.

Something like:

```php
public function transformData()
{
    return [
        'doc' => preg_replace('/\D/', '', $this->query('doc')),
    ];
}
```

I am using the same field to search for names, emails, etc.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
