### ISSUE TITLE
Scout import command didn't indexed all the records in meilisearch

### ISSUE THREAD

**Issue by RafficMohammed** [laravel/scout#786]
### Scout Version

10.5

### Scout Driver

Meilisearch

### Laravel Version

9

### PHP Version

8.1

### Meilisearch CLI Version

1.5

### Description

I have around 1M records in the ticket_thread table.

\Artisan::call('scout:import', ['model' => "$modelQuery"]);

Then I tried to import an existing record from the above command. It's imported but I'm not able to search the latest data.

When I tried with code,
                $modelQuery::orderBy('id', 'desc')->chunk(500, function ($q) {
                    $q->searchable();
                });
                
It's working. But it's taking too much time to complete this command. Any solution ? 

### Steps To Reproduce

Create 1M records with different date creation(Data should be created from before two year to till now

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
