### ISSUE TITLE
Implementing Global Search

### ISSUE THREAD

**Issue by n4p4** [laravel/scout#79]
I want to implement global search in Scout, where I'm able to search in ALL models and get results ranked by relevancy, which Sphinx allows you to do, but I'm facing a few problems. One such problem is I don't know where to add the global search method. I tried creating a class that extends the engine that I'm using and overriding the search method, but when I try to search it complains that a Builder object was not given but instead a string was given, altho I type-hinted the Builder dependency. 

Does anyone have an idea what the best approach is to implementing this feature?

**Comment by jmarcher** [comment]
@n4p4 Here is not the place for such matters, try on Laracasts forum

**Comment by n4p4** [comment]
@jmarcher I'm developing a custom engine and I want to add Global search to it. Therefore, I believe this is the correct place. Perhaps, some new option may be added as a result of my raised issue.

**Comment by jmarcher** [comment]
@n4p4 If you want to make a proposal that is fine but you are asking for specific implementation advices and here is not the place to solve such matters

**Comment by n4p4** [comment]
I want ideas from the developers here so that maybe we could add support or helpful options for global search.

**Comment by jitendra-1217** [comment]
@n4p4 : Did you implement(or find) something around it? Or has this discussion been moved to forum somewhere?

**Comment by driesvints** [comment]
There's currently no support for this but https://github.com/algolia/scout-extended is in the works which should support this if you use Algolia.
