### ISSUE TITLE
Search downtime when running `scout:import` with Algolia

### ISSUE THREAD

**Issue by caiodounis** [laravel/scout#790]
### Scout Version

10.3

### Scout Driver

Algolia

### Laravel Version

10.10

### PHP Version

8.2.7

### Description

I'm encountering a problem when executing php `php artisan scout:import "App\Models\Product"`: it causes a downtime in my search services due to the clearing of all product records in the Algolia index. Is there a method to reimport these products in a way that overwrites the existing ones, instead of clearing the index?

I attempted to update products individually with a custom command, but this method was too slow and eventually hit Algolia's limits on individual updates.

### Steps To Reproduce

Running `php artisan scout:import "App\Models\Product"`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
