### ISSUE TITLE
Method Laravel\Scout\Builder::withSearchParameters does not exist.

### ISSUE THREAD

**Issue by crivion** [laravel/scout#791]
### Scout Version

10.8

### Scout Driver

Typesense

### Laravel Version

10

### PHP Version

10

### Database Driver & Version

0

### SDK Version

0

### Meilisearch CLI Version

0

### Description

I'm trying the new typesense scout integration.
In the docs it says

"Typesense allows you to modify your [search parameters](https://typesense.org/docs/latest/api/search.html#search-parameters) dynamically when performing a search operation via the withSearchParameters method:"
 
Todo::search('Groceries')->**withSearchParameters**([
    'query_by' => 'title, description'
])->get();

However when try that it says:
Method Laravel\Scout\Builder::**withSearchParameters** does not exist.

### Steps To Reproduce

Just install laravel scout and configure it to work with typesense

**Comment by jasonbosco** [comment]
Related to this: https://github.com/laravel/docs/pull/9250#issuecomment-1900113205 (has a potential workaround for now in that comment). 

@karakhanyans is actively looking into this.

**Comment by driesvints** [comment]
@crivion you are using the typesense driver are you? because the issue report says you're using the collection driver?

**Comment by crivion** [comment]
@driesvints yes, you don't have an option when opening an issue to select typesense 

![SCR-20240122-lj8](https://github.com/laravel/scout/assets/15253384/36349d49-7ed8-44c8-9d28-01cd071130fe)

**Comment by driesvints** [comment]
Ah thanks for noting that. I added it now.

**Comment by crivion** [comment]
No problem at all, more context if required (for whoever needs a quick ref)

![SCR-20240122-lko](https://github.com/laravel/scout/assets/15253384/ec6ef35b-1129-4f3f-b756-3fd2150659d9)

**Comment by karakhanyans** [comment]
@driesvints @crivion @jasonbosco the issue has been fixed in this PR: https://github.com/laravel/scout/pull/794

The `withSearchParameters` has been removed and instead we should use `->options()` method.

**Comment by driesvints** [comment]
Will be in today's release. @karakhanyans thanks for your PR. Also feel free to send one in to the docs 👍
