### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by tomschlick** [laravel/scout#8]
Looks like this repo needs the StyleCI service hook 👍 

/cc @GrahamCampbell

**Comment by lucasmichot** [comment]
Any news on this?
Maybe @driesvints ?

**Comment by driesvints** [comment]
@lucasmichot I'll check in on this again with Taylor tomorrow.

**Comment by driesvints** [comment]
StyleCI is now enabled on the latest branches (7.0 & master).
