### ISSUE TITLE
Warn when using null driver

### ISSUE THREAD

**Issue by jasonvarga** [laravel/scout#800]
I just spent some time debugging why Scout didn't seem to be working on a site.

Running `scout:import` etc gave expected feedback. e.g. `Imported [App\Product] models up to ID: 528`. It all looked fine.

Turns out I had Scout configured to use the null driver. Bonehead move by me, yes, but if the command gave a warning that would have saved me some time.

Would you be open to a PR to add a warning on the commands when you're using the null driver? I'd be happy to PR it myself.

```diff
→ php artisan scout:import "App\Product" 
+Warning: The null driver is being used.
Imported [App\Product] models up to ID: 100
All [App\Product] records have been imported.
```

**Comment by driesvints** [comment]
Hi @jasonvarga. We don't really consider this to be a real problem sorry. In the end you forgot to configure the correct driver. But you can send along that PR if you like and we'll consider it, thanks.
