### ISSUE TITLE
Searchable not sync to meilisearch with other index

### ISSUE THREAD

**Issue by cuonglv31** [laravel/scout#809]
### Scout Version

^10.3

### Scout Driver

Meilisearch

### Laravel Version

9

### PHP Version

8.2

### Database Driver & Version

Mysql 8.0

### Description

In the model, I edited the searchable, but in the controller, I updated the value into the DB and synchronized via meilisearch with the command `StampCode::query()->where("index", 1)->searchable();`, Check meilisearch has no data with the revised index.
<img width="666" alt="image" src="https://github.com/laravel/scout/assets/16288464/ca48884f-daf5-475b-9d3e-856a07fbff82">

### Steps To Reproduce

1. StampCode model create func searchableAs
2. StampCode Controller update item and sync to meilisearch `StampCode::query()->where("index", 1)->searchable();`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
