### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by niyazialpay** [laravel/scout#814]
Hello,

In the link below, I explained a problem I encountered with MongoDB. I also explained how I solved it in the same topic. You can make Scout support MongoDB by making an update to this topic.

[https://github.com/orgs/meilisearch/discussions/708](https://github.com/orgs/meilisearch/discussions/708)

I also created a pull request for this

[https://github.com/laravel/scout/pull/813](https://github.com/laravel/scout/pull/813)

**Comment by driesvints** [comment]
I'm sorry but we have no plans for MongoDB right now.
