### ISSUE TITLE
paginate() + query() = wrong pagination

### ISSUE THREAD

**Issue by t3946** [laravel/scout#821]
### Scout Version

10.8

### Scout Driver

Meilisearch

### Laravel Version

10.17

### PHP Version

8.1.4

### Database Driver & Version

MariaDB 10.5

### Meilisearch CLI Version

1.7.0

### Description

I have table cars (id, title, price). I need find "Opel" with price between 1 .. 1000$.

Solve:
```PHP
\App\Models\Car::search('Opel')
    ->query(fn ($query) => $query->where('price', '<=', 1000))
    ->paginate(20);
```
Result expected: Get one page with 20 items.
Result real: Got five pages with 3-5 items on every page.

### Steps To Reproduce

read desc

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by t3946** [comment]
Ok. I think scout can't correctly work with paginate() and query() methods in one query. So my solve is extends limits like this

config/scout.php
```PHP
'index-settings' => [
    \App\Models\Car::class => [
        'pagination' => [
            'maxTotalHits' => 30000,
        ],
    ],
],
```

controller.php
```PHP
$collection= \App\Models\Car::search($text)
    ->query(...)
    ->take(30000)
    ->get();
    
$total = $collection->count();
$perPage = 20;
$currentPage = 1;

$paginator = new LengthAwarePaginator(
    $collection->forPage($currentPage, $perPage),
    $total,
    $perPage,
    $currentPage
);
```
This code will solve my problem with pagination (in fact i'm selecting whole docs and able to do anything with it).
And i get next limitation the 30000 documents search result maximum (this will take about 1.5gb ram what is not problem for my server).
