### ISSUE TITLE
Scout import for large datasets fails after upgrading from 10.X to Laravel 11.X

### ISSUE THREAD

**Issue by pritborteam** [laravel/scout#822]
### Scout Version

^10.8

### Scout Driver

Typesense

### Laravel Version

11.4.0

### PHP Version

8.3

### Database Driver & Version

MariaDB-10.11.7

### SDK Version

0.26

### Description

I had no issue with import/flush with latest laravel Scout with Laravel 10.X and using typesense v.0.26. Post migration to Laravel 11.X, I am unable to import large data using scout:import command for typesense. After indexing first 500 documents, it says my collection with the index name already exists.  Issue is not visible with small data less than 500.
![scout-error](https://github.com/laravel/scout/assets/91776549/cc763d75-7adb-4cbe-b3c5-1899029a6ecd)

### Steps To Reproduce

1. Create a table with large data. May be 5000 or 10000.
2. Do follow the steps of creating toSearchableArray() and Collection as per documentation.
3. Use "php artisan scout:import "App\Models\YourModel"
4. After indexing first 500, you will see error saying collection with the name already exists.
5. On typesense server I  find first batch of initial 500 records already indexed.
6. So while attempting next batch to index, it says collection is already present.

**Comment by jasonbosco** [comment]
Could you try setting `connection_timeout_seconds` in the `typesense` section in scout config file to say 900?

**Comment by pritborteam** [comment]
> Could you try setting `connection_timeout_seconds` in the `typesense` section in scout config file to say 900?

This does not solve the problem. But when try cleaning using
php artisan cache:clear
This does the job well.

But I have below scenarios for issue and its very evident it is something to do with cache:-

Scenario: 1
1. Scout Flush
2. Scout Import (Issue is seen)

Scenario: 2
1. Scout Flush
2. Scout Import (Issue is seen)
3. Clear cache using artisan command
4. Then Scout Import again (Issue is not seen) and import is successful.

Scenario: 3
1. Scout Flush
2. Clear cache
3. Scout Import (Issue seen)

Scenario: 4
1. Clear cache
2. Scout Flush
3. Scout Import (Issue seen)

Observation:
The issue will be always visible when you run the Scout Import for the first time. The only way to solve it is to first run the Scout Import once, let it fail and then run artisan clear cache and then run Scout Import again. This is not great. 



BTW i use Redis for cache. But I was using this even in Laravel10 and had no issue.

**Comment by driesvints** [comment]
Hi @pritborteam. Looks like you found a solution to your issue so I'm going to close this one. I don't feel we need to take action right now because we only have one report for this, sorry.

**Comment by pritborteam** [comment]
> Hi @pritborteam. Looks like you found a solution to your issue so I'm going to close this one. I don't feel we need to take action right now because we only have one report for this, sorry.

But this issue is evident. Why do I need to clear the cache only after every first failure? Clearing the cache before even issue is seen is not working.

**Comment by pritborteam** [comment]
This issue is also seen when you completely clear all database and run seeder again.

**Comment by AbdullahFaqeir** [comment]
I'll take a loot into this

**Comment by erichowey** [comment]
I'm also seeing this issue when my database seeders run. There's no issue when I try to import:

![image](https://github.com/laravel/scout/assets/4033313/30de931c-0293-4d8c-a37c-c503f053b3dc)

**Comment by pritborteam** [comment]
> I'm also seeing this issue when my database seeders run. There's no issue when I try to import:
> 
> ![image](https://private-user-images.githubusercontent.com/4033313/324087246-30de931c-0293-4d8c-a37c-c503f053b3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTg0MjMsIm5iZiI6MTcxMzYxODEyMywicGF0aCI6Ii80MDMzMzEzLzMyNDA4NzI0Ni0zMGRlOTMxYy0wMjkzLTRkOGMtYTM3Yy1jNTAzZjA1M2IzZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMTMwMjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUxNmU4ZDM4NDk5NjkzZTY1ODg2MmVkZTQyYmI2Mjk2ZTc1MTNlYjUwZGRjYWQ2MDg3OWU0ZjYzZjAxZGZkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NTHm9xhkmHtPYcdKgqbagbDnV3Bgt62uB7j7QwOJ9BE)

To see the issue in Scout Import, try having dataset more than 500 if your batch import size of 500.  if fails in second iterationa. In seed, i guess it is one file each but in Scout Import it is batch import. Resolution is only after first failure cache clear.

**Comment by voveson** [comment]
> I'll take a loot into this

Hi [Abdullah](https://github.com/AbdullahFaqeir)! Just wondering – have you had a chance to look into this yet?
