### ISSUE TITLE
Saving a Soft-Deleted Eloquent Model makes it searchable again

### ISSUE THREAD

**Issue by matrad** [laravel/scout#834]
### Scout Version

10.1.0

### Scout Driver

Algolia

### Laravel Version

11.x

### PHP Version

8.1.4

### Description

When we retrieve a soft-deleted model from the Database and Save this model, it becomes again searchable.

### Steps To Reproduce

 - Create a new Model entry in the Database
 - (Soft) Delete the created model
 - Retrieve the Soft-Deleted Model with `Model::withTrashed()->where('id', 111)->first()`
 - Update a Property on the Model, like `$model->comment = 'test';`
 - Save the Model with `$model->save()`
 - The `saved()` Listener is fired and the Model becomes searchable, but it's still trashed
 - The model should not be searchable if the `soft_delete` config is set to `false`

**Comment by Boorinio** [comment]
Hey @matrad 
There is an example in the repo with the following 
![image](https://github.com/laravel/scout/assets/13625730/2712d4f5-11eb-43da-a1eb-22994b6e49c8)

Do you have the trashed check in the shouldBeSearchable in your model? Cause from what I am seeing it should take care of it from the observer.

**Comment by driesvints** [comment]
Thanks @Boorinio
