### ISSUE TITLE
will scout support mapping?

### ISSUE THREAD

**Issue by mehrdaad** [laravel/scout#85]
What I want to do is to use language analyzers (https://www.elastic.co/guide/en/elasticsearch/guide/current/using-language-analyzers.html), but seems like scout doesn't support custom mapping between models and documents.  
Is there any way I can accomplish this?

**Comment by Melcus** [comment]
I'm interested in this as well.

**Comment by toby1991** [comment]
as well too

**Comment by brino** [comment]
There is no reason you couldn't overwrite the mapping with a custom one, or index settings for that matter. You just post them with a REST client to the elastic cluster directly. Then, index your data. Granted you're still somewhat limited, but the point is you can quickly accomplish this outside of scout without too much trouble.

**Comment by mehrdaad** [comment]
Actually, you can create you custom mapping with a curl command in your cluster, the import your data from scout via ``scout:import`` laravel scout will respect your mapping, but you need to override ``toSearchableArray`` to match with your custom mapping.  
An example would be:  

    	#Create a new index with desired analyzer

	curl -XPUT 'localhost:9200/ashojash' -d '
	{
	  "settings":{
		"analysis":{
		  "char_filter":{
			"zero_width_spaces":{
			  "type":"mapping",
			  "mappings":[
				"\\u200C=> "
			  ]
			}
		  },
		  "filter":{
			"persian_stop":{
			  "type":"stop",
			  "stopwords":"_persian_"
			},
			"autocomplete_filter":{
			  "type":"edge_ngram",
			  "min_gram":1,
			  "max_gram":20
			}
		  },
		  "analyzer":{
			"autocomple":{
			  "type":"custom",
			  "tokenizer":"standard",
			  "char_filter":[
				"zero_width_spaces"
			  ],
			  "filter":[
				"autocomplete_filter",
				"lowercase",
				"arabic_normalization",
				"persian_normalization",
				"persian_stop"
			  ]
			},
			"persian":{
			  "type":"custom",
			  "tokenizer":"standard",
			  "char_filter":[
				"zero_width_spaces"
			  ],
			  "filter":[
				"lowercase",
				"arabic_normalization",
				"persian_normalization",
				"persian_stop"
			  ]
			}
		  }
		}
	  },
	  "mappings":{
		"places":{
		  "properties":{
			"name":{
			  "type":"string",
			  "analyzer":"persian"
			},
			"name_suggest":{
			  "type":"string",
			  "analyzer":"autocomple"
			}
		  }
		}
	  }
	}'

And your ``toSearchableArray`` would be like:  

	public function toSearchableArray()
		{
			$array = array("name" => $this->name, "name_suggest" => $this->name, $this->getKeyName() => $this->getKey());
			return $array;
		}

If you get any more problems, just mention me.
