### ISSUE TITLE
Infinite loop in AsPivot::newQueryForRestoration when indexing a custom MorphPivot model

### ISSUE THREAD

**Issue by stephenr85** [laravel/scout#856]
### Scout Version

10.11.1

### Scout Driver

Meilisearch

### Laravel Version

10.48.16

### PHP Version

8.2

### SDK Version

1.9

### Meilisearch CLI Version

1.6.2

### Description

I have a model that extends MorphPivot, and the MakeSearchable job fails due to the following error:

```
local.ERROR: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '512' frames {"exception":"[object] (Error(code: 0): Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '512' frames at /Users/stephen/Workspaces/frameworks/thingson.tv/things-on-tv/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php:278
```

### Steps To Reproduce

Create a model that extends MorphPivot.

MyPivotModel::first()->searchable();

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by stephenr85** [comment]
How is this not a bug with the library? I don't get this error on other
models. It appears to be a bug with the library indexing Morph Pivot
models. I removed everything from my model except boilerplate to make sure
it wasn't something else problematic in my model.

**Comment by francoism90** [comment]
I also have encounter this issue, it seems to only happen when you queue.

@stephenr85 Did you find any solution?
