### ISSUE TITLE
Need a timeout options

### ISSUE THREAD

**Issue by imnhasan** [laravel/scout#859]
I'm using Laravel Scout, but I can't find a timeout option. Is there a way to set a timeout or configure the search to use Meilisearch? I'm looking for something along those lines.

```
$search = Product::search(request()->q)
    ->options([
    'filter' => $filter,
    'limit' => (int)$limit,
    'offset' => (int)$offset,
    'timeoutMs' => 3, // i need something for timeout
    ])
    ->when(($inStock), function ($query) {
        return $query->where('stock_status ', 'In Stock');
    })
    ->orderBy('stock_status_id', 'asc')
    ->raw();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
