### ISSUE TITLE
Issues with docs (which I can't raise on docs repo..)

### ISSUE THREAD

**Issue by stratboy** [laravel/scout#860]
### Scout Version

latest

### Scout Driver

Meilisearch

### Laravel Version

11

### PHP Version

8.2

### Description

You documentation lacks important things, and I cannot post issues on the docs repository, so I'm writing here. 
First, you do not mention the scoutMetadata() method. Second, you don't mention and explain the callback parameter of the search method. Third, you do not eplain how to check things like response.estimatedTotalHits on the server side (on a controller). In the end, for doing extremely easy things, I'm loosing really a lot of time looking for relevant infos in google and in chatgpt. This is a shame and makes Scout a lot less useful than it in fact is.

### Steps To Reproduce

read the docs.

**Comment by driesvints** [comment]
We appreciate PR's to improve the docs.

**Comment by stratboy** [comment]
Already did yesterday for scoutMetadata(), but for the rest, I would appreciate some source of knowledge as well..
