### ISSUE TITLE
Typesense: When using an empty query callback, causes total results to significantly change

### ISSUE THREAD

**Issue by Braunson** [laravel/scout#866]
### Scout Version

10.11.2

### Scout Driver

Typesense

### Laravel Version

10.48.2

### PHP Version

8.2.23

### Description

There's another issue with v10.11.2 I've noticed in #865 but this issue does appear in both v10.11.2 and v10.11.3 (I haven't tested older versions)

```php
$results = Names::search($this->keyword)
    ->options([
        'filter_by' => $this->buildFilterString(),
        'sort_by' => implode(',', $this->sortBy),
    ])
    ->paginate(48);
```

The above returns ~22k results for me locally

However once I add this empty callback query, the results drop from ~22k to 48 (the pagination number) and there's no next page/page numbers shown:
```php
->query(function ($query) {})
```

Query wise, nothing has changed. My initial goal was to eager load a relation to pull one column in to the hydrated returned models but found out even just adding an empty query callback causes the total results to drop significantly

### Steps To Reproduce

1. Install Laravel Scout, Typesense
2. Setup model with thousands of records and import with Scout
3. Setup model relation
4. Use query above using code to re-test

**Comment by tharropoulos** [comment]
I'll see to this ASAP, will update once I have figured out what's going on

**Comment by Braunson** [comment]
Looking deeper into things it looks like the cause is the Scout 'Builder' class specifically line 499 down in the 'getTotalCount' method. If we return '$totalCount' and remove the is null check on query callback it shows the right number of total results.

**Comment by crynobone** [comment]
Seems like related PR has been merged. Feel free to report back if you still have an issue.
