### ISSUE TITLE
Multiple Execution of MakeSearchable Job in Production Causes Memory Exhaustion

### ISSUE THREAD

**Issue by RicardoAugustoTulio** [laravel/scout#870]
### Scout Version

10.8

### Scout Driver

Meilisearch

### Laravel Version

10.48

### PHP Version

8.1

### Meilisearch CLI Version

1.8.0

### Description

We are encountering an issue in production where the makeSearchable job is being executed multiple times for a single product, which eventually leads to memory exhaustion.

In our local environment, the job runs as expected, with only a single execution per product, as seen in the attached logs.

In production, the job is triggered multiple times for the same product, resulting in high memory usage and eventually causing the system to run out of memory.

I've attached the relevant logs for the loca land prod  environment.

Any assistance in resolving this issue would be greatly appreciated.
Local:
![image](https://github.com/user-attachments/assets/d2e87a6d-c50d-4720-9845-c5cd3107bcdb)
Prod:
![image](https://github.com/user-attachments/assets/fe66219d-3790-4e85-bb1a-505d9ee3e35a)

### Steps To Reproduce

Trigger the makeSearchable job for a product in production.
Observe that the job runs multiple times for the same product, unlike the local environment.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
