### ISSUE TITLE
Searchable trait not working outside of App namespace

### ISSUE THREAD

**Issue by DonxDaniyar** [laravel/scout#871]
### Scout Version

10.11.4

### Scout Driver

Meilisearch

### Laravel Version

10.48.22

### PHP Version

8.1.5

### Meilisearch CLI Version

1.10.20

### Description

Searchable trait on Modules namespace on nWidart/laravel-modules package's Modules namespave, for example Modules\Post\App\Modules\Post not working.

![image](https://github.com/user-attachments/assets/cd169a59-aecc-4223-8b4d-84f207a9702c)

### Steps To Reproduce

1)Install fresh Laravel 10
2) Install nwidart/laravel-modules 10.0.6
3) Create Module by command `php artisan module:make`
4) Create Model on module
5) Try to use Searchable trait and use this model

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
