### ISSUE TITLE
Algolia client v4 Bug

### ISSUE THREAD

**Issue by repirisyan** [laravel/scout#885]
### Scout Version

10.11.6

### Scout Driver

Algolia

### Laravel Version

11.31.0

### PHP Version

8.2.24

### Database Driver & Version

MariaDB 10.6

### Description

when i use query search it show error like this Undefined array key "batch_size", it happen when i upgrade the algolia client php to v4, before i update it show an error that  Cannot use object of type Algolia\AlgoliaSearch\Config\SearchConfig as array on laravel

### Steps To Reproduce

its basicly, error on the query search in my case

**Comment by crynobone** [comment]
Fixed in https://github.com/laravel/scout/releases/tag/v10.11.7
