### ISSUE TITLE
Request Multiple Indice. Algolia.

### ISSUE THREAD

**Issue by yuqinz** [laravel/scout#89]
As Algolia doesn't allow sort on query time, we need set up duplicates for different sorting strategy. So multiple indice with different setting required. Thanks.

**Comment by julienbourdeau** [comment]
I think this way of handling sorting is specific to algolia so it probably won't make its way to scout.

What do you think of an extra package adding the feature. For instance you could add a trait `use AlgoliaMultiSorting;` and it would provide a method to set replica settings. Something like:

```php
public function sorting() {
    return [
        'products_by_price_asc',
        'products_by_price_desc'
    ];
}
```

**Comment by julienbourdeau** [comment]
You can set the replica settings in your dashboard, then select the correct index via the `within()` method ([doc](https://laravel.com/docs/5.5/scout#searching)).

If you're interested, I made a package to import/export your settings.
https://github.com/algolia/laravel-scout-settings
