### ISSUE TITLE
PHP Parse error 1.1.6

### ISSUE THREAD

**Issue by AndreyBobrov** [laravel/scout#91]
after updating to 1.1.6 immediately (at php artisan optimize) get this error:

PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /vendor/laravel/scout/src/Console/FlushCommand.php on line 32

PHP 5.6

**Comment by denisrpriebe** [comment]
Go to the FlushCommand.php file and change the line:

`(new $class)::removeAllFromSearch();`

to:

```
$newClass = new $class;
$newClass::removeAllFromSearch();
```

**Comment by ashtonzheng** [comment]
I have the same issue , rolled back to version 1.1.5 and the error is gone.

**Comment by muhamin** [comment]
same situation . opted for denis's temp fix till this gets updated .

**Comment by EliasZ** [comment]
This seems to be a PHP issue as that is valid syntax since PHP 5.3.

>As of PHP 5.3.0, it's possible to reference the class using a variable.

http://php.net/manual/en/language.oop5.paamayim-nekudotayim.php

**Comment by AndreyBobrov** [comment]
fixed, thanks.
