### ISSUE TITLE
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

### ISSUE THREAD

**Issue by khaninejad** [laravel/scout#94]
Symfony\Component\Debug\Exception\FatalErrorException · vendor/laravel/scout/src/Console/FlushCommand.php:32

syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)
Stage

local
Severity

error
Stacktrace summary

vendor/laravel/scout/src/Console/FlushCommand.php:32 · [main]

**Comment by brad82** [comment]
I also experience this error after updating when trying to perform any console commands

**Comment by anteriovieira** [comment]
The solution to this issue has already been resolved https://github.com/laravel/scout/pull/93

We are waiting @taylorotwell launch the new version with this fix.

**Comment by anteriovieira** [comment]
Fix version [v1.1.7](https://github.com/laravel/scout/blob/v1.1.7/src/Console/FlushCommand.php#L32-L33)

**Comment by madfortech** [comment]
I'start learning laravel 
Welcome.blade.php  -------------code
`@extends('layout.main')
@section('content')
<p class="h1">Himanshu Nishad</p> 
@if(session('successMsg'))

<div class="alert alert-success" role="alert">
  {{session('successMsg')}}
</div>

@endif

<div class="container">
<table class="table">
  <thead class="black white-text">
    <tr>
      <th scope="col">#</th>
      <th scope="col">first Name</th>
      <th scope="col">last name</th>
      <th scope="col">email</th>
      <th scope="col">phone</th>
    </tr>
  </thead>
  <tbody>
    @foreach($students as $students 'students')
    <tr>
      <th scope="row">{{$student->id}}</th>
      <td>{{$student->firstname}}</td>
      <td>{{$student->lastname}}</td>
      <td>@{{$student->Email}}</td>
      <td>{{$student->phone}}</td>
      <td>Edit || Delete</td>
    </tr>

    @endforeach
  </tbody>
</table>
</div>


@endsection

`
`<?php --------------- StudentController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Student;


class StudentController extends Controller
{
    public function index(){
        $students = Student::all();
        return View('welcome',compact('students'));
    }

    public function create(){
        return View('create');
    }

    public function store(Request $request){

        // $this->validate($request,[
        //     'firstName' => 'required|min:4|max:20',
        //     'lastName' => 'required|min:4|max:20',
        //     'Email' => 'required|min:4|max:20',
        //     'phone' => 'required|min:4|max:20'
        // ]);
         
        $student = new Student;

        $student -> firstName = $request->firstName;
        $student -> lastName = $request->lastName;
        $student -> Email = $request->Email;
        $student -> phone = $request->phone;
        $student->save();
        return redirect(route('home'))->with('successMsg','Student Successfully Added');
    }


}
`
syntax error, unexpected ''students'' (T_CONSTANT_ENCAPSED_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) (View: C:\xampp7.4.10\htdocs\blog\resources\views\welcome.blade.php)
any one help me
