### ISSUE TITLE
Relational Search

### ISSUE THREAD

**Issue by naumanahmed19** [laravel/scout#97]
Can anyone please tell me how to implement something like this
I have 2 tables

Movies (hasManyActors)
Actors (belongsToMovies)

now i want to search `movies ` by actor name. Before scout  I was doing something like this.

    Movies::whereHas('actors', function ($q, $searchterm) {
        $q->where('name', 'like', $searchterm);
     })->with('actors')->get();

**Comment by naumanahmed19** [comment]
got t using algolia relations

**Comment by MevlutOzdemir** [comment]
How did you do this ?
